MOM6: src/framework/MOM_diag_vkernels.F90 File Reference
MOM_diag_vkernels.F90 File Reference
Modules
module mom_diag_vkernels
Provides kernels for single-column interpolation, re-integration (re-mapping of integrated quantities) and intensive-variable remapping in the vertical.
Functions/Subroutines
subroutine, public mom_diag_vkernels::interpolate_column (nsrc, h_src, u_src, ndest, h_dest, missing_value, u_dest)
Linearly interpolate interface data, u_src, from grid h_src to a grid h_dest.
subroutine, public mom_diag_vkernels::reintegrate_column (nsrc, h_src, uh_src, ndest, h_dest, missing_value, uh_dest)
Conservatively calculate integrated data, uh_dest, on grid h_dest, from layer-integrated data, uh_src, on grid h_src.
logical function, public mom_diag_vkernels::diag_vkernels_unit_tests ()
Returns true if any unit tests for module MOM_diag_vkernels fail.
logical function test_interp (msg, nsrc, h_src, u_src, ndest, h_dest, u_true)
Returns true if a test of interpolate_column() produces the wrong answer.
logical function test_reintegrate (msg, nsrc, h_src, uh_src, ndest, h_dest, uh_true)
Returns true if a test of reintegrate_column() produces the wrong answer.
Variables
logical mom_diag_vkernels::verbose_diag_vkernels_unit_tests = .true.
Function/Subroutine Documentation
test_interp()
logical function diag_vkernels_unit_tests::test_interp (character(len=*), intent(in) msg, integer, intent(in) nsrc, real, dimension(nsrc), intent(in) h_src, real, dimension(nsrc+1), intent(in) u_src, integer, intent(in) ndest, real, dimension(ndest), intent(in) h_dest, real, dimension(ndest+1), intent(in) u_true) private
Returns true if a test of interpolate_column() produces the wrong answer.
Parameters
[in] msg Message to label test
[in] nsrc Number of source cells
[in] h_src Thickness of source cells
[in] u_src Values at source cell interfaces
[in] ndest Number of destination cells
[in] h_dest Thickness of destination cells
[in] u_true Correct value at destination cell interfaces
Definition at line 282 of file MOM_diag_vkernels.F90.
     character(len=*),         intent(in) :: msg !< Message to label test
     integer,                  intent(in) :: nsrc !< Number of source cells
     real, dimension(nsrc),    intent(in) :: h_src !< Thickness of source cells
     real, dimension(nsrc+1),  intent(in) :: u_src !< Values at source cell interfaces
     integer,                  intent(in) :: ndest !< Number of destination cells
     real, dimension(ndest),   intent(in) :: h_dest !< Thickness of destination cells
     real, dimension(ndest+1), intent(in) :: u_true !< Correct value at destination cell interfaces
     ! Local variables
     real, dimension(ndest+1) :: u_dest ! Interpolated value at destination cell interfaces
     integer :: k
     real :: error
     logical :: print_results
     ! Interpolate from src to dest
     call interpolate_column(nsrc, h_src, u_src, ndest, h_dest, missing_value, u_dest)
     test_interp = .false.
     do k=1,ndest+1
       if (u_dest(k)/=u_true(k)) test_interp = .true.
     enddo
     if (verbose_diag_vkernels_unit_tests .or. test_interp) then
       write(0,'(2a)') ' Test: ',msg
       write(0,'(a3,3(a24))') 'k','u_result','u_true','error'
       do k=1,ndest+1
         error = u_dest(k)-u_true(k)
         if (error==0.) then
           write(0,'(i3,3(1pe24.16))') k,u_dest(k),u_true(k),u_dest(k)-u_true(k)
         else
           write(0,'(i3,3(1pe24.16),x,a)') k,u_dest(k),u_true(k),u_dest(k)-u_true(k),'<--- WRONG!'
         endif
       enddo
     endif
References mom_diag_vkernels::interpolate_column(), and mom_diag_vkernels::verbose_diag_vkernels_unit_tests.
Referenced by mom_diag_vkernels::diag_vkernels_unit_tests().
test_reintegrate()
logical function diag_vkernels_unit_tests::test_reintegrate (character(len=*), intent(in) msg, integer, intent(in) nsrc, real, dimension(nsrc), intent(in) h_src, real, dimension(nsrc), intent(in) uh_src, integer, intent(in) ndest, real, dimension(ndest), intent(in) h_dest, real, dimension(ndest), intent(in) uh_true) private
Returns true if a test of reintegrate_column() produces the wrong answer.
Parameters
[in] msg Message to label test
[in] nsrc Number of source cells
[in] h_src Thickness of source cells
[in] uh_src Values of source cell stuff
[in] ndest Number of destination cells
[in] h_dest Thickness of destination cells
[in] uh_true Correct value of destination cell stuff
Definition at line 318 of file MOM_diag_vkernels.F90.
     character(len=*),       intent(in) :: msg !< Message to label test
     integer,                intent(in) :: nsrc !< Number of source cells
     real, dimension(nsrc),  intent(in) :: h_src !< Thickness of source cells
     real, dimension(nsrc),  intent(in) :: uh_src !< Values of source cell stuff
     integer,                intent(in) :: ndest !< Number of destination cells
     real, dimension(ndest), intent(in) :: h_dest !< Thickness of destination cells
     real, dimension(ndest), intent(in) :: uh_true !< Correct value of destination cell stuff
     ! Local variables
     real, dimension(ndest) :: uh_dest ! Reintegrated value on destination cells
     integer :: k
     real :: error
     logical :: print_results
     ! Interpolate from src to dest
     call reintegrate_column(nsrc, h_src, uh_src, ndest, h_dest, missing_value, uh_dest)
     test_reintegrate = .false.
     do k=1,ndest
       if (uh_dest(k)/=uh_true(k)) test_reintegrate = .true.
     enddo
     if (verbose_diag_vkernels_unit_tests .or. test_reintegrate) then
       write(0,'(2a)') ' Test: ',msg
       write(0,'(a3,3(a24))') 'k','uh_result','uh_true','error'
       do k=1,ndest
         error = uh_dest(k)-uh_true(k)
         if (error==0.) then
           write(0,'(i3,3(1pe24.16))') k,uh_dest(k),uh_true(k),uh_dest(k)-uh_true(k)
         else
           write(0,'(i3,3(1pe24.16),x,a)') k,uh_dest(k),uh_true(k),uh_dest(k)-uh_true(k),'<--- WRONG!'
         endif
       enddo
     endif
References mom_diag_vkernels::reintegrate_column(), and mom_diag_vkernels::verbose_diag_vkernels_unit_tests.
Referenced by mom_diag_vkernels::diag_vkernels_unit_tests().