MOM6: src/framework/MOM_string_functions.F90 File Reference
MOM_string_functions.F90 File Reference
Modules
module mom_string_functions
Functions/Subroutines
character(len=len(input_string)) function, public mom_string_functions::lowercase (input_string)
character(len=len(input_string)) function, public mom_string_functions::uppercase (input_string)
character(len=19) function, public mom_string_functions::left_int (i)
character(len=1320) function, public mom_string_functions::left_ints (i)
character(len=32) function, public mom_string_functions::left_real (val)
character(len=1320) function, public mom_string_functions::left_reals (r, sep)
logical function mom_string_functions::isformattedfloatequalto (str, val)
character(len=120) function, public mom_string_functions::extractword (string, n)
Returns the string corresponding to the nth word in the argument or "" if the string is not long enough. Both spaces and commas are interpreted as separators.
character(len=120) function, public mom_string_functions::extract_word (string, separators, n)
Returns the string corresponding to the nth word in the argument or "" if the string is not long enough. Words are delineated by the mandatory separators argument.
integer function, public mom_string_functions::extract_integer (string, separators, n, missing_value)
Returns the integer corresponding to the nth word in the argument.
real function, public mom_string_functions::extract_real (string, separators, n, missing_value)
Returns the real corresponding to the nth word in the argument.
character(len=120) function, public mom_string_functions::remove_spaces (string)
Returns string with all spaces removed.
logical function, public mom_string_functions::string_functions_unit_tests ()
Returns true if a unit test of string_functions fails.
logical function localtests (str1, str2)
logical function localtesti (i1, i2)
logical function localtestr (r1, r2)
character(len=len(dir)+2) function, public mom_string_functions::slasher (dir)
Returns a directory name that is terminated with a "/" or "./" if the argument is an empty string.
Function/Subroutine Documentation
localtesti()
logical function string_functions_unit_tests::localtesti (integer i1, integer i2) private
Definition at line 384 of file MOM_string_functions.F90.
     integer :: i1,i2
     localtesti=.false.
     if (i1/=i2) localtesti=.true.
     if (localtesti .or. verbose) then
       write(*,*) i1,i2
       if (localtesti) write(*,*) i1,'!=',i2, '<-- FAIL'
     endif
Referenced by mom_string_functions::string_functions_unit_tests().
localtestr()
logical function string_functions_unit_tests::localtestr (real r1, real r2) private
Definition at line 393 of file MOM_string_functions.F90.
     real :: r1,r2
     localtestr=.false.
     if (r1/=r2) localtestr=.true.
     if (localtestr .or. verbose) then
       write(*,*) r1,r2
       if (localtestr) write(*,*) r1,'!=',r2, '<-- FAIL'
     endif
Referenced by mom_string_functions::string_functions_unit_tests().
localtests()
logical function string_functions_unit_tests::localtests (character(len=*) str1, character(len=*) str2) private
Definition at line 375 of file MOM_string_functions.F90.
     character(len=*) :: str1, str2
     localtests=.false.
     if (trim(str1)/=trim(str2)) localtests=.true.
     if (localtests .or. verbose) then
       write(*,*) '>'//trim(str1)//'<'
       if (localtests) write(*,*) trim(str1),':',trim(str2), '<-- FAIL'
     endif
Referenced by mom_string_functions::string_functions_unit_tests().