MOM6: src/tracer/MOM_neutral_diffusion.F90 File Reference
MOM_neutral_diffusion.F90 File Reference
#include <MOM_memory.h>
#include "version_variable.h"
Data Types
type mom_neutral_diffusion::neutral_diffusion_cs
Modules
module mom_neutral_diffusion
A column-wise toolbox for implementing neutral diffusion.
Functions/Subroutines
logical function, public mom_neutral_diffusion::neutral_diffusion_init (Time, G, param_file, diag, CS)
Read parameters and allocate control structure for neutral_diffusion module.
subroutine, public mom_neutral_diffusion::neutral_diffusion_diag_init (Time, G, diag, C_p, Reg, CS)
Diagnostic handles for neutral diffusion tendencies.
subroutine, public mom_neutral_diffusion::neutral_diffusion_calc_coeffs (G, GV, h, T, S, EOS, CS)
Calculate remapping factors for u/v columns used to map adjoining columns to a shared coordinate space.
subroutine, public mom_neutral_diffusion::neutral_diffusion (G, GV, h, Coef_x, Coef_y, Tracer, m, dt, name, CS)
Update tracer concentration due to neutral diffusion; layer thickness unchanged by this update.
subroutine mom_neutral_diffusion::interface_scalar (nk, h, S, Si, i_method)
Returns interface scalar, Si, for a column of layer values, S.
real function mom_neutral_diffusion::ppm_edge (hkm1, hk, hkp1, hkp2, Ak, Akp1, Pk, Pkp1)
Returns the PPM quasi-fourth order edge value at k+1/2 following equation 1.6 in Colella & Woodward, 1984: JCP 54, 174-201.
real function mom_neutral_diffusion::ppm_ave (xL, xR, aL, aR, aMean)
Returns the average of a PPM reconstruction between two fractional positions.
real function mom_neutral_diffusion::signum (a, x)
A true signum function that returns either -abs(a), when x<0; or abs(a) when x>0; or 0 when x=0.
subroutine mom_neutral_diffusion::plm_diff (nk, h, S, c_method, b_method, diff)
Returns PLM slopes for a column where the slopes are the difference in value across each cell. The limiting follows equation 1.8 in Colella & Woodward, 1984: JCP 54, 174-201.
real function mom_neutral_diffusion::fv_diff (hkm1, hk, hkp1, Skm1, Sk, Skp1)
Returns the cell-centered second-order finite volume (unlimited PLM) slope using three consecutive cell widths and average values. Slope is returned as a difference across the central cell (i.e. units of scalar S). Discretization follows equation 1.7 in Colella & Woodward, 1984: JCP 54, 174-201.
real function mom_neutral_diffusion::fvlsq_slope (hkm1, hk, hkp1, Skm1, Sk, Skp1)
Returns the cell-centered second-order weighted least squares slope using three consecutive cell widths and average values. Slope is returned as a gradient (i.e. units of scalar S over width units).
subroutine mom_neutral_diffusion::find_neutral_surface_positions (nk, Pl, Tl, Sl, dRdTl, dRdSl, Pr, Tr, Sr, dRdTr, dRdSr, PoL, PoR, KoL, KoR, hEff)
Returns positions within left/right columns of combined interfaces.
real function mom_neutral_diffusion::absolute_position (n, Pint, Karr, NParr, k_surface)
Converts non-dimensional position within a layer to absolute position (for debugging)
real function, dimension(2 *n+2) mom_neutral_diffusion::absolute_positions (n, Pint, Karr, NParr)
Converts non-dimensional positions within layers to absolute positions (for debugging)
real function mom_neutral_diffusion::interpolate_for_nondim_position (dRhoNeg, Pneg, dRhoPos, Ppos)
Returns the non-dimensional position between Pneg and Ppos where the interpolated density difference equals zero. The result is always bounded to be between 0 and 1.
subroutine mom_neutral_diffusion::neutral_surface_flux (nk, hl, hr, Tl, Tr, PiL, PiR, KoL, KoR, hEff, Flx)
Returns a single column of neutral diffusion fluxes of a tracer.
logical function, public mom_neutral_diffusion::neutral_diffusion_unit_tests ()
Returns true if unit tests of neutral_diffusion functions fail. Otherwise returns false.
logical function test_fv_diff (hkm1, hk, hkp1, Skm1, Sk, Skp1, Ptrue, title)
Returns true if a test of fv_diff() fails, and conditionally writes results to stream.
logical function test_fvlsq_slope (hkm1, hk, hkp1, Skm1, Sk, Skp1, Ptrue, title)
Returns true if a test of fvlsq_slope() fails, and conditionally writes results to stream.
logical function test_ifndp (rhoNeg, Pneg, rhoPos, Ppos, Ptrue, title)
Returns true if a test of interpolate_for_nondim_position() fails, and conditionally writes results to stream.
logical function test_data1d (nk, Po, Ptrue, title)
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
logical function test_data1di (nk, Po, Ptrue, title)
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
logical function test_nsp (nk, KoL, KoR, pL, pR, hEff, KoL0, KoR0, pL0, pR0, hEff0, title)
Returns true if output of find_neutral_surface_positions() does not match correct values, and conditionally writes results to stream.
logical function compare_nsp_row (KoL, KoR, pL, pR, KoL0, KoR0, pL0, pR0)
Compares a single row, k, of output from find_neutral_surface_positions()
subroutine, public mom_neutral_diffusion::neutral_diffusion_end (CS)
Deallocates neutral_diffusion control structure.
Variables
character(len=40) mom_neutral_diffusion::mod = "MOM_neutral_diffusion"
logical, parameter mom_neutral_diffusion::debug_this_module = .false.
Function/Subroutine Documentation
compare_nsp_row()
logical function neutral_diffusion_unit_tests::compare_nsp_row (integer, intent(in) KoL, integer, intent(in) KoR, real, intent(in) pL, real, intent(in) pR, integer, intent(in) KoL0, integer, intent(in) KoR0, real, intent(in) pL0, real, intent(in) pR0) private
Compares a single row, k, of output from find_neutral_surface_positions()
Parameters
[in] kol Index of first left interface above neutral surface
[in] kor Index of first right interface above neutral surface
[in] pl Fractional position of neutral surface within layer KoL of left column
[in] pr Fractional position of neutral surface within layer KoR of right column
[in] kol0 Correct value for KoL
[in] kor0 Correct value for KoR
[in] pl0 Correct value for pL
[in] pr0 Correct value for pR
Definition at line 1488 of file MOM_neutral_diffusion.F90.
     integer,  intent(in) :: KoL   !< Index of first left interface above neutral surface
     integer,  intent(in) :: KoR   !< Index of first right interface above neutral surface
     real,     intent(in) :: pL    !< Fractional position of neutral surface within layer KoL of left column
     real,     intent(in) :: pR    !< Fractional position of neutral surface within layer KoR of right column
     integer,  intent(in) :: KoL0  !< Correct value for KoL
     integer,  intent(in) :: KoR0  !< Correct value for KoR
     real,     intent(in) :: pL0   !< Correct value for pL
     real,     intent(in) :: pR0   !< Correct value for pR
     compare_nsp_row = .false.
     if (kol /= kol0) compare_nsp_row = .true.
     if (kor /= kor0) compare_nsp_row = .true.
     if (pl /= pl0) compare_nsp_row = .true.
     if (pr /= pr0) compare_nsp_row = .true.
Referenced by test_nsp().
test_data1d()
logical function neutral_diffusion_unit_tests::test_data1d (integer, intent(in) nk, real, dimension(nk), intent(in) Po, real, dimension(nk), intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
Parameters
[in] nk Number of layers
[in] po Calculated answer
[in] ptrue True answer
[in] title Title for messages
Definition at line 1372 of file MOM_neutral_diffusion.F90.
     integer,             intent(in) :: nk    !< Number of layers
     real, dimension(nk), intent(in) :: Po    !< Calculated answer
     real, dimension(nk), intent(in) :: Ptrue !< True answer
     character(len=*),    intent(in) :: title !< Title for messages
     ! Local variables
     integer :: k, stdunit
     test_data1d = .false.
     do k = 1,nk
       if (po(k) /= ptrue(k)) test_data1d = .true.
     enddo
     if (test_data1d .or. verbosity>5) then
       stdunit = 6
       if (test_data1d) stdunit = 0 ! In case of wrong results, write to error stream
       write(stdunit,'(a)') title
       do k = 1,nk
         if (po(k) /= ptrue(k)) then
           test_data1d = .true.
           write(stdunit,'(a,i2,2(x,a,f20.16),x,a,1pe22.15,x,a)') 'k=',k,'Po=',po(k),'Ptrue=',ptrue(k),'err=',po(k)-ptrue(k),'WRONG!'
         else
           if (verbosity>5) &
             write(stdunit,'(a,i2,2(x,a,f20.16),x,a,1pe22.15)') 'k=',k,'Po=',po(k),'Ptrue=',ptrue(k),'err=',po(k)-ptrue(k)
         endif
       enddo
     endif
Referenced by mom_neutral_diffusion::neutral_diffusion_unit_tests().
test_data1di()
logical function neutral_diffusion_unit_tests::test_data1di (integer, intent(in) nk, integer, dimension(nk), intent(in) Po, integer, dimension(nk), intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if comparison of Po and Ptrue fails, and conditionally writes results to stream.
Parameters
[in] nk Number of layers
[in] po Calculated answer
[in] ptrue True answer
[in] title Title for messages
Definition at line 1404 of file MOM_neutral_diffusion.F90.
     integer,                intent(in) :: nk    !< Number of layers
     integer, dimension(nk), intent(in) :: Po    !< Calculated answer
     integer, dimension(nk), intent(in) :: Ptrue !< True answer
     character(len=*),       intent(in) :: title !< Title for messages
     ! Local variables
     integer :: k, stdunit
     test_data1di = .false.
     do k = 1,nk
       if (po(k) /= ptrue(k)) test_data1di = .true.
     enddo
     if (test_data1di .or. verbosity>5) then
       stdunit = 6
       if (test_data1di) stdunit = 0 ! In case of wrong results, write to error stream
       write(stdunit,'(a)') title
       do k = 1,nk
         if (po(k) /= ptrue(k)) then
           test_data1di = .true.
           write(stdunit,'(a,i2,2(x,a,i5),x,a)') 'k=',k,'Io=',po(k),'Itrue=',ptrue(k),'WRONG!'
         else
           if (verbosity>5) &
             write(stdunit,'(a,i2,2(x,a,i5))') 'k=',k,'Io=',po(k),'Itrue=',ptrue(k)
         endif
       enddo
     endif
test_fv_diff()
logical function neutral_diffusion_unit_tests::test_fv_diff (real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) Skm1, real, intent(in) Sk, real, intent(in) Skp1, real, intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if a test of fv_diff() fails, and conditionally writes results to stream.
Parameters
[in] hkm1 Left cell width
[in] hk Center cell width
[in] hkp1 Right cell width
[in] skm1 Left cell average value
[in] sk Center cell average value
[in] skp1 Right cell average value
[in] ptrue True answer (Pa)
[in] title Title for messages
Definition at line 1281 of file MOM_neutral_diffusion.F90.
     real,             intent(in) :: hkm1  !< Left cell width
     real,             intent(in) :: hk    !< Center cell width
     real,             intent(in) :: hkp1  !< Right cell width
     real,             intent(in) :: Skm1  !< Left cell average value
     real,             intent(in) :: Sk    !< Center cell average value
     real,             intent(in) :: Skp1  !< Right cell average value
     real,             intent(in) :: Ptrue !< True answer (Pa)
     character(len=*), intent(in) :: title !< Title for messages
     ! Local variables
     integer :: stdunit
     real :: Pret
     pret = fv_diff(hkm1, hk, hkp1, skm1, sk, skp1)
     test_fv_diff = (pret /= ptrue)
     if (test_fv_diff .or. verbosity>5) then
       stdunit = 6
       if (test_fv_diff) stdunit = 0 ! In case of wrong results, write to error stream
       write(stdunit,'(a)') title
       if (test_fv_diff) then
         write(stdunit,'(2(x,a,f20.16),x,a)') 'pRet=',pret,'pTrue=',ptrue,'WRONG!'
       else
         write(stdunit,'(2(x,a,f20.16))') 'pRet=',pret,'pTrue=',ptrue
       endif
     endif
References mom_neutral_diffusion::fv_diff().
Referenced by mom_neutral_diffusion::neutral_diffusion_unit_tests().
test_fvlsq_slope()
logical function neutral_diffusion_unit_tests::test_fvlsq_slope (real, intent(in) hkm1, real, intent(in) hk, real, intent(in) hkp1, real, intent(in) Skm1, real, intent(in) Sk, real, intent(in) Skp1, real, intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if a test of fvlsq_slope() fails, and conditionally writes results to stream.
Parameters
[in] hkm1 Left cell width
[in] hk Center cell width
[in] hkp1 Right cell width
[in] skm1 Left cell average value
[in] sk Center cell average value
[in] skp1 Right cell average value
[in] ptrue True answer (Pa)
[in] title Title for messages
Definition at line 1312 of file MOM_neutral_diffusion.F90.
     real,             intent(in) :: hkm1  !< Left cell width
     real,             intent(in) :: hk    !< Center cell width
     real,             intent(in) :: hkp1  !< Right cell width
     real,             intent(in) :: Skm1  !< Left cell average value
     real,             intent(in) :: Sk    !< Center cell average value
     real,             intent(in) :: Skp1  !< Right cell average value
     real,             intent(in) :: Ptrue !< True answer (Pa)
     character(len=*), intent(in) :: title !< Title for messages
     ! Local variables
     integer :: stdunit
     real :: Pret
     pret = fvlsq_slope(hkm1, hk, hkp1, skm1, sk, skp1)
     test_fvlsq_slope = (pret /= ptrue)
     if (test_fvlsq_slope .or. verbosity>5) then
       stdunit = 6
       if (test_fvlsq_slope) stdunit = 0 ! In case of wrong results, write to error stream
       write(stdunit,'(a)') title
       if (test_fvlsq_slope) then
         write(stdunit,'(2(x,a,f20.16),x,a)') 'pRet=',pret,'pTrue=',ptrue,'WRONG!'
       else
         write(stdunit,'(2(x,a,f20.16))') 'pRet=',pret,'pTrue=',ptrue
       endif
     endif
References mom_neutral_diffusion::fvlsq_slope().
Referenced by mom_neutral_diffusion::neutral_diffusion_unit_tests().
test_ifndp()
logical function neutral_diffusion_unit_tests::test_ifndp (real, intent(in) rhoNeg, real, intent(in) Pneg, real, intent(in) rhoPos, real, intent(in) Ppos, real, intent(in) Ptrue, character(len=*), intent(in) title) private
Returns true if a test of interpolate_for_nondim_position() fails, and conditionally writes results to stream.
Parameters
[in] rhoneg Lighter density (kg/m3)
[in] pneg Interface position of lighter density (Pa)
[in] rhopos Heavier density (kg/m3)
[in] ppos Interface position of heavier density (Pa)
[in] ptrue True answer (Pa)
[in] title Title for messages
Definition at line 1343 of file MOM_neutral_diffusion.F90.
     real,             intent(in) :: rhoNeg !< Lighter density (kg/m3)
     real,             intent(in) :: Pneg   !< Interface position of lighter density (Pa)
     real,             intent(in) :: rhoPos !< Heavier density (kg/m3)
     real,             intent(in) :: Ppos   !< Interface position of heavier density (Pa)
     real,             intent(in) :: Ptrue  !< True answer (Pa)
     character(len=*), intent(in) :: title  !< Title for messages
     ! Local variables
     integer :: stdunit
     real :: Pret
     pret = interpolate_for_nondim_position(rhoneg, pneg, rhopos, ppos)
     test_ifndp = (pret /= ptrue)
     if (test_ifndp .or. verbosity>5) then
       stdunit = 6
       if (test_ifndp) stdunit = 0 ! In case of wrong results, write to error stream
       write(stdunit,'(a)') title
       if (test_ifndp) then
         write(stdunit,'(4(x,a,f20.16),2(x,a,1pe22.15),x,a)') 'r1=',rhoneg,'p1=',pneg,'r2=',rhopos,'p2=',ppos,'pRet=',pret,'pTrue=',ptrue,'WRONG!'
       else
         write(stdunit,'(4(x,a,f20.16),2(x,a,1pe22.15))') 'r1=',rhoneg,'p1=',pneg,'r2=',rhopos,'p2=',ppos,'pRet=',pret,'pTrue=',ptrue
       endif
     endif
References mom_neutral_diffusion::interpolate_for_nondim_position().
Referenced by mom_neutral_diffusion::neutral_diffusion_unit_tests().
test_nsp()
logical function neutral_diffusion_unit_tests::test_nsp (integer, intent(in) nk, integer, dimension(2*nk+2), intent(in) KoL, integer, dimension(2*nk+2), intent(in) KoR, real, dimension(2*nk+2), intent(in) pL, real, dimension(2*nk+2), intent(in) pR, real, dimension(2*nk+1), intent(in) hEff, integer, dimension(2*nk+2), intent(in) KoL0, integer, dimension(2*nk+2), intent(in) KoR0, real, dimension(2*nk+2), intent(in) pL0, real, dimension(2*nk+2), intent(in) pR0, real, dimension(2*nk+1), intent(in) hEff0, character(len=*), intent(in) title) private
Returns true if output of find_neutral_surface_positions() does not match correct values, and conditionally writes results to stream.
Parameters
[in] nk Number of layers
[in] kol Index of first left interface above neutral surface
[in] kor Index of first right interface above neutral surface
[in] pl Fractional position of neutral surface within layer KoL of left column
[in] pr Fractional position of neutral surface within layer KoR of right column
[in] heff Effective thickness between two neutral surfaces (Pa)
[in] kol0 Correct value for KoL
[in] kor0 Correct value for KoR
[in] pl0 Correct value for pL
[in] pr0 Correct value for pR
[in] heff0 Correct value for hEff
[in] title Title for messages
Definition at line 1436 of file MOM_neutral_diffusion.F90.
     integer,                    intent(in) :: nk    !< Number of layers
     integer, dimension(2*nk+2), intent(in) :: KoL   !< Index of first left interface above neutral surface
     integer, dimension(2*nk+2), intent(in) :: KoR   !< Index of first right interface above neutral surface
     real, dimension(2*nk+2),    intent(in) :: pL    !< Fractional position of neutral surface within layer KoL of left column
     real, dimension(2*nk+2),    intent(in) :: pR    !< Fractional position of neutral surface within layer KoR of right column
     real, dimension(2*nk+1),    intent(in) :: hEff  !< Effective thickness between two neutral surfaces (Pa)
     integer, dimension(2*nk+2), intent(in) :: KoL0  !< Correct value for KoL
     integer, dimension(2*nk+2), intent(in) :: KoR0  !< Correct value for KoR
     real, dimension(2*nk+2),    intent(in) :: pL0   !< Correct value for pL
     real, dimension(2*nk+2),    intent(in) :: pR0   !< Correct value for pR
     real, dimension(2*nk+1),    intent(in) :: hEff0 !< Correct value for hEff
     character(len=*),           intent(in) :: title !< Title for messages
     ! Local variables
     integer :: k, stdunit
     logical :: this_row_failed
     test_nsp = .false.
     do k = 1,2*nk+2
       test_nsp = test_nsp .or. compare_nsp_row(kol(k), kor(k), pl(k), pr(k), kol0(k), kor0(k), pl0(k), pr0(k))
       if (k < 2*nk+2) then
         if (heff(k) /= heff0(k)) test_nsp = .true.
       endif
     enddo
     if (test_nsp .or. verbosity>5) then
       stdunit = 6
       if (test_nsp) stdunit = 0 ! In case of wrong results, write to error stream
       write(stdunit,'(a)') title
       do k = 1,2*nk+2
         this_row_failed = compare_nsp_row(kol(k), kor(k), pl(k), pr(k), kol0(k), kor0(k), pl0(k), pr0(k))
         if (this_row_failed) then
           write(stdunit,10) k,kol(k),pl(k),kor(k),pr(k),' <-- WRONG!'
           write(stdunit,10) k,kol0(k),pl0(k),kor0(k),pr0(k),' <-- should be this'
         else
           write(stdunit,10) k,kol(k),pl(k),kor(k),pr(k)
         endif
         if (k < 2*nk+2) then
           if (heff(k) /= heff0(k)) then
             write(stdunit,'(i3,8x,"layer hEff =",2(f20.16,a))') k,heff(k)," .neq. ",heff0(k),' <-- WRONG!'
           else
             write(stdunit,'(i3,8x,"layer hEff =",f20.16)') k,heff(k)
           endif
         endif
       enddo
     endif
 10  format("ks=",i3," kL=",i3," pL=",f20.16," kR=",i3," pR=",f20.16,a)
References compare_nsp_row().
Referenced by mom_neutral_diffusion::neutral_diffusion_unit_tests().