MOM6: config_src/unit_drivers/MOM_sum_driver.F90 File Reference
MOM_sum_driver.F90 File Reference
#include <MOM_memory.h>
#include "version_variable.h"
Functions/Subroutines
program mom_main
subroutine benchmark_init_topog_local (D, G, param_file, max_depth)
Function/Subroutine Documentation
benchmark_init_topog_local()
subroutine mom_main::benchmark_init_topog_local (real, dimension(szi_(g),szj_(g)), intent(out) D, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Definition at line 186 of file MOM_sum_driver.F90.
   type(ocean_grid_type), intent(in)             :: G
   real, intent(out), dimension(SZI_(G),SZJ_(G)) :: D
   type(param_file_type), intent(in)             :: param_file
   real,                  intent(in)             :: max_depth
 ! Arguments: D          - the bottom depth in m. Intent out.
 !  (in)      G          - The ocean's grid structure.
 !  (in)      param_file - A structure indicating the open file to parse for
 !                         model parameter values.
 ! This subroutine sets up the benchmark test case topography
   real :: min_depth            ! The minimum and maximum depths in m.
   real :: PI                   ! 3.1415926... calculated as 4*atan(1)
   real :: D0                   ! A constant to make the maximum     !
                                ! basin depth MAXIMUM_DEPTH.         !
   real :: x, y
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mod = "benchmark_initialize_topography" ! This subroutine's name.
   integer :: i, j, is, ie, js, je, isd, ied, jsd, jed
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   call mom_mesg("  benchmark_initialization.F90, benchmark_initialize_topography: setting topography", 5)
   call log_version(param_file, mod, version)
   call get_param(param_file, mod, "MINIMUM_DEPTH", min_depth, &
                  "The minimum depth of the ocean.", units="m", default=0.0)
   pi = 4.0*atan(1.0)
   d0 = max_depth / 0.5;
 !  Calculate the depth of the bottom.
   do i=is,ie ; do j=js,je
     x=(g%geoLonT(i,j)-g%west_lon)/g%len_lon
     y=(g%geoLatT(i,j)-g%south_lat)/g%len_lat
 !  This sets topography that has a reentrant channel to the south.
     d(i,j) = -d0 * ( y*(1.0 + 0.6*cos(4.0*pi*x)) &
                    + 0.75*exp(-6.0*y) &
                    + 0.05*cos(10.0*pi*x) - 0.7 )
     if (d(i,j) > max_depth) d(i,j) = max_depth
     if (d(i,j) < min_depth) d(i,j) = 0.
   enddo ; enddo
Referenced by mom_main().
mom_main()
program mom_main ()
Definition at line 1 of file MOM_sum_driver.F90.
References benchmark_init_topog_local(), mom_file_parser::close_param_file(), mom_coms::efp_to_real(), mom_error_handler::is_root_pe(), mom_domains::mom_domains_init(), mom_error_handler::mom_error(), mom_grid::mom_grid_init(), mom_io::mom_io_init(), mom_error_handler::mom_mesg(), mom_error_handler::mom_set_verbosity(), mom_file_parser::open_param_file(), mom_coms::real_to_efp(), and mom_grid_initialize::set_grid_metrics().