MOM6: mom_error_checking Module Reference
mom_error_checking Module Reference
Data Types
interface check_redundant
Functions/Subroutines
subroutine check_redundant_v3d (mesg, u_comp, v_comp, G, is, ie, js, je, direction, stagger)
subroutine check_redundant_v2d (mesg, u_comp, v_comp, G, is, ie, js, je, direction, stagger)
subroutine check_redundant_s3d (mesg, array, G, is, ie, js, je, stagger)
subroutine check_redundant_s2d (mesg, array, G, is, ie, js, je, stagger)
real function, public totalstuff (HI, hThick, areaT, stuff)
This function returns the sum over computational domain of all processors of hThick*stuff, where stuff is a 3-d array at tracer points.
subroutine, public totaltands (HI, hThick, areaT, temperature, salinity, mesg)
This subroutine display the total thickness, temperature and salinity as well as the change since the last call. NOTE: This subroutine uses "save" data which is not thread safe and is purely for extreme debugging without a proper debugger.
Function/Subroutine Documentation
check_redundant_s2d()
subroutine mom_error_checking::check_redundant_s2d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szjb_(g)), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional stagger) private
Definition at line 188 of file MOM_error_checking.F90.
   character(len=*),                intent(in)    :: mesg
   type(ocean_grid_type),           intent(inout) :: G
   real, dimension(SZIB_(G),SZJB_(G)), intent(in) :: array
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   real :: a_nonsym(SZI_(G),SZJ_(G))
   real :: a_resym(SZIB_(G),SZJB_(G))
   character(len=128) :: mesg2
   type(group_pass_type), save :: pass_a_nonsym, pass_a_resym !For group halo pass
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: Isq, Ieq, Jsq, Jeq, isd, ied, jsd, jed, IsdB, IedB, JsdB, JedB
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if ((isd == isdb) .and. (jsd == jsdb)) return
   do i=isd,ied ; do j=jsd,jed
     a_nonsym(i,j) = array(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call create_group_pass(pass_a_nonsym, a_nonsym, a_nonsym, g%Domain_aux, &
                          direction=to_all+scalar_pair, stagger=bgrid_ne)
   call create_group_pass(pass_a_resym, a_resym, a_resym, g%Domain,     &
                          direction=to_all+scalar_pair, stagger=bgrid_ne)
   call do_group_pass(pass_a_nonsym, g%Domain_aux)
   do i=isdb,iedb ; do j=jsdb,jedb ; a_resym(i,j) = array(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     a_resym(i,j) = a_nonsym(i,j)
   enddo ; enddo
   call do_group_pass(pass_a_resym, g%Domain)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch,je_ch
     if (a_resym(i,j) /= array(i,j)) then
       write(mesg2,'(" Redundant points",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            array(i,j), a_resym(i,j),array(i,j)-a_resym(i,j),i,j,pe_here()
       write(*,'(A130)') trim(mesg)//trim(mesg2)
     endif
   enddo ; enddo
References mom_domains::do_group_pass(), and mom_error_handler::mom_error().
Referenced by check_redundant_s3d().
check_redundant_s3d()
subroutine mom_error_checking::check_redundant_s3d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szjb_(g),szk_(g)), intent(in) array, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional stagger) private
Definition at line 160 of file MOM_error_checking.F90.
   character(len=*),                     intent(in)    :: mesg
   type(ocean_grid_type),                intent(inout) :: G
   real, dimension(SZIB_(G),SZJB_(G),SZK_(G)), intent(in) :: array
   integer,                    optional, intent(in)    :: is, ie, js, je
   integer,                    optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,g%ke
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_s2d(trim(mesg)//trim(mesg_k), array(:,:,k), &
                              g, is, ie, js, je, stagger)
   enddo
References check_redundant_s2d().
check_redundant_v2d()
subroutine mom_error_checking::check_redundant_v2d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g)), intent(in) u_comp, real, dimension(szi_(g),szjb_(g)), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction, integer, intent(in), optional stagger) private
Definition at line 85 of file MOM_error_checking.F90.
   type(ocean_grid_type),           intent(inout) :: G
   character(len=*),                intent(in)    :: mesg
   real, dimension(SZIB_(G),SZJ_(G)), intent(in)  :: u_comp
   real, dimension(SZI_(G),SZJB_(G)), intent(in)  :: v_comp
   integer,               optional, intent(in)    :: is, ie, js, je
   integer,               optional, intent(in)    :: direction
   integer,               optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   real :: u_nonsym(SZI_(G),SZJ_(G))
   real :: v_nonsym(SZI_(G),SZJ_(G))
   real :: u_resym(SZIB_(G),SZJ_(G))
   real :: v_resym(SZI_(G),SZJB_(G))
   character(len=128) :: mesg2
   type(group_pass_type), save :: pass_nonsym_uv, pass_resym_uv !For group halo pass
   integer :: i, j, is_ch, ie_ch, js_ch, je_ch
   integer :: Isq, Ieq, Jsq, Jeq, isd, ied, jsd, jed, IsdB, IedB, JsdB, JedB
   isq = g%IscB ; ieq = g%IecB ; jsq = g%JscB ; jeq = g%JecB
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if ((isd == isdb) .and. (jsd == jsdb)) return
   do i=isd,ied ; do j=jsd,jed
     u_nonsym(i,j) = u_comp(i,j) ; v_nonsym(i,j) = v_comp(i,j)
   enddo ; enddo
   if (.not.associated(g%Domain_aux)) call mom_error(fatal," check_redundant"//&
     " called with a non-associated auxiliary domain the grid type.")
   call create_group_pass(pass_nonsym_uv, u_nonsym, v_nonsym, g%Domain_aux, &
                          direction, stagger)
   call create_group_pass(pass_resym_uv, u_resym, v_resym, g%Domain,  &
                          direction, stagger)
   call do_group_pass(pass_nonsym_uv, g%Domain_aux)
   do i=isdb,iedb ; do j=jsd,jed ; u_resym(i,j) = u_comp(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsdb,jedb ; v_resym(i,j) = v_comp(i,j) ; enddo ; enddo
   do i=isd,ied ; do j=jsd,jed
     u_resym(i,j) = u_nonsym(i,j) ; v_resym(i,j) = v_nonsym(i,j)
   enddo ; enddo
   call do_group_pass(pass_resym_uv, g%Domain)
   is_ch = isq ; ie_ch = ieq ; js_ch = jsq ; je_ch = jeq
   if (present(is)) is_ch = is ; if (present(ie)) ie_ch = ie
   if (present(js)) js_ch = js ; if (present(js)) je_ch = je
   do i=is_ch,ie_ch ; do j=js_ch+1,je_ch
     if (u_resym(i,j) /= u_comp(i,j)) then
       write(mesg2,'(" redundant u-components",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," on pe ",i4)') &
            u_comp(i,j), u_resym(i,j),u_comp(i,j)-u_resym(i,j),i,j,pe_here()
       write(*,'(A130)') trim(mesg)//trim(mesg2)
     endif
   enddo ; enddo
   do i=is_ch+1,ie_ch ; do j=js_ch,je_ch
     if (v_resym(i,j) /= v_comp(i,j)) then
       write(mesg2,'(" redundant v-comps",2(1pe12.4)," differ by ", &
                     & 1pe12.4," at i,j = ",2i4," x,y = ",2(1pe12.4)" on pe ",i4)') &
            v_comp(i,j), v_resym(i,j),v_comp(i,j)-v_resym(i,j),i,j, &
            g%geoLonBu(i,j), g%geoLatBu(i,j), pe_here()
       write(*,'(A155)') trim(mesg)//trim(mesg2)
     endif
   enddo ; enddo
References mom_domains::do_group_pass(), and mom_error_handler::mom_error().
Referenced by check_redundant_v3d().
check_redundant_v3d()
subroutine mom_error_checking::check_redundant_v3d (character(len=*), intent(in) mesg, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) u_comp, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) v_comp, type(ocean_grid_type), intent(inout) G, integer, intent(in), optional is, integer, intent(in), optional ie, integer, intent(in), optional js, integer, intent(in), optional je, integer, intent(in), optional direction, integer, intent(in), optional stagger) private
Definition at line 54 of file MOM_error_checking.F90.
   type(ocean_grid_type),               intent(inout) :: G
   character(len=*),                    intent(in)    :: mesg
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(in) :: u_comp
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(in) :: v_comp
   integer,                   optional, intent(in)    :: is, ie, js, je
   integer,                   optional, intent(in)    :: direction
   integer,                   optional, intent(in)    :: stagger
 ! Arguments: u_comp - The u-component of the vector being checked.
 !  (in)      v_comp - The v-component of the vector being checked.
 !  (in)      mesg - A message indicating what is being checked.
 !  (in)      G - The ocean's grid structure.
 !  (in/opt)  is, ie, js, je - the i- and j- range of indices to check.
 !  (in/opt)  direction - the direction flag to be passed to pass_vector.
 !  (in/opt)  stagger - the stagger flag to be passed to pass_vector.
   character(len=24) :: mesg_k
   integer :: k
   do k=1,g%ke
     if (k < 10) then ; write(mesg_k,'(" Layer",i2," ")') k
     elseif (k < 100) then ; write(mesg_k,'(" Layer",i3," ")') k
     elseif (k < 1000) then ; write(mesg_k,'(" Layer",i4," ")') k
     else ; write(mesg_k,'(" Layer",i9," ")') k ; endif
     call check_redundant_v2d(trim(mesg)//trim(mesg_k), u_comp(:,:,k), &
              v_comp(:,:,k), g, is, ie, js, je, direction, stagger)
   enddo
References check_redundant_v2d().
totalstuff()
real function, public mom_error_checking::totalstuff (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:,:), intent(in) hThick, real, dimension(hi%isd:,hi%jsd:), intent(in) areaT, real, dimension(hi%isd:,hi%jsd:,:), intent(in) stuff)
This function returns the sum over computational domain of all processors of hThick*stuff, where stuff is a 3-d array at tracer points.
Parameters
[in] hi A horizontal index type
[in] hthick The array of thicknesses to use as weights
[in] areat The array of cell areas in m2
[in] stuff The array of stuff to be summed
Definition at line 251 of file MOM_error_checking.F90.
   type(hor_index_type),               intent(in) :: HI     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: hThick !< The array of thicknesses to use as weights
   real, dimension(HI%isd:,HI%jsd:),   intent(in) :: areaT  !< The array of cell areas in m2
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: stuff  !< The array of stuff to be summed
   real                                         :: totalStuff
   integer :: i, j, k, nz
   nz = size(hthick,3)
   totalstuff = 0.
   do k = 1, nz ; do j = hi%jsc, hi%jec ; do i = hi%isc, hi%iec
     totalstuff = totalstuff + hthick(i,j,k) * stuff(i,j,k) * areat(i,j)
   enddo ; enddo ; enddo
   call sum_across_pes(totalstuff)
Referenced by totaltands().
totaltands()
subroutine, public mom_error_checking::totaltands (type(hor_index_type), intent(in) HI, real, dimension(hi%isd:,hi%jsd:,:), intent(in) hThick, real, dimension(hi%isd:,hi%jsd:), intent(in) areaT, real, dimension(hi%isd:,hi%jsd:,:), intent(in) temperature, real, dimension(hi%isd:,hi%jsd:,:), intent(in) salinity, character(len=*), intent(in) mesg)
This subroutine display the total thickness, temperature and salinity as well as the change since the last call. NOTE: This subroutine uses "save" data which is not thread safe and is purely for extreme debugging without a proper debugger.
Parameters
[in] hi A horizontal index type
[in] hthick The array of thicknesses to use as weights
[in] areat The array of cell areas in m2
[in] temperature The temperature field to sum
[in] salinity The salinity field to sum
[in] mesg An identifying message
Definition at line 274 of file MOM_error_checking.F90.
   type(hor_index_type),               intent(in) :: HI     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: hThick !< The array of thicknesses to use as weights
   real, dimension(HI%isd:,HI%jsd:),   intent(in) :: areaT  !< The array of cell areas in m2
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: temperature !< The temperature field to sum
   real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: salinity    !< The salinity field to sum
   character(len=*),                   intent(in) :: mesg        !< An identifying message
   ! NOTE: This subroutine uses "save" data which is not thread safe and is purely for
   ! extreme debugging without a proper debugger.
   real, save :: totalH = 0., totalt = 0., totals = 0.
   logical, save :: firstCall = .true.
   real :: thisH, thisT, thisS, delH, delT, delS
   integer :: i, j, k, nz
   nz = size(hthick,3)
   thish = 0.
   do k = 1, nz ; do j = hi%jsc, hi%jec ; do i = hi%isc, hi%iec
     thish = thish + hthick(i,j,k) * areat(i,j)
   enddo ; enddo ; enddo
   call sum_across_pes(thish)
   thist = totalstuff(hi, hthick, areat, temperature)
   thiss = totalstuff(hi, hthick, areat, salinity)
   if (is_root_pe()) then
     if (firstcall) then
       totalh = thish ; totalt = thist ; totals = thiss
       write(0,*) 'Totals H,T,S:',thish,thist,thiss,' ',mesg
       firstcall = .false.
     else
       delh = thish - totalh
       delt = thist - totalt
       dels = thiss - totals
       totalh = thish ; totalt = thist ; totals = thiss
       write(0,*) 'Tot/del H,T,S:',thish,thist,thiss,delh,delt,dels,' ',mesg
     endif
   endif
References mom_error_handler::is_root_pe(), and totalstuff().