MOM6: mom_checksums Module Reference
mom_checksums Module Reference
Data Types
interface bchksum
interface chk_sum_msg
interface chksum
interface hchksum
interface is_nan
interface qchksum
interface uchksum
interface vchksum
Functions/Subroutines
subroutine chksum_h_2d (array, mesg, HI, haloshift)
chksum_h_2d performs checksums on a 2d array staggered at tracer points.
subroutine chksum_b_2d (array, mesg, HI, haloshift, symmetric)
chksum_B_2d performs checksums on a 2d array staggered at corner points.
subroutine chksum_u_2d (array, mesg, HI, haloshift)
chksum_u_2d performs checksums on a 2d array staggered at C-grid u points.
subroutine chksum_v_2d (array, mesg, HI, haloshift)
chksum_v_2d performs checksums on a 2d array staggered at C-grid v points.
subroutine chksum_h_3d (array, mesg, HI, haloshift)
chksum_h_3d performs checksums on a 3d array staggered at tracer points.
subroutine chksum_b_3d (array, mesg, HI, haloshift)
chksum_B_3d performs checksums on a 3d array staggered at corner points.
subroutine chksum_u_3d (array, mesg, HI, haloshift)
chksum_u_3d performs checksums on a 3d array staggered at C-grid u points.
subroutine chksum_v_3d (array, mesg, HI, haloshift)
chksum_v_3d performs checksums on a 3d array staggered at C-grid v points.
subroutine chksum1d (array, mesg, start_i, end_i, compare_PEs)
chksum1d does a checksum of a 1-dimensional array.
subroutine chksum2d (array, mesg, start_x, end_x, start_y, end_y)
subroutine chksum3d (array, mesg, start_x, end_x, start_y, end_y, start_z, end_z)
logical function is_nan_0d (x)
This function returns .true. if x is a NaN, and .false. otherwise.
logical function is_nan_1d (x, skip_mpp)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
logical function is_nan_2d (x)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
logical function is_nan_3d (x)
This function returns .true. if any element of x is a NaN, and .false. otherwise.
subroutine chk_sum_msg1 (fmsg, bc0, mesg)
subroutine chk_sum_msg5 (fmsg, bc0, bcSW, bcSE, bcNW, bcNE, mesg)
subroutine chk_sum_msg2 (fmsg, bc0, bcSW, mesg)
subroutine chk_sum_msg3 (fmsg, aMean, aMin, aMax, mesg)
subroutine, public mom_checksums_init (param_file)
MOM_checksums_init initializes the MOM_checksums module. As it happens, the only thing that it does is to log the version of this module.
subroutine chksum_error (signal, message)
Variables
integer, parameter default_shift =0
logical calculatestatistics =.true.
logical writechksums =.true.
logical checkfornans =.true.
Function/Subroutine Documentation
chk_sum_msg1()
subroutine mom_checksums::chk_sum_msg1 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, character(len=*), intent(in) mesg) private
Definition at line 1020 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0
   if (is_root_pe()) write(0,'(A,1(A,I10,X),A)') fmsg," c=",bc0,trim(mesg)
References mom_error_handler::is_root_pe().
chk_sum_msg2()
subroutine mom_checksums::chk_sum_msg2 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcSW, character(len=*), intent(in) mesg) private
Definition at line 1037 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0,bcSW
   if (is_root_pe()) write(0,'(A,2(A,I9,1X),A)') &
      fmsg," c=",bc0,"s/w=",bcsw,trim(mesg)
References mom_error_handler::is_root_pe().
chk_sum_msg3()
subroutine mom_checksums::chk_sum_msg3 (character(len=*), intent(in) fmsg, real, intent(in) aMean, real, intent(in) aMin, real, intent(in) aMax, character(len=*), intent(in) mesg) private
Definition at line 1046 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   real,             intent(in) :: aMean,aMin,aMax
   if (is_root_pe()) write(0,'(A,3(A,ES25.16,1X),A)') &
      fmsg," mean=",amean,"min=",amin,"max=",amax,trim(mesg)
References mom_error_handler::is_root_pe().
chk_sum_msg5()
subroutine mom_checksums::chk_sum_msg5 (character(len=*), intent(in) fmsg, integer, intent(in) bc0, integer, intent(in) bcSW, integer, intent(in) bcSE, integer, intent(in) bcNW, integer, intent(in) bcNE, character(len=*), intent(in) mesg) private
Definition at line 1028 of file MOM_checksums.F90.
   character(len=*), intent(in) :: fmsg, mesg
   integer,          intent(in) :: bc0,bcSW,bcSE,bcNW,bcNE
   if (is_root_pe()) write(0,'(A,5(A,I10,1X),A)') &
      fmsg," c=",bc0,"sw=",bcsw,"se=",bcse,"nw=",bcnw,"ne=",bcne,trim(mesg)
References mom_error_handler::is_root_pe().
chksum1d()
subroutine mom_checksums::chksum1d (real, dimension(:), intent(in) array, character(len=*), intent(in) mesg, integer, intent(in), optional start_i, integer, intent(in), optional end_i, logical, intent(in), optional compare_PEs) private
chksum1d does a checksum of a 1-dimensional array.
Parameters
[in] array The array to be summed (index starts at 1).
[in] mesg An identifying message.
[in] start_i The starting index for the sum (default 1)
[in] end_i The ending index for the sum (default all)
[in] compare_pes If true, compare across PEs instead of summing and list the root_PE value (default true)
Definition at line 808 of file MOM_checksums.F90.
   real, dimension(:), intent(in) :: array   !< The array to be summed (index starts at 1).
   character(len=*),   intent(in) :: mesg    !< An identifying message.
   integer, optional,  intent(in) :: start_i !< The starting index for the sum (default 1)
   integer, optional,  intent(in) :: end_i   !< The ending index for the sum (default all)
   logical, optional,  intent(in) :: compare_PEs !< If true, compare across PEs instead of summing
                                                 !! and list the root_PE value (default true)
   integer :: is, ie, i, bc, sum1, sum_bc
   integer :: bitcount
   real :: sum
   real, allocatable :: sum_here(:)
   logical :: compare
   integer :: pe_num   ! pe number of the data
   integer :: nPEs     ! Total number of processsors
   is = lbound(array,1) ; ie = ubound(array,1)
   if (present(start_i)) is = start_i
   if (present(end_i)) ie = end_i
   compare = .true. ; if (present(compare_pes)) compare = compare_pes
   sum = 0.0 ; sum_bc = 0
   do i=is,ie
     sum = sum + array(i)
     bc = bitcount(abs(array(i)))
     sum_bc = sum_bc + bc
   enddo
   pe_num = pe_here() + 1 - root_pe() ; npes = num_pes()
   allocate(sum_here(npes)) ; sum_here(:) = 0.0 ; sum_here(pe_num) = sum
   call sum_across_pes(sum_here,npes)
   sum1 = sum_bc
   call sum_across_pes(sum1)
   if (.not.compare) then
     sum = 0.0
     do i=1,npes ; sum = sum + sum_here(i) ; enddo
     sum_bc = sum1
   elseif (is_root_pe()) then
     if (sum1 /= npes*sum_bc) &
       write(0, '(A40," bitcounts do not match across PEs: ",I12,1X,I12)') &
             mesg, sum1, npes*sum_bc
     do i=1,npes ; if (sum /= sum_here(i)) then
       write(0, '(A40," PE ",i4," sum mismatches root_PE: ",3(ES22.13,1X))') &
             mesg, i, sum_here(i), sum, sum_here(i)-sum
     endif ; enddo
   endif
   deallocate(sum_here)
   if (is_root_pe()) &
     write(0,'(A50,1X,ES25.16,1X,I12)') mesg, sum, sum_bc
References mom_error_handler::is_root_pe().
chksum2d()
subroutine mom_checksums::chksum2d (real, dimension(:,:) array, character(len=*) mesg, integer, optional start_x, integer, optional end_x, integer, optional start_y, integer, optional end_y) private
Definition at line 867 of file MOM_checksums.F90.
   real, dimension(:,:) :: array
   character(len=*) :: mesg
   integer, optional :: start_x, end_x, start_y, end_y
   integer :: bitcount
   integer :: xs,xe,ys,ye,i,j,sum1,bc
   real :: sum
   xs = lbound(array,1) ; xe = ubound(array,1)
   ys = lbound(array,2) ; ye = ubound(array,2)
   if (present(start_x)) xs = start_x
   if (present(end_x  )) xe = end_x
   if (present(start_y)) ys = start_y
   if (present(end_y  )) ye = end_y
   sum = 0.0 ; sum1 = 0
   do i=xs,xe ; do j=ys,ye
     bc = bitcount(abs(array(i,j)))
     sum1 = sum1 + bc
   enddo ; enddo
   call sum_across_pes(sum1)
   sum = reproducing_sum(array(xs:xe,ys:ye))
   if (is_root_pe()) &
     write(0,'(A50,1X,ES25.16,1X,I12)') mesg, sum, sum1
 !    write(0,'(A40,1X,Z16.16,1X,Z16.16,1X,ES25.16,1X,I12)') &
 !      mesg, sum, sum1, sum, sum1
References mom_error_handler::is_root_pe().
chksum3d()
subroutine mom_checksums::chksum3d (real, dimension(:,:,:) array, character(len=*) mesg, integer, optional start_x, integer, optional end_x, integer, optional start_y, integer, optional end_y, integer, optional start_z, integer, optional end_z) private
Definition at line 900 of file MOM_checksums.F90.
   real, dimension(:,:,:) :: array
   character(len=*) :: mesg
   integer, optional :: start_x, end_x, start_y, end_y, start_z, end_z
   integer :: bitcount
   integer :: xs,xe,ys,ye,zs,ze,i,j,k, bc,sum1
   real :: sum
   xs = lbound(array,1) ; xe = ubound(array,1)
   ys = lbound(array,2) ; ye = ubound(array,2)
   zs = lbound(array,3) ; ze = ubound(array,3)
   if (present(start_x)) xs = start_x
   if (present(end_x  )) xe = end_x
   if (present(start_y)) ys = start_y
   if (present(end_y  )) ye = end_y
   if (present(start_z)) zs = start_z
   if (present(end_z  )) ze = end_z
   sum = 0.0 ; sum1 = 0
   do i=xs,xe ; do j=ys,ye ; do k=zs,ze
     bc = bitcount(abs(array(i,j,k)))
     sum1 = sum1 + bc
   enddo ; enddo ; enddo
   call sum_across_pes(sum1)
   sum = reproducing_sum(array(xs:xe,ys:ye,zs:ze))
   if (is_root_pe()) &
     write(0,'(A50,1X,ES25.16,1X,I12)') mesg, sum, sum1
 !    write(0,'(A40,1X,Z16.16,1X,Z16.16,1X,ES25.16,1X,I12)') &
 !      mesg, sum, sum1, sum, sum1
References mom_error_handler::is_root_pe().
chksum_b_2d()
subroutine mom_checksums::chksum_b_2d (real, dimension(hi%isdb:,hi%jsdb:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift, logical, intent(in), optional symmetric) private
chksum_B_2d performs checksums on a 2d array staggered at corner points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
[in] symmetric If true, do the checksums on the full symmetric computational domain.
Definition at line 169 of file MOM_checksums.F90.
   type(hor_index_type), intent(in) :: HI     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%JsdB:), &
                         intent(in) :: array !< The array to be checksummed
   character(len=*),     intent(in) :: mesg  !< An identifying message
   integer,    optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   logical,    optional, intent(in) :: symmetric !< If true, do the checksums on the
                                                 !! full symmetric computational domain.
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   logical :: sym
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%JscB:hi%JecB))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_B_2d: haloshift =',hshift
     write(0,*) 'chksum_B_2d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_B_2d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_B_2d '//trim(mesg))
   endif
   sym = .false. ; if (present(symmetric)) sym = symmetric
   bc0=subchk(array, hi, 0, 0)
   if ((hshift==0) .and. .not.sym) then
     if (is_root_pe()) call chk_sum_msg("B-point:",bc0,mesg)
     return
   endif
   if (sym) then
     bcsw=subchk(array, hi, -hshift-1, -hshift-1)
     bcse=subchk(array, hi, hshift, -hshift-1)
     bcnw=subchk(array, hi, -hshift-1, hshift)
   else
     bcsw=subchk(array, hi, -hshift, -hshift)
     bcse=subchk(array, hi, hshift, -hshift)
     bcnw=subchk(array, hi, -hshift, hshift)
   endif
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("B-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%JsdB:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: aMean, aMin, aMax
     amean = 0.
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
       n = n + 1
     enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("B-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_b_3d()
subroutine mom_checksums::chksum_b_3d (real, dimension(hi%isdb:,hi%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_B_3d performs checksums on a 3d array staggered at corner points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 537 of file MOM_checksums.F90.
   type(hor_index_type),              intent(in) :: HI !< A horizontal index type
   real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
   character(len=*),                   intent(in) :: mesg  !< An identifying message
   integer,                  optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%JscB:hi%JecB,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_B_3d: haloshift =',hshift
     write(0,*) 'chksum_B_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_B_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_B_3d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
     if (is_root_pe()) call chk_sum_msg("B-point:",bc0,mesg)
     return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("B-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%JsdB:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("B-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_error()
subroutine mom_checksums::chksum_error (integer, intent(in) signal, character(len=*), intent(in) message) private
Definition at line 1069 of file MOM_checksums.F90.
   ! Wrapper for MOM_error to help place specific break points in
   ! debuggers
   integer, intent(in) :: signal
   character(len=*), intent(in) :: message
   call mom_error(signal, message)
References mom_error_handler::mom_error().
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
chksum_h_2d()
subroutine mom_checksums::chksum_h_2d (real, dimension(hi%isd:,hi%jsd:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_h_2d performs checksums on a 2d array staggered at tracer points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 80 of file MOM_checksums.F90.
   type(hor_index_type),           intent(in) :: HI     !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:), intent(in) :: array !< The array to be checksummed
   character(len=*),                intent(in) :: mesg  !< An identifying message
   integer,               optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%jsc:hi%jec))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_h_2d: haloshift =',hshift
     write(0,*) 'chksum_h_2d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_h_2d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_h_2d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
       if (is_root_pe()) call chk_sum_msg("h-point:",bc0,mesg)
       return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("h-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%jsd:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
       n = n + 1
     enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("h-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_h_3d()
subroutine mom_checksums::chksum_h_3d (real, dimension(hi%isd:,hi%jsd:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_h_3d performs checksums on a 3d array staggered at tracer points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 448 of file MOM_checksums.F90.
   type(hor_index_type),             intent(in) :: HI !< A horizontal index type
   real, dimension(HI%isd:,HI%jsd:,:),  intent(in) :: array !< The array to be checksummed
   character(len=*),                  intent(in) :: mesg  !< An identifying message
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_h_3d: haloshift =',hshift
     write(0,*) 'chksum_h_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_h_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_h_3d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
       if (is_root_pe()) call chk_sum_msg("h-point:",bc0,mesg)
       return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("h-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%jsd:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("h-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_u_2d()
subroutine mom_checksums::chksum_u_2d (real, dimension(hi%isdb:,hi%jsd:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_u_2d performs checksums on a 2d array staggered at C-grid u points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 270 of file MOM_checksums.F90.
   type(hor_index_type),           intent(in) :: HI     !< A horizontal index type
   real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array !< The array to be checksummed
   character(len=*),                intent(in) :: mesg  !< An identifying message
   integer,               optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%jsc:hi%jec))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_u_2d: haloshift =',hshift
     write(0,*) 'chksum_u_2d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_u_2d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_u_2d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
       if (is_root_pe()) call chk_sum_msg("u-point:",bc0,mesg)
       return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("u-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%jsd:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
       n = n + 1
     enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("u-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_u_3d()
subroutine mom_checksums::chksum_u_3d (real, dimension(hi%isdb:,hi%jsd:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_u_3d performs checksums on a 3d array staggered at C-grid u points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 626 of file MOM_checksums.F90.
   type(hor_index_type),             intent(in) :: HI !< A horizontal index type
   real, dimension(HI%isdB:,HI%Jsd:,:), intent(in) :: array !< The array to be checksummed
   character(len=*),                  intent(in) :: mesg  !< An identifying message
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%IscB:hi%IecB,hi%jsc:hi%jec,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_u_3d: haloshift =',hshift
     write(0,*) 'chksum_u_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_u_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_u_3d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
     if (is_root_pe()) call chk_sum_msg("u-point:",bc0,mesg)
     return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("u-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%IsdB:,HI%jsd:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("u-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_v_2d()
subroutine mom_checksums::chksum_v_2d (real, dimension(hi%isd:,hi%jsdb:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_v_2d performs checksums on a 2d array staggered at C-grid v points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 359 of file MOM_checksums.F90.
   type(hor_index_type),           intent(in) :: HI     !< A horizontal index type
   real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array !< The array to be checksummed
   character(len=*),                intent(in) :: mesg  !< An identifying message
   integer,               optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%JscB:hi%JecB))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_v_2d: haloshift =',hshift
     write(0,*) 'chksum_v_2d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_v_2d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_v_2d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
       if (is_root_pe()) call chk_sum_msg("v-point:",bc0,mesg)
       return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("v-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, bc
     subchk = 0
     do j=hi%jsc+dj,hi%jec+dj; do i=hi%isc+di,hi%iec+di
         bc = bitcount(abs(array(i,j)))
         subchk = subchk + bc
     enddo; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%JsdB:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc)
     amax = array(hi%isc,hi%jsc)
     n = 0
     do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j))
       amax = max(amax, array(i,j))
       n = n + 1
     enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("v-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
chksum_v_3d()
subroutine mom_checksums::chksum_v_3d (real, dimension(hi%isd:,hi%jsdb:,:), intent(in) array, character(len=*), intent(in) mesg, type(hor_index_type), intent(in) HI, integer, intent(in), optional haloshift) private
chksum_v_3d performs checksums on a 3d array staggered at C-grid v points.
Parameters
[in] hi A horizontal index type
[in] array The array to be checksummed
[in] mesg An identifying message
[in] haloshift The width of halos to check (default 0)
Definition at line 715 of file MOM_checksums.F90.
   type(hor_index_type),             intent(in) :: HI !< A horizontal index type
   real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array !< The array to be checksummed
   character(len=*),                  intent(in) :: mesg  !< An identifying message
   integer,                 optional, intent(in) :: haloshift !< The width of halos to check (default 0)
   integer :: bc0,bcSW,bcSE,bcNW,bcNE,hshift
   if (checkfornans) then
     if (is_nan(array(hi%isc:hi%iec,hi%JscB:hi%JecB,:))) &
       call chksum_error(fatal, 'NaN detected: '//trim(mesg))
 !   if (is_NaN(array)) &
 !     call chksum_error(FATAL, 'NaN detected in halo: '//trim(mesg))
   endif
   if (calculatestatistics) call substats(hi, array, mesg)
   if (.not.writechksums) return
   hshift=default_shift
   if (present(haloshift)) hshift=haloshift
   if (hshift<0) hshift=hi%ied-hi%iec
   if ( hi%isc-hshift<hi%isd .or. hi%iec+hshift>hi%ied .or. &
        hi%jsc-hshift<hi%jsd .or. hi%jec+hshift>hi%jed ) then
     write(0,*) 'chksum_v_3d: haloshift =',hshift
     write(0,*) 'chksum_v_3d: isd,isc,iec,ied=',hi%isd,hi%isc,hi%iec,hi%ied
     write(0,*) 'chksum_v_3d: jsd,jsc,jec,jed=',hi%jsd,hi%jsc,hi%jec,hi%jed
     call chksum_error(fatal,'Error in chksum_v_3d '//trim(mesg))
   endif
   bc0=subchk(array, hi, 0, 0)
   if (hshift==0) then
     if (is_root_pe()) call chk_sum_msg("v-point:",bc0,mesg)
     return
   endif
   bcsw=subchk(array, hi, -hshift, -hshift)
   bcse=subchk(array, hi, hshift, -hshift)
   bcnw=subchk(array, hi, -hshift, hshift)
   bcne=subchk(array, hi, hshift, hshift)
   if (is_root_pe()) call chk_sum_msg("v-point:",bc0,bcsw,bcse,bcnw,bcne,mesg)
   contains
   integer function subchk(array, HI, di, dj)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array
     integer, intent(in) :: di, dj
     integer :: bitcount, i, j, k, bc
     subchk = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc+dj,hi%jec+dj ; do i=hi%isc+di,hi%iec+di
       bc = bitcount(abs(array(i,j,k)))
       subchk = subchk + bc
     enddo ; enddo ; enddo
     call sum_across_pes(subchk)
     subchk=mod(subchk,1000000000)
   end function subchk
   subroutine substats(HI, array, mesg)
     type(hor_index_type), intent(in) :: HI
     real, dimension(HI%isd:,HI%JsdB:,:), intent(in) :: array
     character(len=*), intent(in) :: mesg
     integer :: i, j, k, n
     real :: aMean, aMin, aMax
     amin = array(hi%isc,hi%jsc,1)
     amax = array(hi%isc,hi%jsc,1)
     n = 0
     do k=lbound(array,3),ubound(array,3) ; do j=hi%jsc,hi%jec ; do i=hi%isc,hi%iec
       amin = min(amin, array(i,j,k))
       amax = max(amax, array(i,j,k))
       n = n + 1
     enddo ; enddo ; enddo
     amean = reproducing_sum(array(hi%isc:hi%iec,hi%jsc:hi%jec,:))
     call sum_across_pes(n)
     call min_across_pes(amin)
     call max_across_pes(amax)
     amean = amean / real(n)
     if (is_root_pe()) call chk_sum_msg("v-point:",amean,amin,amax,mesg)
   end subroutine substats
References calculatestatistics, checkfornans, chksum_error(), default_shift, mom_error_handler::is_root_pe(), subchk(), substats(), and writechksums.
is_nan_0d()
logical function mom_checksums::is_nan_0d (real, intent(in) x) private
This function returns .true. if x is a NaN, and .false. otherwise.
Parameters
[in] x The value to be checked for NaNs.
Definition at line 939 of file MOM_checksums.F90.
   real, intent(in) :: x !< The value to be checked for NaNs.
   logical :: is_NaN_0d
  !is_NaN_0d = (((x < 0.0) .and. (x >= 0.0)) .or. &
  !          (.not.(x < 0.0) .and. .not.(x >= 0.0)))
   if (((x < 0.0) .and. (x >= 0.0)) .or. &
             (.not.(x < 0.0) .and. .not.(x >= 0.0))) then
     is_nan_0d = .true.
   else
     is_nan_0d = .false.
   endif
Referenced by is_nan_1d(), is_nan_2d(), and is_nan_3d().
is_nan_1d()
logical function mom_checksums::is_nan_1d (real, dimension(:), intent(in) x, logical, optional skip_mpp) private
This function returns .true. if any element of x is a NaN, and .false. otherwise.
Parameters
[in] x The array to be checked for NaNs.
skip_mpp If true, only check this array only on the local PE (default false).
Definition at line 957 of file MOM_checksums.F90.
   real, dimension(:), intent(in) :: x !< The array to be checked for NaNs.
   logical :: is_NaN_1d
   logical, optional :: skip_mpp  !< If true, only check this array only on the local PE (default false).
   integer :: i, n
   logical :: call_mpp
   n = 0
   do i = lbound(x,1), ubound(x,1)
     if (is_nan_0d(x(i))) n = n + 1
   enddo
   call_mpp = .true.
   if (present(skip_mpp)) call_mpp = .not.skip_mpp
   if (call_mpp) call sum_across_pes(n)
   is_nan_1d = .false.
   if (n>0) is_nan_1d = .true.
References is_nan_0d().
is_nan_2d()
logical function mom_checksums::is_nan_2d (real, dimension(:,:), intent(in) x) private
This function returns .true. if any element of x is a NaN, and .false. otherwise.
Parameters
[in] x The array to be checked for NaNs.
Definition at line 981 of file MOM_checksums.F90.
   real, dimension(:,:), intent(in) :: x !< The array to be checked for NaNs.
   logical :: is_NaN_2d
   integer :: i, j, n
   n = 0
   do j = lbound(x,2), ubound(x,2) ; do i = lbound(x,1), ubound(x,1)
     if (is_nan_0d(x(i,j))) n = n + 1
   enddo ; enddo
   call sum_across_pes(n)
   is_nan_2d = .false.
   if (n>0) is_nan_2d = .true.
References is_nan_0d().
is_nan_3d()
logical function mom_checksums::is_nan_3d (real, dimension(:,:,:), intent(in) x) private
This function returns .true. if any element of x is a NaN, and .false. otherwise.
Parameters
[in] x The array to be checked for NaNs.
Definition at line 1000 of file MOM_checksums.F90.
   real, dimension(:,:,:), intent(in) :: x !< The array to be checked for NaNs.
   logical :: is_NaN_3d
   integer :: i, j, k, n
   n = 0
   do k = lbound(x,3), ubound(x,3)
     do j = lbound(x,2), ubound(x,2) ; do i = lbound(x,1), ubound(x,1)
       if (is_nan_0d(x(i,j,k))) n = n + 1
     enddo ; enddo
   enddo
   call sum_across_pes(n)
   is_nan_3d = .false.
   if (n>0) is_nan_3d = .true.
References is_nan_0d().
mom_checksums_init()
subroutine, public mom_checksums::mom_checksums_init (type(param_file_type), intent(in) param_file)
MOM_checksums_init initializes the MOM_checksums module. As it happens, the only thing that it does is to log the version of this module.
Definition at line 1057 of file MOM_checksums.F90.
   type(param_file_type),   intent(in)    :: param_file
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mod = "MOM_checksums" ! This module's name.
   call log_version(param_file, mod, version)
Referenced by mom::initialize_mom().
Variable Documentation
calculatestatistics
logical mom_checksums::calculatestatistics =.true. private
Definition at line 69 of file MOM_checksums.F90.
 logical :: calculateStatistics=.true. ! If true, report min, max and mean.
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
checkfornans
logical mom_checksums::checkfornans =.true. private
Definition at line 71 of file MOM_checksums.F90.
 logical :: checkForNaNs=.true. ! If true, checks array for NaNs and cause
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
default_shift
integer, parameter mom_checksums::default_shift =0 private
Definition at line 68 of file MOM_checksums.F90.
 integer, parameter :: default_shift=0
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().
writechksums
logical mom_checksums::writechksums =.true. private
Definition at line 70 of file MOM_checksums.F90.
 logical :: writeChksums=.true. ! If true, report the bitcount checksum
Referenced by chksum_b_2d(), chksum_b_3d(), chksum_h_2d(), chksum_h_3d(), chksum_u_2d(), chksum_u_3d(), chksum_v_2d(), and chksum_v_3d().