MOM6: rossby_front_2d_initialization Module Reference
rossby_front_2d_initialization Module Reference
Initial conditions for the 2D Rossby front test.
Functions/Subroutines
subroutine, public rossby_front_initialize_thickness (h, G, GV, param_file)
Initialization of thicknesses in 2D Rossby front test.
subroutine, public rossby_front_initialize_temperature_salinity (T, S, h, G, param_file, eqn_of_state)
Initialization of temperature and salinity in the Rossby front test.
subroutine, public rossby_front_initialize_velocity (u, v, h, G, GV, param_file)
Initialization of u and v in the Rossby front test.
real function ypseudo (G, lat)
Pseudo coordinate across domain used by Hml() and dTdy() returns a coordinate from -PI/2 .. PI/2 squashed towards the center of the domain.
real function hml (G, lat)
Analytic prescription of mixed layer depth in 2d Rossby front test.
real function dtdy (G, dT, lat)
Analytic prescription of mixed layer temperature gradient in 2d Rossby front test.
Variables
character(len=40) mod = "Rossby_front_2d_initialization"
This module's name.
real, parameter frontfractionalwidth = 0.5
Width of front as fraction of domain.
real, parameter hmlmin = 0.25
Shallowest ML as fractional depth of ocean.
real, parameter hmlmax = 0.75
Deepest ML as fractional depth of ocean.
Detailed Description
Initial conditions for the 2D Rossby front test.
Function/Subroutine Documentation
dtdy()
real function rossby_front_2d_initialization::dtdy (type(ocean_grid_type), intent(in) G, real, intent(in) dT, real, intent(in) lat) private
Analytic prescription of mixed layer temperature gradient in 2d Rossby front test.
Parameters
[in] g Grid structure
[in] dt Top to bottom temperature difference
[in] lat Latitude
Definition at line 214 of file Rossby_front_2d_initialization.F90.
   type(ocean_grid_type), intent(in) :: G     !< Grid structure
   real,                  intent(in) :: dT    !< Top to bottom temperature difference
   real,                  intent(in) :: lat   !< Latitude
   ! Local
   real :: PI, dHML, dHdy
   real :: km = 1.e3 ! AXIS_UNITS = 'k' (1000 m)
   pi = 4.0 * atan(1.0)
   dhml = 0.5 * ( hmlmax - hmlmin ) * g%max_depth
   dhdy = dhml * ( pi / ( frontfractionalwidth * g%len_lat * km ) ) * cos( ypseudo(g, lat) )
   dtdy = -( dt / g%max_depth ) * dhdy
Referenced by rossby_front_initialize_velocity().
hml()
real function rossby_front_2d_initialization::hml (type(ocean_grid_type), intent(in) G, real, intent(in) lat) private
Analytic prescription of mixed layer depth in 2d Rossby front test.
Parameters
[in] g Grid structure
[in] lat Latitude
Definition at line 201 of file Rossby_front_2d_initialization.F90.
   type(ocean_grid_type), intent(in) :: G   !< Grid structure
   real,                  intent(in) :: lat !< Latitude
   ! Local
   real :: dHML, HMLmean
   dhml = 0.5 * ( hmlmax - hmlmin ) * g%max_depth
   hmlmean = 0.5 * ( hmlmin + hmlmax ) * g%max_depth
   hml = hmlmean + dhml * sin( ypseudo(g, lat) )
References hmlmax, hmlmin, and ypseudo().
Referenced by rossby_front_initialize_temperature_salinity(), rossby_front_initialize_thickness(), and rossby_front_initialize_velocity().
rossby_front_initialize_temperature_salinity()
subroutine, public rossby_front_2d_initialization::rossby_front_initialize_temperature_salinity (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) T, real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) S, real, dimension(szi_(g),szj_(g), szk_(g)), intent(in) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Initialization of temperature and salinity in the Rossby front test.
Parameters
[in] g Grid structure
[out] t Potential temperature [deg C]
[out] s Salinity [ppt]
[in] h Thickness
[in] param_file Parameter file handle
eqn_of_state Equation of state structure
Definition at line 99 of file Rossby_front_2d_initialization.F90.
   type(ocean_grid_type),                     intent(in)  :: G  !< Grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: T  !< Potential temperature [deg C]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: S  !< Salinity [ppt]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(in)  :: h  !< Thickness
   type(param_file_type),                     intent(in)  :: param_file   !< Parameter file handle
   type(EOS_type),                            pointer     :: eqn_of_state !< Equation of state structure
   integer   :: i, j, k, is, ie, js, je, nz
   real      :: T_ref, S_ref ! Reference salinity and temerature within surface layer
   real      :: T_range      ! Range of salinities and temperatures over the vertical
   real      :: y, zc, zi, dTdz
   character(len=40) :: verticalCoordinate
   real      :: PI                   ! 3.1415926... calculated as 4*atan(1)
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   call get_param(param_file,mod,"REGRIDDING_COORDINATE_MODE", verticalcoordinate, &
             default=default_coordinate_mode)
   call get_param(param_file,mod,"S_REF",s_ref,'Reference salinity',units='1e-3',fail_if_missing=.true.)
   call get_param(param_file,mod,"T_REF",t_ref,'Reference temperature',units='C',fail_if_missing=.true.)
   call get_param(param_file,mod,"T_RANGE",t_range,'Initial temperature range',units='C',default=0.0)
   t(:,:,:) = 0.0
   s(:,:,:) = s_ref
   dtdz = t_range / g%max_depth
   do j = g%jsc,g%jec ; do i = g%isc,g%iec
     zi = 0.
     do k = 1, nz
       zi = zi - h(i,j,k)              ! Bottom interface position
       zc = zi - 0.5*h(i,j,k)          ! Position of middle of cell
       zc = min( zc, -hml(g, g%geoLatT(i,j)) ) ! Bound by depth of mixed layer
       t(i,j,k) = t_ref + dtdz * zc ! Linear temperature profile
     enddo
   end do ; end do
References hml(), and mod.
rossby_front_initialize_thickness()
subroutine, public rossby_front_2d_initialization::rossby_front_initialize_thickness (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) h, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file)
Initialization of thicknesses in 2D Rossby front test.
Parameters
[in] g Grid structure
[in] gv Vertical grid structure
[out] h Thickness
[in] param_file Parameter file handle
Definition at line 40 of file Rossby_front_2d_initialization.F90.
   type(ocean_grid_type),   intent(in) :: G                 !< Grid structure
   type(verticalGrid_type), intent(in) :: GV                !< Vertical grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: h !< Thickness
   type(param_file_type),   intent(in) :: param_file        !< Parameter file handle
   integer :: i, j, k, is, ie, js, je, nz
   real    :: Tz, Dml, eta, stretch, h0
   real    :: min_thickness, T_range, dRho_dT
   character(len=40) :: verticalCoordinate
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   call mom_mesg("Rossby_front_2d_initialization.F90, Rossby_front_initialize_thickness: setting thickness")
   ! Read parameters needed to set thickness
   call get_param(param_file, mod, "MIN_THICKNESS", min_thickness, &
                  'Minimum layer thickness',units='m',default=1.e-3)
   call get_param(param_file, mod, "REGRIDDING_COORDINATE_MODE", verticalcoordinate, &
                  default=default_coordinate_mode)
   call get_param(param_file, mod, "T_RANGE", t_range, 'Initial temperature range', units='C', default=0.0)
   call get_param(param_file, mod, "DRHO_DT", drho_dt, default=-0.2, do_not_log=.true.)
   tz = t_range / g%max_depth
   select case ( coordinatemode(verticalcoordinate) )
     case (regridding_layer, regridding_rho)
       do j = g%jsc,g%jec ; do i = g%isc,g%iec
         dml = hml( g, g%geoLatT(i,j) )
         eta = -( -drho_dt / gv%Rho0 ) * tz * 0.5 * ( dml * dml )
         stretch = ( ( g%max_depth + eta ) / g%max_depth )
         h0 = ( g%max_depth / real(nz) ) * stretch
         do k = 1, nz
           h(i,j,k) = h0
         enddo
       end do ; end do
     case (regridding_zstar, regridding_sigma)
       do j = g%jsc,g%jec ; do i = g%isc,g%iec
         dml = hml( g, g%geoLatT(i,j) )
         eta = -( -drho_dt / gv%Rho0 ) * tz * 0.5 * ( dml * dml )
         stretch = ( ( g%max_depth + eta ) / g%max_depth )
         h0 = ( g%max_depth / real(nz) ) * stretch
         do k = 1, nz
           h(i,j,k) = h0
         enddo
       end do ; end do
     case default
       call mom_error(fatal,"Rossby_front_initialize: "// &
       "Unrecognized i.c. setup - set REGRIDDING_COORDINATE_MODE")
   end select
References hml(), mod, mom_error_handler::mom_error(), mom_error_handler::mom_mesg(), regrid_consts::regridding_rho, and regrid_consts::regridding_sigma.
rossby_front_initialize_velocity()
subroutine, public rossby_front_2d_initialization::rossby_front_initialize_velocity (real, dimension(szib_(g),szj_(g),szk_(g)), intent(out) u, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(out) v, real, dimension(szi_(g),szj_(g), szk_(g)), intent(in) h, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file)
Initialization of u and v in the Rossby front test.
Parameters
[in] g Grid structure
[in] gv Vertical grid structure
[out] u i-component of velocity [m/s]
[out] v j-component of velocity [m/s]
[in] h Thickness [H]
[in] param_file A structure indicating the open file to parse for model parameter values.
Definition at line 140 of file Rossby_front_2d_initialization.F90.
   type(ocean_grid_type),                  intent(in)     :: G  !< Grid structure
   type(verticalGrid_type),                intent(in)     :: GV !< Vertical grid structure
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(out) :: u  !< i-component of velocity [m/s]
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(out) :: v  !< j-component of velocity [m/s]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(in)  :: h  !< Thickness [H]
   type(param_file_type),                  intent(in)     :: param_file !< A structure indicating the
                                                                !! open file to parse for model
                                                                !! parameter values.
   real    :: y              ! Non-dimensional coordinate across channel, 0..pi
   real    :: T_range        ! Range of salinities and temperatures over the vertical
   real    :: dUdT           ! Factor to convert dT/dy into dU/dz, g*alpha/f
   real    :: dRho_dT, zi, zc, zm, f, Ty, Dml, hAtU
   integer :: i, j, k, is, ie, js, je, nz
   character(len=40) :: verticalCoordinate
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   call get_param(param_file, mod, "REGRIDDING_COORDINATE_MODE", verticalcoordinate, &
             default=default_coordinate_mode)
   call get_param(param_file, mod, "T_RANGE", t_range, 'Initial temperature range', units='C', default=0.0)
   call get_param(param_file, mod, "DRHO_DT", drho_dt, default=-0.2, do_not_log=.true.)
   v(:,:,:) = 0.0
   u(:,:,:) = 0.0
   do j = g%jsc,g%jec ; do i = g%isc-1,g%iec+1
     f = 0.5*( g%CoriolisBu(i,j) + g%CoriolisBu(i,j-1) )
     dudt = 0.0 ; if (abs(f) > 0.0) &
       dudt = ( gv%g_Earth * drho_dt ) / ( f * gv%Rho0 )
     dml = hml( g, g%geoLatT(i,j) )
     ty = dtdy( g, t_range, g%geoLatT(i,j) )
     zi = 0.
     do k = 1, nz
       hatu = 0.5*(h(i,j,k)+h(i+1,j,k))
       zi = zi - hatu              ! Bottom interface position
       zc = zi - 0.5*hatu          ! Position of middle of cell
       zm = max( zc + dml, 0. )    ! Height above bottom of mixed layer
       u(i,j,k) = dudt * ty * zm   ! Thermal wind starting at base of ML
     enddo
   enddo ; enddo
References dtdy(), hml(), and mod.
Referenced by mom_state_initialization::mom_initialize_state().
ypseudo()
real function rossby_front_2d_initialization::ypseudo (type(ocean_grid_type), intent(in) G, real, intent(in) lat) private
Pseudo coordinate across domain used by Hml() and dTdy() returns a coordinate from -PI/2 .. PI/2 squashed towards the center of the domain.
Parameters
[in] g Grid structure
[in] lat Latitude
Definition at line 188 of file Rossby_front_2d_initialization.F90.
   type(ocean_grid_type), intent(in) :: G   !< Grid structure
   real,                  intent(in) :: lat !< Latitude
   ! Local
   real :: y, PI
   pi = 4.0 * atan(1.0)
   ypseudo = ( ( lat - g%south_lat ) / g%len_lat ) - 0.5 ! -1/2 .. 1/.2
   ypseudo = pi * max(-0.5, min(0.5, ypseudo / frontfractionalwidth))
References frontfractionalwidth.
Referenced by hml().
Variable Documentation
frontfractionalwidth
real, parameter rossby_front_2d_initialization::frontfractionalwidth = 0.5 private
Width of front as fraction of domain.
Definition at line 32 of file Rossby_front_2d_initialization.F90.
 real, parameter :: frontFractionalWidth = 0.5 !< Width of front as fraction of domain
Referenced by ypseudo().
hmlmax
real, parameter rossby_front_2d_initialization::hmlmax = 0.75 private
Deepest ML as fractional depth of ocean.
Definition at line 34 of file Rossby_front_2d_initialization.F90.
 real, parameter :: HMLmax = 0.75 !< Deepest ML as fractional depth of ocean
Referenced by hml().
hmlmin
real, parameter rossby_front_2d_initialization::hmlmin = 0.25 private
Shallowest ML as fractional depth of ocean.
Definition at line 33 of file Rossby_front_2d_initialization.F90.
 real, parameter :: HMLmin = 0.25 !< Shallowest ML as fractional depth of ocean
Referenced by hml().
mod
character(len=40) rossby_front_2d_initialization::mod = "Rossby_front_2d_initialization" private
This module's name.
Definition at line 25 of file Rossby_front_2d_initialization.F90.
 character(len=40) :: mod = "Rossby_front_2d_initialization" !< This module's name.
Referenced by rossby_front_initialize_temperature_salinity(), rossby_front_initialize_thickness(), and rossby_front_initialize_velocity().