MOM6: gsw_mod_specvol_coefficients Module Reference
gsw_mod_specvol_coefficients Module Reference
Variables
real(r8), parameter a000 = -1.56497346750e-5_r8
real(r8), parameter a001 = 1.85057654290e-5_r8
real(r8), parameter a002 = -1.17363867310e-6_r8
real(r8), parameter a003 = -3.65270065530e-7_r8
real(r8), parameter a004 = 3.14540999020e-7_r8
real(r8), parameter a010 = 5.55242129680e-5_r8
real(r8), parameter a011 = -2.34332137060e-5_r8
real(r8), parameter a012 = 4.26100574800e-6_r8
real(r8), parameter a013 = 5.73918103180e-7_r8
real(r8), parameter a020 = -4.95634777770e-5_r8
real(r8), parameter a021 = 2.37838968519e-5_r8
real(r8), parameter a022 = -1.38397620111e-6_r8
real(r8), parameter a030 = 2.76445290808e-5_r8
real(r8), parameter a031 = -1.36408749928e-5_r8
real(r8), parameter a032 = -2.53411666056e-7_r8
real(r8), parameter a040 = -4.02698077700e-6_r8
real(r8), parameter a041 = 2.53683834070e-6_r8
real(r8), parameter a050 = 1.23258565608e-6_r8
real(r8), parameter a100 = 3.50095997640e-5_r8
real(r8), parameter a101 = -9.56770881560e-6_r8
real(r8), parameter a102 = -5.56991545570e-6_r8
real(r8), parameter a103 = -2.72956962370e-7_r8
real(r8), parameter a110 = -7.48716846880e-5_r8
real(r8), parameter a111 = -4.73566167220e-7_r8
real(r8), parameter a112 = 7.82747741600e-7_r8
real(r8), parameter a120 = 7.24244384490e-5_r8
real(r8), parameter a121 = -1.03676320965e-5_r8
real(r8), parameter a122 = 2.32856664276e-8_r8
real(r8), parameter a130 = -3.50383492616e-5_r8
real(r8), parameter a131 = 5.18268711320e-6_r8
real(r8), parameter a140 = -1.65263794500e-6_r8
real(r8), parameter a200 = -4.35926785610e-5_r8
real(r8), parameter a201 = 1.11008347650e-5_r8
real(r8), parameter a202 = 5.46207488340e-6_r8
real(r8), parameter a210 = 7.18156455200e-5_r8
real(r8), parameter a211 = 5.85666925900e-6_r8
real(r8), parameter a212 = -1.31462208134e-6_r8
real(r8), parameter a220 = -4.30608991440e-5_r8
real(r8), parameter a221 = 9.49659182340e-7_r8
real(r8), parameter a230 = 1.74814722392e-5_r8
real(r8), parameter a300 = 3.45324618280e-5_r8
real(r8), parameter a301 = -9.84471178440e-6_r8
real(r8), parameter a302 = -1.35441856270e-6_r8
real(r8), parameter a310 = -3.73971683740e-5_r8
real(r8), parameter a311 = -9.76522784000e-7_r8
real(r8), parameter a320 = 6.85899736680e-6_r8
real(r8), parameter a400 = -1.19594097880e-5_r8
real(r8), parameter a401 = 2.59092252600e-6_r8
real(r8), parameter a410 = 7.71906784880e-6_r8
real(r8), parameter a500 = 1.38645945810e-6_r8
real(r8), parameter b000 = -3.10389819760e-4_r8
real(r8), parameter b003 = 3.63101885150e-7_r8
real(r8), parameter b004 = -1.11471254230e-7_r8
real(r8), parameter b010 = 3.50095997640e-5_r8
real(r8), parameter b013 = -2.72956962370e-7_r8
real(r8), parameter b020 = -3.74358423440e-5_r8
real(r8), parameter b030 = 2.41414794830e-5_r8
real(r8), parameter b040 = -8.75958731540e-6_r8
real(r8), parameter b050 = -3.30527589000e-7_r8
real(r8), parameter b100 = 1.33856134076e-3_r8
real(r8), parameter b103 = 3.34926075600e-8_r8
real(r8), parameter b110 = -8.71853571220e-5_r8
real(r8), parameter b120 = 7.18156455200e-5_r8
real(r8), parameter b130 = -2.87072660960e-5_r8
real(r8), parameter b140 = 8.74073611960e-6_r8
real(r8), parameter b200 = -2.55143801811e-3_r8
real(r8), parameter b210 = 1.03597385484e-4_r8
real(r8), parameter b220 = -5.60957525610e-5_r8
real(r8), parameter b230 = 6.85899736680e-6_r8
real(r8), parameter b300 = 2.32344279772e-3_r8
real(r8), parameter b310 = -4.78376391520e-5_r8
real(r8), parameter b320 = 1.54381356976e-5_r8
real(r8), parameter b400 = -1.05461852535e-3_r8
real(r8), parameter b410 = 6.93229729050e-6_r8
real(r8), parameter b500 = 1.91594743830e-4_r8
real(r8), parameter b001 = 2.42624687470e-5_r8
real(r8), parameter b011 = -9.56770881560e-6_r8
real(r8), parameter b021 = -2.36783083610e-7_r8
real(r8), parameter b031 = -3.45587736550e-6_r8
real(r8), parameter b041 = 1.29567177830e-6_r8
real(r8), parameter b101 = -6.95849219480e-5_r8
real(r8), parameter b111 = 2.22016695300e-5_r8
real(r8), parameter b121 = 5.85666925900e-6_r8
real(r8), parameter b131 = 6.33106121560e-7_r8
real(r8), parameter b201 = 1.12412331915e-4_r8
real(r8), parameter b211 = -2.95341353532e-5_r8
real(r8), parameter b221 = -1.46478417600e-6_r8
real(r8), parameter b301 = -6.92888744480e-5_r8
real(r8), parameter b311 = 1.03636901040e-5_r8
real(r8), parameter b401 = 1.54637136265e-5_r8
real(r8), parameter b002 = -5.84844329840e-7_r8
real(r8), parameter b012 = -5.56991545570e-6_r8
real(r8), parameter b022 = 3.91373870800e-7_r8
real(r8), parameter b032 = 7.76188880920e-9_r8
real(r8), parameter b102 = -9.62445031940e-6_r8
real(r8), parameter b112 = 1.09241497668e-5_r8
real(r8), parameter b122 = -1.31462208134e-6_r8
real(r8), parameter b202 = 1.47789320994e-5_r8
real(r8), parameter b212 = -4.06325568810e-6_r8
real(r8), parameter b302 = -7.12478989080e-6_r8
real(r8), parameter c000 = -6.07991438090e-5_r8
real(r8), parameter c001 = 1.99712338438e-5_r8
real(r8), parameter c002 = -3.39280843110e-6_r8
real(r8), parameter c003 = 4.21246123200e-7_r8
real(r8), parameter c004 = -6.32363064300e-8_r8
real(r8), parameter c005 = 1.17681023580e-8_r8
real(r8), parameter c010 = 1.85057654290e-5_r8
real(r8), parameter c011 = -2.34727734620e-6_r8
real(r8), parameter c012 = -1.09581019659e-6_r8
real(r8), parameter c013 = 1.25816399608e-6_r8
real(r8), parameter c020 = -1.17166068530e-5_r8
real(r8), parameter c021 = 4.26100574800e-6_r8
real(r8), parameter c022 = 8.60877154770e-7_r8
real(r8), parameter c030 = 7.92796561730e-6_r8
real(r8), parameter c031 = -9.22650800740e-7_r8
real(r8), parameter c040 = -3.41021874820e-6_r8
real(r8), parameter c041 = -1.26705833028e-7_r8
real(r8), parameter c050 = 5.07367668140e-7_r8
real(r8), parameter c100 = 2.42624687470e-5_r8
real(r8), parameter c101 = -1.16968865968e-6_r8
real(r8), parameter c102 = 1.08930565545e-6_r8
real(r8), parameter c103 = -4.45885016920e-7_r8
real(r8), parameter c110 = -9.56770881560e-6_r8
real(r8), parameter c111 = -1.11398309114e-5_r8
real(r8), parameter c112 = -8.18870887110e-7_r8
real(r8), parameter c120 = -2.36783083610e-7_r8
real(r8), parameter c121 = 7.82747741600e-7_r8
real(r8), parameter c130 = -3.45587736550e-6_r8
real(r8), parameter c131 = 1.55237776184e-8_r8
real(r8), parameter c140 = 1.29567177830e-6_r8
real(r8), parameter c200 = -3.47924609740e-5_r8
real(r8), parameter c201 = -9.62445031940e-6_r8
real(r8), parameter c202 = 5.02389113400e-8_r8
real(r8), parameter c210 = 1.11008347650e-5_r8
real(r8), parameter c211 = 1.09241497668e-5_r8
real(r8), parameter c220 = 2.92833462950e-6_r8
real(r8), parameter c221 = -1.31462208134e-6_r8
real(r8), parameter c230 = 3.16553060780e-7_r8
real(r8), parameter c300 = 3.74707773050e-5_r8
real(r8), parameter c301 = 9.85262139960e-6_r8
real(r8), parameter c310 = -9.84471178440e-6_r8
real(r8), parameter c311 = -2.70883712540e-6_r8
real(r8), parameter c320 = -4.88261392000e-7_r8
real(r8), parameter c400 = -1.73222186120e-5_r8
real(r8), parameter c401 = -3.56239494540e-6_r8
real(r8), parameter c410 = 2.59092252600e-6_r8
real(r8), parameter c500 = 3.09274272530e-6_r8
real(r8), parameter h001 = 1.07699958620e-3_r8
real(r8), parameter h002 = -3.03995719050e-5_r8
real(r8), parameter h003 = 3.32853897400e-6_r8
real(r8), parameter h004 = -2.82734035930e-7_r8
real(r8), parameter h005 = 2.10623061600e-8_r8
real(r8), parameter h006 = -2.10787688100e-9_r8
real(r8), parameter h007 = 2.80192913290e-10_r8
real(r8), parameter h011 = -1.56497346750e-5_r8
real(r8), parameter h012 = 9.25288271450e-6_r8
real(r8), parameter h013 = -3.91212891030e-7_r8
real(r8), parameter h014 = -9.13175163830e-8_r8
real(r8), parameter h015 = 6.29081998040e-8_r8
real(r8), parameter h021 = 2.77621064840e-5_r8
real(r8), parameter h022 = -5.85830342650e-6_r8
real(r8), parameter h023 = 7.10167624670e-7_r8
real(r8), parameter h024 = 7.17397628980e-8_r8
real(r8), parameter h031 = -1.65211592590e-5_r8
real(r8), parameter h032 = 3.96398280870e-6_r8
real(r8), parameter h033 = -1.53775133460e-7_r8
real(r8), parameter h042 = -1.70510937410e-6_r8
real(r8), parameter h043 = -2.11176388380e-8_r8
real(r8), parameter h041 = 6.91113227020e-6_r8
real(r8), parameter h051 = -8.05396155400e-7_r8
real(r8), parameter h052 = 2.53683834070e-7_r8
real(r8), parameter h061 = 2.05430942680e-7_r8
real(r8), parameter h101 = -3.10389819760e-4_r8
real(r8), parameter h102 = 1.21312343735e-5_r8
real(r8), parameter h103 = -1.94948109950e-7_r8
real(r8), parameter h104 = 9.07754712880e-8_r8
real(r8), parameter h105 = -2.22942508460e-8_r8
real(r8), parameter h111 = 3.50095997640e-5_r8
real(r8), parameter h112 = -4.78385440780e-6_r8
real(r8), parameter h113 = -1.85663848520e-6_r8
real(r8), parameter h114 = -6.82392405930e-8_r8
real(r8), parameter h121 = -3.74358423440e-5_r8
real(r8), parameter h122 = -1.18391541805e-7_r8
real(r8), parameter h123 = 1.30457956930e-7_r8
real(r8), parameter h131 = 2.41414794830e-5_r8
real(r8), parameter h132 = -1.72793868275e-6_r8
real(r8), parameter h133 = 2.58729626970e-9_r8
real(r8), parameter h141 = -8.75958731540e-6_r8
real(r8), parameter h142 = 6.47835889150e-7_r8
real(r8), parameter h151 = -3.30527589000e-7_r8
real(r8), parameter h201 = 6.69280670380e-4_r8
real(r8), parameter h202 = -1.73962304870e-5_r8
real(r8), parameter h203 = -1.60407505320e-6_r8
real(r8), parameter h204 = 4.18657594500e-9_r8
real(r8), parameter h211 = -4.35926785610e-5_r8
real(r8), parameter h212 = 5.55041738250e-6_r8
real(r8), parameter h213 = 1.82069162780e-6_r8
real(r8), parameter h221 = 3.59078227600e-5_r8
real(r8), parameter h222 = 1.46416731475e-6_r8
real(r8), parameter h223 = -2.19103680220e-7_r8
real(r8), parameter h231 = -1.43536330480e-5_r8
real(r8), parameter h232 = 1.58276530390e-7_r8
real(r8), parameter h241 = 4.37036805980e-6_r8
real(r8), parameter h301 = -8.50479339370e-4_r8
real(r8), parameter h302 = 1.87353886525e-5_r8
real(r8), parameter h303 = 1.64210356660e-6_r8
real(r8), parameter h311 = 3.45324618280e-5_r8
real(r8), parameter h312 = -4.92235589220e-6_r8
real(r8), parameter h313 = -4.51472854230e-7_r8
real(r8), parameter h321 = -1.86985841870e-5_r8
real(r8), parameter h322 = -2.44130696000e-7_r8
real(r8), parameter h331 = 2.28633245560e-6_r8
real(r8), parameter h401 = 5.80860699430e-4_r8
real(r8), parameter h402 = -8.66110930600e-6_r8
real(r8), parameter h403 = -5.93732490900e-7_r8
real(r8), parameter h411 = -1.19594097880e-5_r8
real(r8), parameter h421 = 3.85953392440e-6_r8
real(r8), parameter h412 = 1.29546126300e-6_r8
real(r8), parameter h501 = -2.10923705070e-4_r8
real(r8), parameter h502 = 1.54637136265e-6_r8
real(r8), parameter h511 = 1.38645945810e-6_r8
real(r8), parameter h601 = 3.19324573050e-5_r8
real(r8), parameter v000 = 1.0769995862e-3_r8
real(r8), parameter v001 = -6.0799143809e-5_r8
real(r8), parameter v002 = 9.9856169219e-6_r8
real(r8), parameter v003 = -1.1309361437e-6_r8
real(r8), parameter v004 = 1.0531153080e-7_r8
real(r8), parameter v005 = -1.2647261286e-8_r8
real(r8), parameter v006 = 1.9613503930e-9_r8
real(r8), parameter v010 = -3.1038981976e-4_r8
real(r8), parameter v011 = 2.4262468747e-5_r8
real(r8), parameter v012 = -5.8484432984e-7_r8
real(r8), parameter v013 = 3.6310188515e-7_r8
real(r8), parameter v014 = -1.1147125423e-7_r8
real(r8), parameter v020 = 6.6928067038e-4_r8
real(r8), parameter v021 = -3.4792460974e-5_r8
real(r8), parameter v022 = -4.8122251597e-6_r8
real(r8), parameter v023 = 1.6746303780e-8_r8
real(r8), parameter v030 = -8.5047933937e-4_r8
real(r8), parameter v031 = 3.7470777305e-5_r8
real(r8), parameter v032 = 4.9263106998e-6_r8
real(r8), parameter v040 = 5.8086069943e-4_r8
real(r8), parameter v041 = -1.7322218612e-5_r8
real(r8), parameter v042 = -1.7811974727e-6_r8
real(r8), parameter v050 = -2.1092370507e-4_r8
real(r8), parameter v051 = 3.0927427253e-6_r8
real(r8), parameter v060 = 3.1932457305e-5_r8
real(r8), parameter v100 = -1.5649734675e-5_r8
real(r8), parameter v101 = 1.8505765429e-5_r8
real(r8), parameter v102 = -1.1736386731e-6_r8
real(r8), parameter v103 = -3.6527006553e-7_r8
real(r8), parameter v104 = 3.1454099902e-7_r8
real(r8), parameter v110 = 3.5009599764e-5_r8
real(r8), parameter v111 = -9.5677088156e-6_r8
real(r8), parameter v112 = -5.5699154557e-6_r8
real(r8), parameter v113 = -2.7295696237e-7_r8
real(r8), parameter v120 = -4.3592678561e-5_r8
real(r8), parameter v121 = 1.1100834765e-5_r8
real(r8), parameter v122 = 5.4620748834e-6_r8
real(r8), parameter v130 = 3.4532461828e-5_r8
real(r8), parameter v131 = -9.8447117844e-6_r8
real(r8), parameter v132 = -1.3544185627e-6_r8
real(r8), parameter v140 = -1.1959409788e-5_r8
real(r8), parameter v141 = 2.5909225260e-6_r8
real(r8), parameter v150 = 1.3864594581e-6_r8
real(r8), parameter v200 = 2.7762106484e-5_r8
real(r8), parameter v201 = -1.1716606853e-5_r8
real(r8), parameter v202 = 2.1305028740e-6_r8
real(r8), parameter v203 = 2.8695905159e-7_r8
real(r8), parameter v210 = -3.7435842344e-5_r8
real(r8), parameter v211 = -2.3678308361e-7_r8
real(r8), parameter v212 = 3.9137387080e-7_r8
real(r8), parameter v220 = 3.5907822760e-5_r8
real(r8), parameter v221 = 2.9283346295e-6_r8
real(r8), parameter v222 = -6.5731104067e-7_r8
real(r8), parameter v230 = -1.8698584187e-5_r8
real(r8), parameter v231 = -4.8826139200e-7_r8
real(r8), parameter v240 = 3.8595339244e-6_r8
real(r8), parameter v300 = -1.6521159259e-5_r8
real(r8), parameter v301 = 7.9279656173e-6_r8
real(r8), parameter v302 = -4.6132540037e-7_r8
real(r8), parameter v310 = 2.4141479483e-5_r8
real(r8), parameter v311 = -3.4558773655e-6_r8
real(r8), parameter v312 = 7.7618888092e-9_r8
real(r8), parameter v320 = -1.4353633048e-5_r8
real(r8), parameter v321 = 3.1655306078e-7_r8
real(r8), parameter v330 = 2.2863324556e-6_r8
real(r8), parameter v400 = 6.9111322702e-6_r8
real(r8), parameter v401 = -3.4102187482e-6_r8
real(r8), parameter v402 = -6.3352916514e-8_r8
real(r8), parameter v410 = -8.7595873154e-6_r8
real(r8), parameter v411 = 1.2956717783e-6_r8
real(r8), parameter v420 = 4.3703680598e-6_r8
real(r8), parameter v500 = -8.0539615540e-7_r8
real(r8), parameter v501 = 5.0736766814e-7_r8
real(r8), parameter v510 = -3.3052758900e-7_r8
real(r8), parameter v600 = 2.0543094268e-7_r8
Variable Documentation
a000
real (r8), parameter gsw_mod_specvol_coefficients::a000 = -1.56497346750e-5_r8
Definition at line 9 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a000 = -1.56497346750e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a001
real (r8), parameter gsw_mod_specvol_coefficients::a001 = 1.85057654290e-5_r8
Definition at line 10 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a001 =  1.85057654290e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a002
real (r8), parameter gsw_mod_specvol_coefficients::a002 = -1.17363867310e-6_r8
Definition at line 11 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a002 = -1.17363867310e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a003
real (r8), parameter gsw_mod_specvol_coefficients::a003 = -3.65270065530e-7_r8
Definition at line 12 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a003 = -3.65270065530e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a004
real (r8), parameter gsw_mod_specvol_coefficients::a004 = 3.14540999020e-7_r8
Definition at line 13 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a004 =  3.14540999020e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a010
real (r8), parameter gsw_mod_specvol_coefficients::a010 = 5.55242129680e-5_r8
Definition at line 14 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a010 =  5.55242129680e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a011
real (r8), parameter gsw_mod_specvol_coefficients::a011 = -2.34332137060e-5_r8
Definition at line 15 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a011 = -2.34332137060e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a012
real (r8), parameter gsw_mod_specvol_coefficients::a012 = 4.26100574800e-6_r8
Definition at line 16 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a012 =  4.26100574800e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a013
real (r8), parameter gsw_mod_specvol_coefficients::a013 = 5.73918103180e-7_r8
Definition at line 17 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a013 =  5.73918103180e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a020
real (r8), parameter gsw_mod_specvol_coefficients::a020 = -4.95634777770e-5_r8
Definition at line 18 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a020 = -4.95634777770e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a021
real (r8), parameter gsw_mod_specvol_coefficients::a021 = 2.37838968519e-5_r8
Definition at line 19 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a021 =  2.37838968519e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a022
real (r8), parameter gsw_mod_specvol_coefficients::a022 = -1.38397620111e-6_r8
Definition at line 20 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a022 = -1.38397620111e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a030
real (r8), parameter gsw_mod_specvol_coefficients::a030 = 2.76445290808e-5_r8
Definition at line 21 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a030 =  2.76445290808e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a031
real (r8), parameter gsw_mod_specvol_coefficients::a031 = -1.36408749928e-5_r8
Definition at line 22 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a031 = -1.36408749928e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a032
real (r8), parameter gsw_mod_specvol_coefficients::a032 = -2.53411666056e-7_r8
Definition at line 23 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a032 = -2.53411666056e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a040
real (r8), parameter gsw_mod_specvol_coefficients::a040 = -4.02698077700e-6_r8
Definition at line 24 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a040 = -4.02698077700e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a041
real (r8), parameter gsw_mod_specvol_coefficients::a041 = 2.53683834070e-6_r8
Definition at line 25 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a041 =  2.53683834070e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a050
real (r8), parameter gsw_mod_specvol_coefficients::a050 = 1.23258565608e-6_r8
Definition at line 26 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a050 =  1.23258565608e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a100
real (r8), parameter gsw_mod_specvol_coefficients::a100 = 3.50095997640e-5_r8
Definition at line 27 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a100 =  3.50095997640e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a101
real (r8), parameter gsw_mod_specvol_coefficients::a101 = -9.56770881560e-6_r8
Definition at line 28 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a101 = -9.56770881560e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a102
real (r8), parameter gsw_mod_specvol_coefficients::a102 = -5.56991545570e-6_r8
Definition at line 29 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a102 = -5.56991545570e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a103
real (r8), parameter gsw_mod_specvol_coefficients::a103 = -2.72956962370e-7_r8
Definition at line 30 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a103 = -2.72956962370e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a110
real (r8), parameter gsw_mod_specvol_coefficients::a110 = -7.48716846880e-5_r8
Definition at line 31 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a110 = -7.48716846880e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a111
real (r8), parameter gsw_mod_specvol_coefficients::a111 = -4.73566167220e-7_r8
Definition at line 32 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a111 = -4.73566167220e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a112
real (r8), parameter gsw_mod_specvol_coefficients::a112 = 7.82747741600e-7_r8
Definition at line 33 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a112 =  7.82747741600e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a120
real (r8), parameter gsw_mod_specvol_coefficients::a120 = 7.24244384490e-5_r8
Definition at line 34 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a120 =  7.24244384490e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a121
real (r8), parameter gsw_mod_specvol_coefficients::a121 = -1.03676320965e-5_r8
Definition at line 35 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a121 = -1.03676320965e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a122
real (r8), parameter gsw_mod_specvol_coefficients::a122 = 2.32856664276e-8_r8
Definition at line 36 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a122 =  2.32856664276e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a130
real (r8), parameter gsw_mod_specvol_coefficients::a130 = -3.50383492616e-5_r8
Definition at line 37 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a130 = -3.50383492616e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a131
real (r8), parameter gsw_mod_specvol_coefficients::a131 = 5.18268711320e-6_r8
Definition at line 38 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a131 =  5.18268711320e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a140
real (r8), parameter gsw_mod_specvol_coefficients::a140 = -1.65263794500e-6_r8
Definition at line 39 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a140 = -1.65263794500e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a200
real (r8), parameter gsw_mod_specvol_coefficients::a200 = -4.35926785610e-5_r8
Definition at line 40 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a200 = -4.35926785610e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a201
real (r8), parameter gsw_mod_specvol_coefficients::a201 = 1.11008347650e-5_r8
Definition at line 41 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a201 =  1.11008347650e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a202
real (r8), parameter gsw_mod_specvol_coefficients::a202 = 5.46207488340e-6_r8
Definition at line 42 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a202 =  5.46207488340e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a210
real (r8), parameter gsw_mod_specvol_coefficients::a210 = 7.18156455200e-5_r8
Definition at line 43 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a210 =  7.18156455200e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a211
real (r8), parameter gsw_mod_specvol_coefficients::a211 = 5.85666925900e-6_r8
Definition at line 44 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a211 =  5.85666925900e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a212
real (r8), parameter gsw_mod_specvol_coefficients::a212 = -1.31462208134e-6_r8
Definition at line 45 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a212 = -1.31462208134e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a220
real (r8), parameter gsw_mod_specvol_coefficients::a220 = -4.30608991440e-5_r8
Definition at line 46 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a220 = -4.30608991440e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a221
real (r8), parameter gsw_mod_specvol_coefficients::a221 = 9.49659182340e-7_r8
Definition at line 47 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a221 =  9.49659182340e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a230
real (r8), parameter gsw_mod_specvol_coefficients::a230 = 1.74814722392e-5_r8
Definition at line 48 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a230 =  1.74814722392e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a300
real (r8), parameter gsw_mod_specvol_coefficients::a300 = 3.45324618280e-5_r8
Definition at line 49 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a300 =  3.45324618280e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a301
real (r8), parameter gsw_mod_specvol_coefficients::a301 = -9.84471178440e-6_r8
Definition at line 50 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a301 = -9.84471178440e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a302
real (r8), parameter gsw_mod_specvol_coefficients::a302 = -1.35441856270e-6_r8
Definition at line 51 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a302 = -1.35441856270e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a310
real (r8), parameter gsw_mod_specvol_coefficients::a310 = -3.73971683740e-5_r8
Definition at line 52 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a310 = -3.73971683740e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a311
real (r8), parameter gsw_mod_specvol_coefficients::a311 = -9.76522784000e-7_r8
Definition at line 53 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a311 = -9.76522784000e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a320
real (r8), parameter gsw_mod_specvol_coefficients::a320 = 6.85899736680e-6_r8
Definition at line 54 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a320 =  6.85899736680e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a400
real (r8), parameter gsw_mod_specvol_coefficients::a400 = -1.19594097880e-5_r8
Definition at line 55 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a400 = -1.19594097880e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a401
real (r8), parameter gsw_mod_specvol_coefficients::a401 = 2.59092252600e-6_r8
Definition at line 56 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a401 =  2.59092252600e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a410
real (r8), parameter gsw_mod_specvol_coefficients::a410 = 7.71906784880e-6_r8
Definition at line 57 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a410 =  7.71906784880e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
a500
real (r8), parameter gsw_mod_specvol_coefficients::a500 = 1.38645945810e-6_r8
Definition at line 58 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: a500 =  1.38645945810e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b000
real (r8), parameter gsw_mod_specvol_coefficients::b000 = -3.10389819760e-4_r8
Definition at line 60 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b000 = -3.10389819760e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b001
real (r8), parameter gsw_mod_specvol_coefficients::b001 = 2.42624687470e-5_r8
Definition at line 85 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b001 =  2.42624687470e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b002
real (r8), parameter gsw_mod_specvol_coefficients::b002 = -5.84844329840e-7_r8
Definition at line 100 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b002 = -5.84844329840e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b003
real (r8), parameter gsw_mod_specvol_coefficients::b003 = 3.63101885150e-7_r8
Definition at line 61 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b003 =  3.63101885150e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b004
real (r8), parameter gsw_mod_specvol_coefficients::b004 = -1.11471254230e-7_r8
Definition at line 62 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b004 = -1.11471254230e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b010
real (r8), parameter gsw_mod_specvol_coefficients::b010 = 3.50095997640e-5_r8
Definition at line 63 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b010 =  3.50095997640e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b011
real (r8), parameter gsw_mod_specvol_coefficients::b011 = -9.56770881560e-6_r8
Definition at line 86 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b011 = -9.56770881560e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b012
real (r8), parameter gsw_mod_specvol_coefficients::b012 = -5.56991545570e-6_r8
Definition at line 101 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b012 = -5.56991545570e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b013
real (r8), parameter gsw_mod_specvol_coefficients::b013 = -2.72956962370e-7_r8
Definition at line 64 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b013 = -2.72956962370e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b020
real (r8), parameter gsw_mod_specvol_coefficients::b020 = -3.74358423440e-5_r8
Definition at line 65 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b020 = -3.74358423440e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b021
real (r8), parameter gsw_mod_specvol_coefficients::b021 = -2.36783083610e-7_r8
Definition at line 87 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b021 = -2.36783083610e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b022
real (r8), parameter gsw_mod_specvol_coefficients::b022 = 3.91373870800e-7_r8
Definition at line 102 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b022 =  3.91373870800e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b030
real (r8), parameter gsw_mod_specvol_coefficients::b030 = 2.41414794830e-5_r8
Definition at line 66 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b030 =  2.41414794830e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b031
real (r8), parameter gsw_mod_specvol_coefficients::b031 = -3.45587736550e-6_r8
Definition at line 88 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b031 = -3.45587736550e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b032
real (r8), parameter gsw_mod_specvol_coefficients::b032 = 7.76188880920e-9_r8
Definition at line 103 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b032 =  7.76188880920e-9_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b040
real (r8), parameter gsw_mod_specvol_coefficients::b040 = -8.75958731540e-6_r8
Definition at line 67 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b040 = -8.75958731540e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b041
real (r8), parameter gsw_mod_specvol_coefficients::b041 = 1.29567177830e-6_r8
Definition at line 89 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b041 =  1.29567177830e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b050
real (r8), parameter gsw_mod_specvol_coefficients::b050 = -3.30527589000e-7_r8
Definition at line 68 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b050 = -3.30527589000e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b100
real (r8), parameter gsw_mod_specvol_coefficients::b100 = 1.33856134076e-3_r8
Definition at line 69 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b100 =  1.33856134076e-3_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b101
real (r8), parameter gsw_mod_specvol_coefficients::b101 = -6.95849219480e-5_r8
Definition at line 90 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b101 = -6.95849219480e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b102
real (r8), parameter gsw_mod_specvol_coefficients::b102 = -9.62445031940e-6_r8
Definition at line 104 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b102 = -9.62445031940e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b103
real (r8), parameter gsw_mod_specvol_coefficients::b103 = 3.34926075600e-8_r8
Definition at line 70 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b103 =  3.34926075600e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b110
real (r8), parameter gsw_mod_specvol_coefficients::b110 = -8.71853571220e-5_r8
Definition at line 71 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b110 = -8.71853571220e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b111
real (r8), parameter gsw_mod_specvol_coefficients::b111 = 2.22016695300e-5_r8
Definition at line 91 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b111 =  2.22016695300e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b112
real (r8), parameter gsw_mod_specvol_coefficients::b112 = 1.09241497668e-5_r8
Definition at line 105 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b112 =  1.09241497668e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b120
real (r8), parameter gsw_mod_specvol_coefficients::b120 = 7.18156455200e-5_r8
Definition at line 72 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b120 =  7.18156455200e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b121
real (r8), parameter gsw_mod_specvol_coefficients::b121 = 5.85666925900e-6_r8
Definition at line 92 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b121 =  5.85666925900e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b122
real (r8), parameter gsw_mod_specvol_coefficients::b122 = -1.31462208134e-6_r8
Definition at line 106 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b122 = -1.31462208134e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b130
real (r8), parameter gsw_mod_specvol_coefficients::b130 = -2.87072660960e-5_r8
Definition at line 73 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b130 = -2.87072660960e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b131
real (r8), parameter gsw_mod_specvol_coefficients::b131 = 6.33106121560e-7_r8
Definition at line 93 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b131 =  6.33106121560e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b140
real (r8), parameter gsw_mod_specvol_coefficients::b140 = 8.74073611960e-6_r8
Definition at line 74 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b140 =  8.74073611960e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b200
real (r8), parameter gsw_mod_specvol_coefficients::b200 = -2.55143801811e-3_r8
Definition at line 75 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b200 = -2.55143801811e-3_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b201
real (r8), parameter gsw_mod_specvol_coefficients::b201 = 1.12412331915e-4_r8
Definition at line 94 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b201 =  1.12412331915e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b202
real (r8), parameter gsw_mod_specvol_coefficients::b202 = 1.47789320994e-5_r8
Definition at line 107 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b202 =  1.47789320994e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b210
real (r8), parameter gsw_mod_specvol_coefficients::b210 = 1.03597385484e-4_r8
Definition at line 76 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b210 =  1.03597385484e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b211
real (r8), parameter gsw_mod_specvol_coefficients::b211 = -2.95341353532e-5_r8
Definition at line 95 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b211 = -2.95341353532e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b212
real (r8), parameter gsw_mod_specvol_coefficients::b212 = -4.06325568810e-6_r8
Definition at line 108 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b212 = -4.06325568810e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b220
real (r8), parameter gsw_mod_specvol_coefficients::b220 = -5.60957525610e-5_r8
Definition at line 77 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b220 = -5.60957525610e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b221
real (r8), parameter gsw_mod_specvol_coefficients::b221 = -1.46478417600e-6_r8
Definition at line 96 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b221 = -1.46478417600e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b230
real (r8), parameter gsw_mod_specvol_coefficients::b230 = 6.85899736680e-6_r8
Definition at line 78 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b230 =  6.85899736680e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b300
real (r8), parameter gsw_mod_specvol_coefficients::b300 = 2.32344279772e-3_r8
Definition at line 79 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b300 =  2.32344279772e-3_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b301
real (r8), parameter gsw_mod_specvol_coefficients::b301 = -6.92888744480e-5_r8
Definition at line 97 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b301 = -6.92888744480e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b302
real (r8), parameter gsw_mod_specvol_coefficients::b302 = -7.12478989080e-6_r8
Definition at line 109 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b302 = -7.12478989080e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b310
real (r8), parameter gsw_mod_specvol_coefficients::b310 = -4.78376391520e-5_r8
Definition at line 80 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b310 = -4.78376391520e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b311
real (r8), parameter gsw_mod_specvol_coefficients::b311 = 1.03636901040e-5_r8
Definition at line 98 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b311 =  1.03636901040e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b320
real (r8), parameter gsw_mod_specvol_coefficients::b320 = 1.54381356976e-5_r8
Definition at line 81 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b320 =  1.54381356976e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b400
real (r8), parameter gsw_mod_specvol_coefficients::b400 = -1.05461852535e-3_r8
Definition at line 82 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b400 = -1.05461852535e-3_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b401
real (r8), parameter gsw_mod_specvol_coefficients::b401 = 1.54637136265e-5_r8
Definition at line 99 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b401 =  1.54637136265e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b410
real (r8), parameter gsw_mod_specvol_coefficients::b410 = 6.93229729050e-6_r8
Definition at line 83 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b410 =  6.93229729050e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
b500
real (r8), parameter gsw_mod_specvol_coefficients::b500 = 1.91594743830e-4_r8
Definition at line 84 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: b500 =  1.91594743830e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c000
real (r8), parameter gsw_mod_specvol_coefficients::c000 = -6.07991438090e-5_r8
Definition at line 111 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c000 = -6.07991438090e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c001
real (r8), parameter gsw_mod_specvol_coefficients::c001 = 1.99712338438e-5_r8
Definition at line 112 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c001 =  1.99712338438e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c002
real (r8), parameter gsw_mod_specvol_coefficients::c002 = -3.39280843110e-6_r8
Definition at line 113 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c002 = -3.39280843110e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c003
real (r8), parameter gsw_mod_specvol_coefficients::c003 = 4.21246123200e-7_r8
Definition at line 114 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c003 =  4.21246123200e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c004
real (r8), parameter gsw_mod_specvol_coefficients::c004 = -6.32363064300e-8_r8
Definition at line 115 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c004 = -6.32363064300e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c005
real (r8), parameter gsw_mod_specvol_coefficients::c005 = 1.17681023580e-8_r8
Definition at line 116 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c005 =  1.17681023580e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c010
real (r8), parameter gsw_mod_specvol_coefficients::c010 = 1.85057654290e-5_r8
Definition at line 117 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c010 =  1.85057654290e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c011
real (r8), parameter gsw_mod_specvol_coefficients::c011 = -2.34727734620e-6_r8
Definition at line 118 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c011 = -2.34727734620e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c012
real (r8), parameter gsw_mod_specvol_coefficients::c012 = -1.09581019659e-6_r8
Definition at line 119 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c012 = -1.09581019659e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c013
real (r8), parameter gsw_mod_specvol_coefficients::c013 = 1.25816399608e-6_r8
Definition at line 120 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c013 =  1.25816399608e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c020
real (r8), parameter gsw_mod_specvol_coefficients::c020 = -1.17166068530e-5_r8
Definition at line 121 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c020 = -1.17166068530e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c021
real (r8), parameter gsw_mod_specvol_coefficients::c021 = 4.26100574800e-6_r8
Definition at line 122 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c021 =  4.26100574800e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c022
real (r8), parameter gsw_mod_specvol_coefficients::c022 = 8.60877154770e-7_r8
Definition at line 123 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c022 =  8.60877154770e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c030
real (r8), parameter gsw_mod_specvol_coefficients::c030 = 7.92796561730e-6_r8
Definition at line 124 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c030 =  7.92796561730e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c031
real (r8), parameter gsw_mod_specvol_coefficients::c031 = -9.22650800740e-7_r8
Definition at line 125 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c031 = -9.22650800740e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c040
real (r8), parameter gsw_mod_specvol_coefficients::c040 = -3.41021874820e-6_r8
Definition at line 126 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c040 = -3.41021874820e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c041
real (r8), parameter gsw_mod_specvol_coefficients::c041 = -1.26705833028e-7_r8
Definition at line 127 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c041 = -1.26705833028e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c050
real (r8), parameter gsw_mod_specvol_coefficients::c050 = 5.07367668140e-7_r8
Definition at line 128 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c050 =  5.07367668140e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c100
real (r8), parameter gsw_mod_specvol_coefficients::c100 = 2.42624687470e-5_r8
Definition at line 129 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c100 =  2.42624687470e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c101
real (r8), parameter gsw_mod_specvol_coefficients::c101 = -1.16968865968e-6_r8
Definition at line 130 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c101 = -1.16968865968e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c102
real (r8), parameter gsw_mod_specvol_coefficients::c102 = 1.08930565545e-6_r8
Definition at line 131 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c102 =  1.08930565545e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c103
real (r8), parameter gsw_mod_specvol_coefficients::c103 = -4.45885016920e-7_r8
Definition at line 132 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c103 = -4.45885016920e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c110
real (r8), parameter gsw_mod_specvol_coefficients::c110 = -9.56770881560e-6_r8
Definition at line 133 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c110 = -9.56770881560e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c111
real (r8), parameter gsw_mod_specvol_coefficients::c111 = -1.11398309114e-5_r8
Definition at line 134 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c111 = -1.11398309114e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c112
real (r8), parameter gsw_mod_specvol_coefficients::c112 = -8.18870887110e-7_r8
Definition at line 135 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c112 = -8.18870887110e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c120
real (r8), parameter gsw_mod_specvol_coefficients::c120 = -2.36783083610e-7_r8
Definition at line 136 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c120 = -2.36783083610e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c121
real (r8), parameter gsw_mod_specvol_coefficients::c121 = 7.82747741600e-7_r8
Definition at line 137 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c121 =  7.82747741600e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c130
real (r8), parameter gsw_mod_specvol_coefficients::c130 = -3.45587736550e-6_r8
Definition at line 138 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c130 = -3.45587736550e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c131
real (r8), parameter gsw_mod_specvol_coefficients::c131 = 1.55237776184e-8_r8
Definition at line 139 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c131 =  1.55237776184e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c140
real (r8), parameter gsw_mod_specvol_coefficients::c140 = 1.29567177830e-6_r8
Definition at line 140 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c140 =  1.29567177830e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c200
real (r8), parameter gsw_mod_specvol_coefficients::c200 = -3.47924609740e-5_r8
Definition at line 141 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c200 = -3.47924609740e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c201
real (r8), parameter gsw_mod_specvol_coefficients::c201 = -9.62445031940e-6_r8
Definition at line 142 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c201 = -9.62445031940e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c202
real (r8), parameter gsw_mod_specvol_coefficients::c202 = 5.02389113400e-8_r8
Definition at line 143 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c202 =  5.02389113400e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c210
real (r8), parameter gsw_mod_specvol_coefficients::c210 = 1.11008347650e-5_r8
Definition at line 144 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c210 =  1.11008347650e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c211
real (r8), parameter gsw_mod_specvol_coefficients::c211 = 1.09241497668e-5_r8
Definition at line 145 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c211 =  1.09241497668e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c220
real (r8), parameter gsw_mod_specvol_coefficients::c220 = 2.92833462950e-6_r8
Definition at line 146 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c220 =  2.92833462950e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c221
real (r8), parameter gsw_mod_specvol_coefficients::c221 = -1.31462208134e-6_r8
Definition at line 147 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c221 = -1.31462208134e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c230
real (r8), parameter gsw_mod_specvol_coefficients::c230 = 3.16553060780e-7_r8
Definition at line 148 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c230 =  3.16553060780e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c300
real (r8), parameter gsw_mod_specvol_coefficients::c300 = 3.74707773050e-5_r8
Definition at line 149 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c300 =  3.74707773050e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c301
real (r8), parameter gsw_mod_specvol_coefficients::c301 = 9.85262139960e-6_r8
Definition at line 150 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c301 =  9.85262139960e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c310
real (r8), parameter gsw_mod_specvol_coefficients::c310 = -9.84471178440e-6_r8
Definition at line 151 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c310 = -9.84471178440e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c311
real (r8), parameter gsw_mod_specvol_coefficients::c311 = -2.70883712540e-6_r8
Definition at line 152 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c311 = -2.70883712540e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c320
real (r8), parameter gsw_mod_specvol_coefficients::c320 = -4.88261392000e-7_r8
Definition at line 153 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c320 = -4.88261392000e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c400
real (r8), parameter gsw_mod_specvol_coefficients::c400 = -1.73222186120e-5_r8
Definition at line 154 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c400 = -1.73222186120e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c401
real (r8), parameter gsw_mod_specvol_coefficients::c401 = -3.56239494540e-6_r8
Definition at line 155 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c401 = -3.56239494540e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c410
real (r8), parameter gsw_mod_specvol_coefficients::c410 = 2.59092252600e-6_r8
Definition at line 156 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c410 =  2.59092252600e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
c500
real (r8), parameter gsw_mod_specvol_coefficients::c500 = 3.09274272530e-6_r8
Definition at line 157 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: c500 =  3.09274272530e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol_first_derivatives().
h001
real (r8), parameter gsw_mod_specvol_coefficients::h001 = 1.07699958620e-3_r8
Definition at line 159 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h001 =  1.07699958620e-3_r8
h002
real (r8), parameter gsw_mod_specvol_coefficients::h002 = -3.03995719050e-5_r8
Definition at line 160 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h002 = -3.03995719050e-5_r8
h003
real (r8), parameter gsw_mod_specvol_coefficients::h003 = 3.32853897400e-6_r8
Definition at line 161 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h003 =  3.32853897400e-6_r8
h004
real (r8), parameter gsw_mod_specvol_coefficients::h004 = -2.82734035930e-7_r8
Definition at line 162 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h004 = -2.82734035930e-7_r8
h005
real (r8), parameter gsw_mod_specvol_coefficients::h005 = 2.10623061600e-8_r8
Definition at line 163 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h005 =  2.10623061600e-8_r8
h006
real (r8), parameter gsw_mod_specvol_coefficients::h006 = -2.10787688100e-9_r8
Definition at line 164 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h006 = -2.10787688100e-9_r8
h007
real (r8), parameter gsw_mod_specvol_coefficients::h007 = 2.80192913290e-10_r8
Definition at line 165 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h007 =  2.80192913290e-10_r8
h011
real (r8), parameter gsw_mod_specvol_coefficients::h011 = -1.56497346750e-5_r8
Definition at line 166 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h011 = -1.56497346750e-5_r8
h012
real (r8), parameter gsw_mod_specvol_coefficients::h012 = 9.25288271450e-6_r8
Definition at line 167 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h012 =  9.25288271450e-6_r8
h013
real (r8), parameter gsw_mod_specvol_coefficients::h013 = -3.91212891030e-7_r8
Definition at line 168 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h013 = -3.91212891030e-7_r8
h014
real (r8), parameter gsw_mod_specvol_coefficients::h014 = -9.13175163830e-8_r8
Definition at line 169 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h014 = -9.13175163830e-8_r8
h015
real (r8), parameter gsw_mod_specvol_coefficients::h015 = 6.29081998040e-8_r8
Definition at line 170 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h015 =  6.29081998040e-8_r8
h021
real (r8), parameter gsw_mod_specvol_coefficients::h021 = 2.77621064840e-5_r8
Definition at line 171 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h021 =  2.77621064840e-5_r8
h022
real (r8), parameter gsw_mod_specvol_coefficients::h022 = -5.85830342650e-6_r8
Definition at line 172 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h022 = -5.85830342650e-6_r8
h023
real (r8), parameter gsw_mod_specvol_coefficients::h023 = 7.10167624670e-7_r8
Definition at line 173 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h023 =  7.10167624670e-7_r8
h024
real (r8), parameter gsw_mod_specvol_coefficients::h024 = 7.17397628980e-8_r8
Definition at line 174 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h024 =  7.17397628980e-8_r8
h031
real (r8), parameter gsw_mod_specvol_coefficients::h031 = -1.65211592590e-5_r8
Definition at line 175 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h031 = -1.65211592590e-5_r8
h032
real (r8), parameter gsw_mod_specvol_coefficients::h032 = 3.96398280870e-6_r8
Definition at line 176 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h032 =  3.96398280870e-6_r8
h033
real (r8), parameter gsw_mod_specvol_coefficients::h033 = -1.53775133460e-7_r8
Definition at line 177 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h033 = -1.53775133460e-7_r8
h041
real (r8), parameter gsw_mod_specvol_coefficients::h041 = 6.91113227020e-6_r8
Definition at line 180 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h041 =  6.91113227020e-6_r8
h042
real (r8), parameter gsw_mod_specvol_coefficients::h042 = -1.70510937410e-6_r8
Definition at line 178 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h042 = -1.70510937410e-6_r8
h043
real (r8), parameter gsw_mod_specvol_coefficients::h043 = -2.11176388380e-8_r8
Definition at line 179 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h043 = -2.11176388380e-8_r8
h051
real (r8), parameter gsw_mod_specvol_coefficients::h051 = -8.05396155400e-7_r8
Definition at line 181 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h051 = -8.05396155400e-7_r8
h052
real (r8), parameter gsw_mod_specvol_coefficients::h052 = 2.53683834070e-7_r8
Definition at line 182 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h052 =  2.53683834070e-7_r8
h061
real (r8), parameter gsw_mod_specvol_coefficients::h061 = 2.05430942680e-7_r8
Definition at line 183 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h061 =  2.05430942680e-7_r8
h101
real (r8), parameter gsw_mod_specvol_coefficients::h101 = -3.10389819760e-4_r8
Definition at line 184 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h101 = -3.10389819760e-4_r8
h102
real (r8), parameter gsw_mod_specvol_coefficients::h102 = 1.21312343735e-5_r8
Definition at line 185 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h102 =  1.21312343735e-5_r8
h103
real (r8), parameter gsw_mod_specvol_coefficients::h103 = -1.94948109950e-7_r8
Definition at line 186 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h103 = -1.94948109950e-7_r8
h104
real (r8), parameter gsw_mod_specvol_coefficients::h104 = 9.07754712880e-8_r8
Definition at line 187 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h104 =  9.07754712880e-8_r8
h105
real (r8), parameter gsw_mod_specvol_coefficients::h105 = -2.22942508460e-8_r8
Definition at line 188 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h105 = -2.22942508460e-8_r8
h111
real (r8), parameter gsw_mod_specvol_coefficients::h111 = 3.50095997640e-5_r8
Definition at line 189 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h111 =  3.50095997640e-5_r8
h112
real (r8), parameter gsw_mod_specvol_coefficients::h112 = -4.78385440780e-6_r8
Definition at line 190 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h112 = -4.78385440780e-6_r8
h113
real (r8), parameter gsw_mod_specvol_coefficients::h113 = -1.85663848520e-6_r8
Definition at line 191 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h113 = -1.85663848520e-6_r8
h114
real (r8), parameter gsw_mod_specvol_coefficients::h114 = -6.82392405930e-8_r8
Definition at line 192 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h114 = -6.82392405930e-8_r8
h121
real (r8), parameter gsw_mod_specvol_coefficients::h121 = -3.74358423440e-5_r8
Definition at line 193 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h121 = -3.74358423440e-5_r8
h122
real (r8), parameter gsw_mod_specvol_coefficients::h122 = -1.18391541805e-7_r8
Definition at line 194 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h122 = -1.18391541805e-7_r8
h123
real (r8), parameter gsw_mod_specvol_coefficients::h123 = 1.30457956930e-7_r8
Definition at line 195 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h123 =  1.30457956930e-7_r8
h131
real (r8), parameter gsw_mod_specvol_coefficients::h131 = 2.41414794830e-5_r8
Definition at line 196 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h131 =  2.41414794830e-5_r8
h132
real (r8), parameter gsw_mod_specvol_coefficients::h132 = -1.72793868275e-6_r8
Definition at line 197 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h132 = -1.72793868275e-6_r8
h133
real (r8), parameter gsw_mod_specvol_coefficients::h133 = 2.58729626970e-9_r8
Definition at line 198 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h133 =  2.58729626970e-9_r8
h141
real (r8), parameter gsw_mod_specvol_coefficients::h141 = -8.75958731540e-6_r8
Definition at line 199 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h141 = -8.75958731540e-6_r8
h142
real (r8), parameter gsw_mod_specvol_coefficients::h142 = 6.47835889150e-7_r8
Definition at line 200 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h142 =  6.47835889150e-7_r8
h151
real (r8), parameter gsw_mod_specvol_coefficients::h151 = -3.30527589000e-7_r8
Definition at line 201 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h151 = -3.30527589000e-7_r8
h201
real (r8), parameter gsw_mod_specvol_coefficients::h201 = 6.69280670380e-4_r8
Definition at line 202 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h201 =  6.69280670380e-4_r8
h202
real (r8), parameter gsw_mod_specvol_coefficients::h202 = -1.73962304870e-5_r8
Definition at line 203 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h202 = -1.73962304870e-5_r8
h203
real (r8), parameter gsw_mod_specvol_coefficients::h203 = -1.60407505320e-6_r8
Definition at line 204 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h203 = -1.60407505320e-6_r8
h204
real (r8), parameter gsw_mod_specvol_coefficients::h204 = 4.18657594500e-9_r8
Definition at line 205 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h204 =  4.18657594500e-9_r8
h211
real (r8), parameter gsw_mod_specvol_coefficients::h211 = -4.35926785610e-5_r8
Definition at line 206 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h211 = -4.35926785610e-5_r8
h212
real (r8), parameter gsw_mod_specvol_coefficients::h212 = 5.55041738250e-6_r8
Definition at line 207 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h212 =  5.55041738250e-6_r8
h213
real (r8), parameter gsw_mod_specvol_coefficients::h213 = 1.82069162780e-6_r8
Definition at line 208 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h213 =  1.82069162780e-6_r8
h221
real (r8), parameter gsw_mod_specvol_coefficients::h221 = 3.59078227600e-5_r8
Definition at line 209 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h221 =  3.59078227600e-5_r8
h222
real (r8), parameter gsw_mod_specvol_coefficients::h222 = 1.46416731475e-6_r8
Definition at line 210 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h222 =  1.46416731475e-6_r8
h223
real (r8), parameter gsw_mod_specvol_coefficients::h223 = -2.19103680220e-7_r8
Definition at line 211 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h223 = -2.19103680220e-7_r8
h231
real (r8), parameter gsw_mod_specvol_coefficients::h231 = -1.43536330480e-5_r8
Definition at line 212 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h231 = -1.43536330480e-5_r8
h232
real (r8), parameter gsw_mod_specvol_coefficients::h232 = 1.58276530390e-7_r8
Definition at line 213 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h232 =  1.58276530390e-7_r8
h241
real (r8), parameter gsw_mod_specvol_coefficients::h241 = 4.37036805980e-6_r8
Definition at line 214 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h241 =  4.37036805980e-6_r8
h301
real (r8), parameter gsw_mod_specvol_coefficients::h301 = -8.50479339370e-4_r8
Definition at line 215 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h301 = -8.50479339370e-4_r8
h302
real (r8), parameter gsw_mod_specvol_coefficients::h302 = 1.87353886525e-5_r8
Definition at line 216 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h302 =  1.87353886525e-5_r8
h303
real (r8), parameter gsw_mod_specvol_coefficients::h303 = 1.64210356660e-6_r8
Definition at line 217 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h303 =  1.64210356660e-6_r8
h311
real (r8), parameter gsw_mod_specvol_coefficients::h311 = 3.45324618280e-5_r8
Definition at line 218 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h311 =  3.45324618280e-5_r8
h312
real (r8), parameter gsw_mod_specvol_coefficients::h312 = -4.92235589220e-6_r8
Definition at line 219 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h312 = -4.92235589220e-6_r8
h313
real (r8), parameter gsw_mod_specvol_coefficients::h313 = -4.51472854230e-7_r8
Definition at line 220 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h313 = -4.51472854230e-7_r8
h321
real (r8), parameter gsw_mod_specvol_coefficients::h321 = -1.86985841870e-5_r8
Definition at line 221 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h321 = -1.86985841870e-5_r8
h322
real (r8), parameter gsw_mod_specvol_coefficients::h322 = -2.44130696000e-7_r8
Definition at line 222 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h322 = -2.44130696000e-7_r8
h331
real (r8), parameter gsw_mod_specvol_coefficients::h331 = 2.28633245560e-6_r8
Definition at line 223 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h331 =  2.28633245560e-6_r8
h401
real (r8), parameter gsw_mod_specvol_coefficients::h401 = 5.80860699430e-4_r8
Definition at line 224 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h401 =  5.80860699430e-4_r8
h402
real (r8), parameter gsw_mod_specvol_coefficients::h402 = -8.66110930600e-6_r8
Definition at line 225 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h402 = -8.66110930600e-6_r8
h403
real (r8), parameter gsw_mod_specvol_coefficients::h403 = -5.93732490900e-7_r8
Definition at line 226 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h403 = -5.93732490900e-7_r8
h411
real (r8), parameter gsw_mod_specvol_coefficients::h411 = -1.19594097880e-5_r8
Definition at line 227 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h411 = -1.19594097880e-5_r8
h412
real (r8), parameter gsw_mod_specvol_coefficients::h412 = 1.29546126300e-6_r8
Definition at line 229 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h412 =  1.29546126300e-6_r8
h421
real (r8), parameter gsw_mod_specvol_coefficients::h421 = 3.85953392440e-6_r8
Definition at line 228 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h421 =  3.85953392440e-6_r8
h501
real (r8), parameter gsw_mod_specvol_coefficients::h501 = -2.10923705070e-4_r8
Definition at line 230 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h501 = -2.10923705070e-4_r8
h502
real (r8), parameter gsw_mod_specvol_coefficients::h502 = 1.54637136265e-6_r8
Definition at line 231 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h502 =  1.54637136265e-6_r8
h511
real (r8), parameter gsw_mod_specvol_coefficients::h511 = 1.38645945810e-6_r8
Definition at line 232 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h511 =  1.38645945810e-6_r8
h601
real (r8), parameter gsw_mod_specvol_coefficients::h601 = 3.19324573050e-5_r8
Definition at line 233 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: h601 =  3.19324573050e-5_r8
v000
real (r8), parameter gsw_mod_specvol_coefficients::v000 = 1.0769995862e-3_r8
Definition at line 235 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v000 =  1.0769995862e-3_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v001
real (r8), parameter gsw_mod_specvol_coefficients::v001 = -6.0799143809e-5_r8
Definition at line 236 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v001 = -6.0799143809e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v002
real (r8), parameter gsw_mod_specvol_coefficients::v002 = 9.9856169219e-6_r8
Definition at line 237 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v002 =  9.9856169219e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v003
real (r8), parameter gsw_mod_specvol_coefficients::v003 = -1.1309361437e-6_r8
Definition at line 238 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v003 = -1.1309361437e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v004
real (r8), parameter gsw_mod_specvol_coefficients::v004 = 1.0531153080e-7_r8
Definition at line 239 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v004 =  1.0531153080e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v005
real (r8), parameter gsw_mod_specvol_coefficients::v005 = -1.2647261286e-8_r8
Definition at line 240 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v005 = -1.2647261286e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v006
real (r8), parameter gsw_mod_specvol_coefficients::v006 = 1.9613503930e-9_r8
Definition at line 241 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v006 =  1.9613503930e-9_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v010
real (r8), parameter gsw_mod_specvol_coefficients::v010 = -3.1038981976e-4_r8
Definition at line 242 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v010 = -3.1038981976e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v011
real (r8), parameter gsw_mod_specvol_coefficients::v011 = 2.4262468747e-5_r8
Definition at line 243 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v011 =  2.4262468747e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v012
real (r8), parameter gsw_mod_specvol_coefficients::v012 = -5.8484432984e-7_r8
Definition at line 244 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v012 = -5.8484432984e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v013
real (r8), parameter gsw_mod_specvol_coefficients::v013 = 3.6310188515e-7_r8
Definition at line 245 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v013 =  3.6310188515e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v014
real (r8), parameter gsw_mod_specvol_coefficients::v014 = -1.1147125423e-7_r8
Definition at line 246 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v014 = -1.1147125423e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v020
real (r8), parameter gsw_mod_specvol_coefficients::v020 = 6.6928067038e-4_r8
Definition at line 247 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v020 =  6.6928067038e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v021
real (r8), parameter gsw_mod_specvol_coefficients::v021 = -3.4792460974e-5_r8
Definition at line 248 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v021 = -3.4792460974e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v022
real (r8), parameter gsw_mod_specvol_coefficients::v022 = -4.8122251597e-6_r8
Definition at line 249 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v022 = -4.8122251597e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v023
real (r8), parameter gsw_mod_specvol_coefficients::v023 = 1.6746303780e-8_r8
Definition at line 250 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v023 =  1.6746303780e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v030
real (r8), parameter gsw_mod_specvol_coefficients::v030 = -8.5047933937e-4_r8
Definition at line 251 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v030 = -8.5047933937e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v031
real (r8), parameter gsw_mod_specvol_coefficients::v031 = 3.7470777305e-5_r8
Definition at line 252 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v031 =  3.7470777305e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v032
real (r8), parameter gsw_mod_specvol_coefficients::v032 = 4.9263106998e-6_r8
Definition at line 253 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v032 =  4.9263106998e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v040
real (r8), parameter gsw_mod_specvol_coefficients::v040 = 5.8086069943e-4_r8
Definition at line 254 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v040 =  5.8086069943e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v041
real (r8), parameter gsw_mod_specvol_coefficients::v041 = -1.7322218612e-5_r8
Definition at line 255 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v041 = -1.7322218612e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v042
real (r8), parameter gsw_mod_specvol_coefficients::v042 = -1.7811974727e-6_r8
Definition at line 256 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v042 = -1.7811974727e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v050
real (r8), parameter gsw_mod_specvol_coefficients::v050 = -2.1092370507e-4_r8
Definition at line 257 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v050 = -2.1092370507e-4_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v051
real (r8), parameter gsw_mod_specvol_coefficients::v051 = 3.0927427253e-6_r8
Definition at line 258 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v051 =  3.0927427253e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v060
real (r8), parameter gsw_mod_specvol_coefficients::v060 = 3.1932457305e-5_r8
Definition at line 259 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v060 =  3.1932457305e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v100
real (r8), parameter gsw_mod_specvol_coefficients::v100 = -1.5649734675e-5_r8
Definition at line 260 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v100 = -1.5649734675e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v101
real (r8), parameter gsw_mod_specvol_coefficients::v101 = 1.8505765429e-5_r8
Definition at line 261 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v101 =  1.8505765429e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v102
real (r8), parameter gsw_mod_specvol_coefficients::v102 = -1.1736386731e-6_r8
Definition at line 262 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v102 = -1.1736386731e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v103
real (r8), parameter gsw_mod_specvol_coefficients::v103 = -3.6527006553e-7_r8
Definition at line 263 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v103 = -3.6527006553e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v104
real (r8), parameter gsw_mod_specvol_coefficients::v104 = 3.1454099902e-7_r8
Definition at line 264 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v104 =  3.1454099902e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v110
real (r8), parameter gsw_mod_specvol_coefficients::v110 = 3.5009599764e-5_r8
Definition at line 265 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v110 =  3.5009599764e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v111
real (r8), parameter gsw_mod_specvol_coefficients::v111 = -9.5677088156e-6_r8
Definition at line 266 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v111 = -9.5677088156e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v112
real (r8), parameter gsw_mod_specvol_coefficients::v112 = -5.5699154557e-6_r8
Definition at line 267 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v112 = -5.5699154557e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v113
real (r8), parameter gsw_mod_specvol_coefficients::v113 = -2.7295696237e-7_r8
Definition at line 268 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v113 = -2.7295696237e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v120
real (r8), parameter gsw_mod_specvol_coefficients::v120 = -4.3592678561e-5_r8
Definition at line 269 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v120 = -4.3592678561e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v121
real (r8), parameter gsw_mod_specvol_coefficients::v121 = 1.1100834765e-5_r8
Definition at line 270 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v121 =  1.1100834765e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v122
real (r8), parameter gsw_mod_specvol_coefficients::v122 = 5.4620748834e-6_r8
Definition at line 271 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v122 =  5.4620748834e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v130
real (r8), parameter gsw_mod_specvol_coefficients::v130 = 3.4532461828e-5_r8
Definition at line 272 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v130 =  3.4532461828e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v131
real (r8), parameter gsw_mod_specvol_coefficients::v131 = -9.8447117844e-6_r8
Definition at line 273 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v131 = -9.8447117844e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v132
real (r8), parameter gsw_mod_specvol_coefficients::v132 = -1.3544185627e-6_r8
Definition at line 274 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v132 = -1.3544185627e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v140
real (r8), parameter gsw_mod_specvol_coefficients::v140 = -1.1959409788e-5_r8
Definition at line 275 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v140 = -1.1959409788e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v141
real (r8), parameter gsw_mod_specvol_coefficients::v141 = 2.5909225260e-6_r8
Definition at line 276 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v141 =  2.5909225260e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v150
real (r8), parameter gsw_mod_specvol_coefficients::v150 = 1.3864594581e-6_r8
Definition at line 277 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v150 =  1.3864594581e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v200
real (r8), parameter gsw_mod_specvol_coefficients::v200 = 2.7762106484e-5_r8
Definition at line 278 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v200 =  2.7762106484e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v201
real (r8), parameter gsw_mod_specvol_coefficients::v201 = -1.1716606853e-5_r8
Definition at line 279 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v201 = -1.1716606853e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v202
real (r8), parameter gsw_mod_specvol_coefficients::v202 = 2.1305028740e-6_r8
Definition at line 280 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v202 =  2.1305028740e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v203
real (r8), parameter gsw_mod_specvol_coefficients::v203 = 2.8695905159e-7_r8
Definition at line 281 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v203 =  2.8695905159e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v210
real (r8), parameter gsw_mod_specvol_coefficients::v210 = -3.7435842344e-5_r8
Definition at line 282 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v210 = -3.7435842344e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v211
real (r8), parameter gsw_mod_specvol_coefficients::v211 = -2.3678308361e-7_r8
Definition at line 283 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v211 = -2.3678308361e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v212
real (r8), parameter gsw_mod_specvol_coefficients::v212 = 3.9137387080e-7_r8
Definition at line 284 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v212 =  3.9137387080e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v220
real (r8), parameter gsw_mod_specvol_coefficients::v220 = 3.5907822760e-5_r8
Definition at line 285 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v220 =  3.5907822760e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v221
real (r8), parameter gsw_mod_specvol_coefficients::v221 = 2.9283346295e-6_r8
Definition at line 286 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v221 =  2.9283346295e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v222
real (r8), parameter gsw_mod_specvol_coefficients::v222 = -6.5731104067e-7_r8
Definition at line 287 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v222 = -6.5731104067e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v230
real (r8), parameter gsw_mod_specvol_coefficients::v230 = -1.8698584187e-5_r8
Definition at line 288 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v230 = -1.8698584187e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v231
real (r8), parameter gsw_mod_specvol_coefficients::v231 = -4.8826139200e-7_r8
Definition at line 289 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v231 = -4.8826139200e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v240
real (r8), parameter gsw_mod_specvol_coefficients::v240 = 3.8595339244e-6_r8
Definition at line 290 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v240 =  3.8595339244e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v300
real (r8), parameter gsw_mod_specvol_coefficients::v300 = -1.6521159259e-5_r8
Definition at line 291 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v300 = -1.6521159259e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v301
real (r8), parameter gsw_mod_specvol_coefficients::v301 = 7.9279656173e-6_r8
Definition at line 292 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v301 =  7.9279656173e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v302
real (r8), parameter gsw_mod_specvol_coefficients::v302 = -4.6132540037e-7_r8
Definition at line 293 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v302 = -4.6132540037e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v310
real (r8), parameter gsw_mod_specvol_coefficients::v310 = 2.4141479483e-5_r8
Definition at line 294 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v310 =  2.4141479483e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v311
real (r8), parameter gsw_mod_specvol_coefficients::v311 = -3.4558773655e-6_r8
Definition at line 295 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v311 = -3.4558773655e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v312
real (r8), parameter gsw_mod_specvol_coefficients::v312 = 7.7618888092e-9_r8
Definition at line 296 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v312 =  7.7618888092e-9_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v320
real (r8), parameter gsw_mod_specvol_coefficients::v320 = -1.4353633048e-5_r8
Definition at line 297 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v320 = -1.4353633048e-5_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v321
real (r8), parameter gsw_mod_specvol_coefficients::v321 = 3.1655306078e-7_r8
Definition at line 298 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v321 =  3.1655306078e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v330
real (r8), parameter gsw_mod_specvol_coefficients::v330 = 2.2863324556e-6_r8
Definition at line 299 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v330 =  2.2863324556e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v400
real (r8), parameter gsw_mod_specvol_coefficients::v400 = 6.9111322702e-6_r8
Definition at line 300 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v400 =  6.9111322702e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v401
real (r8), parameter gsw_mod_specvol_coefficients::v401 = -3.4102187482e-6_r8
Definition at line 301 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v401 = -3.4102187482e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v402
real (r8), parameter gsw_mod_specvol_coefficients::v402 = -6.3352916514e-8_r8
Definition at line 302 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v402 = -6.3352916514e-8_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v410
real (r8), parameter gsw_mod_specvol_coefficients::v410 = -8.7595873154e-6_r8
Definition at line 303 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v410 = -8.7595873154e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v411
real (r8), parameter gsw_mod_specvol_coefficients::v411 = 1.2956717783e-6_r8
Definition at line 304 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v411 =  1.2956717783e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v420
real (r8), parameter gsw_mod_specvol_coefficients::v420 = 4.3703680598e-6_r8
Definition at line 305 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v420 =  4.3703680598e-6_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v500
real (r8), parameter gsw_mod_specvol_coefficients::v500 = -8.0539615540e-7_r8
Definition at line 306 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v500 = -8.0539615540e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v501
real (r8), parameter gsw_mod_specvol_coefficients::v501 = 5.0736766814e-7_r8
Definition at line 307 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v501 =  5.0736766814e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v510
real (r8), parameter gsw_mod_specvol_coefficients::v510 = -3.3052758900e-7_r8
Definition at line 308 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v510 = -3.3052758900e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().
v600
real (r8), parameter gsw_mod_specvol_coefficients::v600 = 2.0543094268e-7_r8
Definition at line 309 of file gsw_mod_specvol_coefficients.f90.
 real(r8), parameter :: v600 =  2.0543094268e-7_r8
Referenced by gsw_rho_first_derivatives(), and gsw_specvol().