MOM6: mom_boundary_update Module Reference
mom_boundary_update Module Reference
Controls where open boundary conditions are applied.
Functions/Subroutines
subroutine, public update_obc_data (OBC, G, h, Time)
Calls appropriate routine to update the open boundary conditions.
Variables
integer id_clock_pass
character(len=40) mod = "MOM_boundary_update"
Detailed Description
Controls where open boundary conditions are applied.
This module updates the open boundary arrays when time-varying. It caused a circular dependency with the tidal_bay setup when MOM_open_boundary.
A small fragment of the grid is shown below:
j+1 x ^ x ^ x At x: q, CoriolisBu j+1 > o > o > At ^: v, tauy j x ^ x ^ x At >: u, taux j > o > o > At o: h, bathyT, buoy, tr, T, S, Rml, ustar j-1 x ^ x ^ x i-1 i i+1 At x & ^: i i+1 At > & o:
The boundaries always run through q grid points (x).
Function/Subroutine Documentation
update_obc_data()
subroutine, public mom_boundary_update::update_obc_data (type(ocean_obc_type), pointer OBC, type(ocean_grid_type), intent(in) G, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, type(time_type), intent(in) Time)
Calls appropriate routine to update the open boundary conditions.
Parameters
[in] g Ocean grid structure
[in,out] h layer thickness
obc Open boundary structure
[in] time Model time
Definition at line 38 of file MOM_boundary_update.F90.
   type(ocean_grid_type),          intent(in) :: G !< Ocean grid structure
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(inout) :: h !< layer thickness
   type(ocean_OBC_type),           pointer    :: OBC !< Open boundary structure
   type(time_type),                intent(in) :: Time !< Model time
   ! Local variables
   logical :: read_OBC_eta = .false.
   logical :: read_OBC_uv = .false.
   logical :: read_OBC_TS = .false.
   integer :: i, j, k, itt, is, ie, js, je, isd, ied, jsd, jed, nz
   integer :: isd_off, jsd_off
   integer :: IsdB, IedB, JsdB, JedB
   character(len=40)  :: mod = "update_OBC_data" ! This subroutine's name.
   character(len=200) :: filename, OBC_file, inputdir ! Strings for file/path
   real :: temp_u(G%domain%niglobal+1,G%domain%njglobal)
   real :: temp_v(G%domain%niglobal,G%domain%njglobal+1)
   real, pointer, dimension(:,:,:) :: &
     OBC_T_u => null(), &    ! These arrays should be allocated and set to
     obc_t_v => null(), &    ! specify the values of T and S that should come
     obc_s_u => null(), &
     obc_s_v => null()
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   isd = g%isd ; ied = g%ied ; jsd = g%jsd ; jed = g%jed
   isdb = g%IsdB ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   if (obc%OBC_values_config == "tidal_bay") then
     call tidal_bay_set_obc_data(obc, g, h, time)
   endif
References tidal_bay_initialization::tidal_bay_set_obc_data().
Referenced by mom_dynamics_legacy_split::step_mom_dyn_legacy_split(), mom_dynamics_split_rk2::step_mom_dyn_split_rk2(), mom_dynamics_unsplit::step_mom_dyn_unsplit(), and mom_dynamics_unsplit_rk2::step_mom_dyn_unsplit_rk2().
Variable Documentation
id_clock_pass
integer mom_boundary_update::id_clock_pass private
Definition at line 28 of file MOM_boundary_update.F90.
 integer :: id_clock_pass
mod
character(len=40) mom_boundary_update::mod = "MOM_boundary_update" private
Definition at line 30 of file MOM_boundary_update.F90.
 character(len=40)  :: mod = "MOM_boundary_update" ! This module's name.