MOM6: baroclinic_zone_initialization Module Reference
baroclinic_zone_initialization Module Reference
Initial conditions for an idealized baroclinic zone.
Functions/Subroutines
subroutine bcz_params (G, param_file, S_ref, dSdz, delta_S, dSdx, T_ref, dTdz, delta_T, dTdx, L_zone)
Reads the parameters unique to this module.
subroutine, public baroclinic_zone_init_temperature_salinity (T, S, h, G, param_file)
Initialization of temperature and salinity with the baroclinic zone initial conditions.
Variables
character(len=40) mod = "baroclinic_zone_initialization"
This module's name.
Detailed Description
Initial conditions for an idealized baroclinic zone.
Description of the baroclinic zone initial conditions
yada yada yada
Function/Subroutine Documentation
baroclinic_zone_init_temperature_salinity()
subroutine, public baroclinic_zone_initialization::baroclinic_zone_init_temperature_salinity (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) T, real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) S, real, dimension(szi_(g),szj_(g), szk_(g)), intent(in) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
Initialization of temperature and salinity with the baroclinic zone initial conditions.
Parameters
[in] g Grid structure
[out] t Potential temperature [deg C]
[out] s Salinity [ppt]
[in] h Thickness
[in] param_file Parameter file handle
Definition at line 53 of file baroclinic_zone_initialization.F90.
   type(ocean_grid_type),                     intent(in)  :: G  !< Grid structure
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: T  !< Potential temperature [deg C]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: S  !< Salinity [ppt]
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(in)  :: h  !< Thickness
   type(param_file_type),                     intent(in)  :: param_file  !< Parameter file handle
   integer   :: i, j, k, is, ie, js, je, nz
   real      :: T_ref, dTdz, dTdx, delta_T ! Parameters describing temperature distribution
   real      :: S_ref, dSdz, dSdx, delta_S ! Parameters describing salinity distribution
   real      :: L_zone ! Width of baroclinic zone
   real      :: zc, zi, x, xd, xs, y, yd, fn
   real      :: PI                   ! 3.1415926... calculated as 4*atan(1)
   is = g%isc ; ie = g%iec ; js = g%jsc ; je = g%jec ; nz = g%ke
   call bcz_params(g, param_file, s_ref, dsdz, delta_s, dsdx, t_ref, dtdz, delta_t, dtdx, l_zone)
   t(:,:,:) = 0.
   s(:,:,:) = 0.
   pi = 4.*atan(1.)
   do j = g%jsc,g%jec ; do i = g%isc,g%iec
     zi = -g%bathyT(i,j)
     x = g%geoLonT(i,j) - (g%west_lon + 0.5*g%len_lon) ! Relative to center of domain
     xd = x / g%len_lon ! -1/2 < xd 1/2
     y = g%geoLatT(i,j) - (g%south_lat + 0.5*g%len_lat) ! Relative to center of domain
     yd = y / g%len_lat ! -1/2 < yd 1/2
     if (l_zone/=0.) then
       xs = min(1., max(-1., x/l_zone)) ! -1 < ys < 1
       fn = sin((0.5*pi)*xs)
     else
       xs = sign(1., x) ! +/- 1
       fn = xs
     endif
     do k = nz, 1, -1
       zc = zi + 0.5*h(i,j,k)          ! Position of middle of cell
       zi = zi + h(i,j,k)              ! Top interface position
       t(i,j,k) = t_ref + dtdz * zc  & ! Linear temperature stratification
                  + dtdx * x         & ! Linear gradient
                  + delta_t * fn       ! Smooth fn of width L_zone
       s(i,j,k) = s_ref + dsdz * zc  & ! Linear temperature stratification
                  + dsdx * x         & ! Linear gradient
                  + delta_s * fn       ! Smooth fn of width L_zone
     enddo
   end do ; end do
References bcz_params().
Referenced by mom_state_initialization::mom_initialize_state().
bcz_params()
subroutine baroclinic_zone_initialization::bcz_params (type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(out) S_ref, real, intent(out) dSdz, real, intent(out) delta_S, real, intent(out) dSdx, real, intent(out) T_ref, real, intent(out) dTdz, real, intent(out) delta_T, real, intent(out) dTdx, real, intent(out) L_zone) private
Reads the parameters unique to this module.
Parameters
[in] g Grid structure
[in] param_file Parameter file handle
[out] s_ref Reference salinity (ppt)
[out] dsdz Salinity stratification (ppt/m)
[out] delta_s Salinity difference across baroclinic zone (ppt)
[out] dsdx Linear salinity gradient (ppt/m)
[out] t_ref Reference temperature (ppt)
[out] dtdz Temperature stratification (ppt/m)
[out] delta_t Temperature difference across baroclinic zone (ppt)
[out] dtdx Linear temperature gradient (ppt/m)
[out] l_zone Width of baroclinic zone (m)
Definition at line 24 of file baroclinic_zone_initialization.F90.
   type(ocean_grid_type), intent(in)  :: G          !< Grid structure
   type(param_file_type), intent(in)  :: param_file !< Parameter file handle
   real,                  intent(out) :: S_ref      !< Reference salinity (ppt)
   real,                  intent(out) :: dSdz       !< Salinity stratification (ppt/m)
   real,                  intent(out) :: delta_S    !< Salinity difference across baroclinic zone (ppt)
   real,                  intent(out) :: dSdx       !< Linear salinity gradient (ppt/m)
   real,                  intent(out) :: T_ref      !< Reference temperature (ppt)
   real,                  intent(out) :: dTdz       !< Temperature stratification (ppt/m)
   real,                  intent(out) :: delta_T    !< Temperature difference across baroclinic zone (ppt)
   real,                  intent(out) :: dTdx       !< Linear temperature gradient (ppt/m)
   real,                  intent(out) :: L_zone     !< Width of baroclinic zone (m)
   call log_version(param_file, mod, version, 'Initialization of an analytic baroclninic zone')
   call openparameterblock(param_file,'BCZIC')
   call get_param(param_file,mod,"S_REF",s_ref,'Reference salinity',units='ppt',default=35.)
   call get_param(param_file,mod,"DSDZ",dsdz,'Salinity stratification',units='ppt/m',default=0.0)
   call get_param(param_file,mod,"DELTA_S",delta_s,'Salinity difference across baroclinic zone',units='ppt',default=0.0)
   call get_param(param_file,mod,"DSDX",dsdx,'Meridional salinity difference',units='ppt/'//trim(g%x_axis_units),default=0.0)
   call get_param(param_file,mod,"T_REF",t_ref,'Reference temperature',units='C',default=10.)
   call get_param(param_file,mod,"DTDZ",dtdz,'Temperature stratification',units='C/m',default=0.0)
   call get_param(param_file,mod,"DELTA_T",delta_t,'Temperature difference across baroclinic zone',units='C',default=0.0)
   call get_param(param_file,mod,"DTDX",dtdx,'Meridional temperature difference',units='C/'//trim(g%x_axis_units),default=0.0)
   call get_param(param_file,mod,"L_ZONE",l_zone,'Width of baroclinic zone',units=g%x_axis_units,default=0.5*g%len_lat)
   call closeparameterblock(param_file)
References mom_file_parser::closeparameterblock(), mod, and mom_file_parser::openparameterblock().
Referenced by baroclinic_zone_init_temperature_salinity().
Variable Documentation
mod
character(len=40) baroclinic_zone_initialization::mod = "baroclinic_zone_initialization" private
This module's name.
Definition at line 16 of file baroclinic_zone_initialization.F90.
 character(len=40) :: mod = "baroclinic_zone_initialization" !< This module's name.
Referenced by bcz_params().