MOM6: mom_offline_transport Module Reference
mom_offline_transport Module Reference
Contains routines related to offline transport of tracers.
Data Types
type offline_transport_cs
Functions/Subroutines
subroutine, public transport_by_files (G, GV, CS, h_end, eatr, ebtr, uhtr, vhtr, khdt_x, khdt_y, temp, salt, fluxes, do_ale_in)
Controls the reading in 3d mass fluxes, diffusive fluxes, and other fields stored in a previous integration of the online model.
subroutine, public register_diags_offline_transport (Time, diag, CS)
Initialize additional diagnostics required for offline tracer transport.
subroutine, public offline_transport_init (param_file, CS, diabatic_aux_CSp, G, GV)
Initializes the control structure for offline transport and reads in some of the.
integer function next_modulo_time (inidx, numtime)
Calculates the next timelevel to read from the input fields. This allows the 'looping' of the fields.
subroutine, public update_h_horizontal_flux (G, GV, uhtr, vhtr, h_pre, h_new)
This updates thickness based on the convergence of horizontal mass fluxes NOTE: Only used in non-ALE mode.
subroutine, public update_h_vertical_flux (G, GV, ea, eb, h_pre, h_new)
Updates layer thicknesses due to vertical mass transports NOTE: Only used in non-ALE configuration.
subroutine, public limit_mass_flux_3d (G, GV, uh, vh, ea, eb, h_pre, max_off_cfl)
This routine limits the mass fluxes so that the a layer cannot be completely depleted. NOTE: Only used in non-ALE mode.
subroutine, public distribute_residual_uh_barotropic (G, GV, h, uh)
In the case where offline advection has failed to converge, redistribute the u-flux into remainder of the water column as a barotropic equivalent.
subroutine, public distribute_residual_vh_barotropic (G, GV, h, vh)
Redistribute the v-flux as a barotropic equivalent.
subroutine, public distribute_residual_uh_upwards (G, GV, h, uh)
In the case where offline advection has failed to converge, redistribute the u-flux into layers above.
subroutine, public distribute_residual_vh_upwards (G, GV, h, vh)
In the case where offline advection has failed to converge, redistribute the u-flux into layers above.
Detailed Description
Contains routines related to offline transport of tracers.
Offline Tracer Transport in MOM6
'Offline tracer modeling' uses physical fields (e.g. mass transports and layer thicknesses) saved from a previous integration of the physical model to transport passive tracers. These fields are accumulated or averaged over a period of time (in this test case, 1 day) and used to integrate portions of the MOM6 code base that handle the 3d advection and diffusion of passive tracers.
The distribution of tracers in the ocean modeled offline should not be expected to match an online simulation. Accumulating transports over more than one online model timestep implicitly assumes homogeneity over that time period and essentially aliases over processes that occur with higher frequency. For example, consider the case of a surface boundary layer with a strong diurnal cycle. An offline simulation with a 1 day timestep, captures the net transport into or out of that layer, but not the exact cycling. This effective aliasing may also complicate online model configurations which strongly-eddying regions. In this case, the offline model timestep must be limited to some fraction of the eddy correlation timescale. Lastly, the nonlinear advection scheme which applies limited mass-transports over a sequence of iterations means that tracers are not transported along exactly the same path as they are in the online model.
This capability has currently targeted the Baltic_ALE_z test case, though some work has also been done with the OM4 1/2 degree configuration. Work is ongoing to develop recommendations and best practices for investigators seeking to use MOM6 for offline tracer modeling.
Implementation of offline routine in MOM6
The subroutine step_tracers that coordinates this can be found in MOM.F90 and is only called using the solo ocean driver. This is to avoid issues with coupling to other climate components that may be relying on fluxes from the ocean to be coupled more often than the offline time step. Other routines related to offline tracer modeling can be found in tracers/MOM_offline_control.F90
As can also be seen in the comments for the step_tracers subroutine, an offline time step comprises the following steps:
Using the layer thicknesses and tracer concentrations from the previous timestep, half of the accumulated vertical mixing (eatr and ebtr) is applied in the call to tracer_column_fns. For tracers whose source/sink terms need dt, this value is set to 1/2 dt_offline
Half of the accumulated surface freshwater fluxes are applied START ITERATION
Accumulated mass fluxes are used to do horizontal transport. The number of iterations used in advect_tracer is limited to 2 (e.g x->y->x->y). The remaining mass fluxes are stored for later use and resulting layer thicknesses fed into the next step
Tracers and the h-grid are regridded and remapped in a call to ALE. This allows for layers which might 'vanish' because of horizontal mass transport to be 'reinflated' and essentially allows for the vertical transport of tracers
Check that transport is done if the remaining mass fluxes equals 0 or if the max number of iterations has been reached END ITERATION
Repeat steps 1 and 2
Redistribute any residual mass fluxes that remain after the advection iterations in a barotropic manner, progressively upward through the water column.
Force a remapping to the stored layer thicknesses that correspond to the snapshot of the online model at the end of an accumulation interval
Reset T/S and h to their stored snapshotted values to prevent model drift
Evaluating the utility of an offline tracer model
How well an offline tracer model can be used as an alternative to integrating tracers online with the prognostic model must be evaluated for each application. This efficacy may be related to the native coordinate of the online model, to the length of the offline timestep, and to the behavior of the tracer itself.
A framework for formally regression testing the offline capability still needs to be developed. However, as a simple way of testing whether the offline model is nominally behaving as expected, the total inventory of the advection test tracers (tr1, tr2, etc.) should be conserved between time steps except for the last 4 decimal places. As a general guideline, an offline timestep of 5 days or less.
Runtime parameters for offline tracers
OFFLINEDIR: Input directory where the offline fields can be found
OFF_SUM_FILE: Filename where the accumulated fields can be found (e.g. horizontal mass transports)
OFF_SNAP_FILE: Filename where snapshot fields can be found (e.g. end of timestep layer thickness)
START_INDEX: Which timelevel of the input files to read first
NUMTIME: How many timelevels to read before 'looping' back to 1
FIELDS_ARE_OFFSET: True if the time-averaged fields and snapshot fields are offset by one time level, probably not needed -NUM_OFF_ITER: Maximum number of iterations to do for the nonlinear advection scheme -REDISTRIBUTE_METHOD: Redistributes any remaining horizontal fluxes throughout the rest of water column. Options are 'barotropic' which "evenly distributes flux throughout the entire water column,'upwards' which adds the maximum of the remaining flux in each layer above, and 'none' which does no redistribution"
Function/Subroutine Documentation
distribute_residual_uh_barotropic()
subroutine, public mom_offline_transport::distribute_residual_uh_barotropic (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, real, dimension(szib_(g),szj_(g),szk_(g)), intent(inout) uh)
In the case where offline advection has failed to converge, redistribute the u-flux into remainder of the water column as a barotropic equivalent.
Definition at line 518 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                           :: G
   type(verticalGrid_type),  pointer                           :: GV
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(inout)    :: h
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(inout)    :: uh
   real, dimension(SZIB_(G),SZK_(G))   :: uh2d
   real, dimension(SZIB_(G))           :: uh2d_sum
   real, dimension(SZI_(G),SZK_(G))    :: h2d
   real, dimension(SZI_(G))            :: h2d_sum
   integer :: i, j, k, m, is, ie, js, je, nz
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   do j=js,je
     uh2d_sum(:) = 0.0
     ! Copy over uh to a working array and sum up the remaining fluxes in a column
     do k=1,nz ; do i=is-1,ie
       uh2d(i,k) = uh(i,j,k)
       uh2d_sum(i) = uh2d_sum(i) + uh2d(i,k)
     enddo ; enddo
     ! Copy over h to a working array and calculate column height
     h2d_sum(:) = 0.0
     do k=1,nz ; do i=is-2,ie+1
       h2d(i,k) = h(i,j,k)*g%areaT(i,j)
       if(h(i,j,k)>gv%Angstrom) then
         h2d_sum(i) = h2d_sum(i) + h2d(i,k)
       else
         h2d(i,k) = 0.0
       endif
     enddo; enddo;
     ! Distribute flux. Note min/max is intended to make sure that the mass transport
     ! does not deplete a cell
     do i=is-1,ie
       if( uh2d_sum(i)>0.0 ) then
         do k=1,nz
           uh2d(i,k) = min(uh2d_sum(i)*(h2d(i,k)/h2d_sum(i)),h2d(i,k))
         enddo
       elseif (uh2d_sum(i)<0.0) then
         do k=1,nz
           uh2d(i,k) = max(uh2d_sum(i)*(h2d(i+1,k)/h2d_sum(i+1)),-h2d(i+1,k))
         enddo
       else
         do k=1,nz
           uh2d(i,k) = 0.0
         enddo
       endif
     enddo
     ! Update layer thicknesses at the end
     do k=1,nz ; do i=is-2,ie+1
       h(i,j,k) = h(i,j,k) + (uh2d(i-1,k) - uh2d(i,k))/g%areaT(i,j)
     enddo ; enddo
     do k=1,nz ; do i=is-1,ie
       uh(i,j,k) = uh2d(i,k)
       uh2d_sum(i) = uh2d_sum(i)-uh2d(i,k)
     enddo ; enddo
   enddo
distribute_residual_uh_upwards()
subroutine, public mom_offline_transport::distribute_residual_uh_upwards (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, real, dimension(szib_(g),szj_(g),szk_(g)), intent(inout) uh)
In the case where offline advection has failed to converge, redistribute the u-flux into layers above.
Definition at line 653 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                           :: G
   type(verticalGrid_type),  pointer                           :: GV
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(inout)     :: h
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(inout)    :: uh
   real, dimension(SZIB_(G),SZK_(G))   :: uh2d
   real, dimension(SZI_(G),SZK_(G))    :: h2d
   logical, dimension(SZK_(G))            :: filled
   real  :: uh_neglect, uh_remain, uh_LB, uh_UB, uh_add, uh_max, uh_sum
   real  :: hup, hdown, hlos, min_h
   integer :: i, j, k, m, is, ie, js, je, nz, k_rev
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   min_h = 0.1*gv%Angstrom
   do j=js,je
     ! Copy over uh and cell volume to working arrays
     do k=1,nz ; do i=is-1,ie
       uh2d(i,k) = uh(i,j,k)
     enddo ; enddo
     do k=1,nz ; do i=is-2,ie+1
       ! Subtract just a little bit of thickness to avoid roundoff errors
       h2d(i,k) = max(h(i,j,k)*g%areaT(i,j)-min_h*g%areaT(i,j),min_h*g%areaT(i,j))
     enddo ; enddo
     do i=is-1,ie
       uh_sum = sum(uh2d(i,:))
       do k=1,nz
         uh_remain = uh2d(i,k)
         uh_neglect = gv%H_subroundoff*min(g%areaT(i,j),g%areaT(i+1,j))
         if(uh_remain<-uh_neglect) then
           ! Set the mass flux to zero. This will be refilled in the first iteration
           uh2d(i,k) = 0.0
           do k_rev=k,1,-1
             ! Calculate the lower bound of uh(I)
             hlos = max(uh2d(i+1,k_rev),0.0)
             ! This lower bound is deliberately conservative to ensure that nothing will be left after
             uh_lb = min(-0.5*h2d(i+1,k_rev), -0.5*hlos, 0.0)
               ! Calculate the maximum amount that could be added
               uh_max = uh_lb-uh2d(i,k_rev)
               ! Calculate how much will actually be added to uh(I)
               uh_add = max(uh_max,uh_remain)
               ! Reduce the remaining flux
               uh_remain = uh_remain - uh_add
               uh2d(i,k_rev) = uh2d(i,k_rev) + uh_add
               if(uh2d(i,k_rev)==uh_lb) filled(k_rev)=.true.
               if(uh_remain>-uh_neglect) exit
           enddo
         elseif (uh_remain>uh_neglect) then
           ! Set the amount in the layer with remaining fluxes to zero. This will be reset
           ! in the first iteration of the redistribution loop
           uh2d(i,k) = 0.0
           ! Loop to distribute remaining flux in layers above
           do k_rev=k,1,-1
             hlos = max(0.0,-uh2d(i-1,k_rev))
             ! Calculate the upper bound of uh(I)
             uh_ub = max(0.5*h2d(i,k_rev), 0.5*h2d(i,k_rev)-hlos, 0.0)
             ! Calculate the maximum amount that could be added
             uh_max = uh_ub-uh2d(i,k_rev)
             ! Calculate how much will actually be added to uh(I)
             uh_add = min(uh_max,uh_remain)
             ! Reduce the remaining flux
             uh_remain = uh_remain - uh_add
             uh2d(i,k_rev) = uh2d(i,k_rev) + uh_add
             if(uh_remain<uh_neglect) exit
           enddo
           ! Check to see if there's any mass flux left. If so, put it in the layer beneath, unless we've bottomed out
         endif
         if(abs(uh_remain)>uh_neglect) then
           if(k<nz) then
             uh2d(i,k+1) = uh2d(i,k+1) + uh_remain
           else
             call mom_error(warning,"Water column cannot accommodate UH redistribution. Tracer will not be conserved")
           endif
         endif
       enddo
     enddo
     ! Update layer thicknesses at the end
     do k=1,nz ; do i=is,ie
       h(i,j,k) = (h(i,j,k)*g%areaT(i,j) + (uh2d(i-1,k) - uh2d(i,k)))/g%areaT(i,j)
     enddo ; enddo
     do k=1,nz ; do i=is-1,ie
       uh(i,j,k) = uh2d(i,k)
     enddo ; enddo
   enddo
References mom_error_handler::mom_error().
Referenced by mom::step_tracers().
distribute_residual_vh_barotropic()
subroutine, public mom_offline_transport::distribute_residual_vh_barotropic (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(inout) vh)
Redistribute the v-flux as a barotropic equivalent.
Definition at line 585 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                           :: G
   type(verticalGrid_type),  pointer                           :: GV
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)), intent(inout)    :: h
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(inout)    :: vh
   real, dimension(SZJB_(G),SZK_(G))   :: vh2d
   real, dimension(SZJB_(G))           :: vh2d_sum
   real, dimension(SZJ_(G),SZK_(G))    :: h2d
   real, dimension(SZJ_(G))            :: h2d_sum
   integer :: i, j, k, m, is, ie, js, je, nz
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   do i=is,ie
     vh2d_sum(:) = 0.0
     ! Copy over uh to a working array and sum up the remaining fluxes in a column
     do k=1,nz ; do j=js-1,je
       vh2d(j,k) = vh(i,j,k)
       vh2d_sum(j) = vh2d_sum(j) + vh2d(j,k)
     enddo ; enddo
     ! Copy over h to a working array and calculate column volume
     h2d_sum(:) = 0.0
     do k=1,nz ; do j=js-2,je+1
       h2d(j,k) = h(i,j,k)*g%areaT(i,j)
       if(h(i,j,k)>gv%Angstrom) then
         h2d_sum(j) = h2d_sum(j) + h2d(j,k)
       else
         h2d(j,k) = 0.0
       endif
     enddo; enddo;
     ! Distribute flux. Note min/max is intended to make sure that the mass transport
     ! does not deplete a cell
     do j=js-1,je
       if( vh2d_sum(j)>0.0 ) then
         do k=1,nz
           vh2d(j,k) = min(vh2d_sum(j)*(h2d(j,k)/h2d_sum(j)),0.5*h2d(j,k))
         enddo
       elseif (vh2d_sum(j)<0.0) then
         do k=1,nz
           vh2d(j,k) = max(vh2d_sum(j)*(h2d(j+1,k)/h2d_sum(j+1)),-0.5*h2d(j+1,k))
         enddo
       else
         do k=1,nz
           vh2d(j,k) = 0.0
         enddo
       endif
     enddo
     ! Update layer thicknesses at the end
     do k=1,nz ; do j=js-2,je+1
       h(i,j,k) = h(i,j,k) + (vh2d(j-1,k) - vh2d(j,k))/g%areaT(i,j)
     enddo ; enddo
     do k=1,nz ; do j=js-1,je
       vh(i,j,k) = vh2d(j,k)
     enddo ; enddo
   enddo
distribute_residual_vh_upwards()
subroutine, public mom_offline_transport::distribute_residual_vh_upwards (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(inout) vh)
In the case where offline advection has failed to converge, redistribute the u-flux into layers above.
Definition at line 753 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                          :: G
   type(verticalGrid_type),  pointer                          :: GV
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)),  intent(inout)   :: h
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(inout)   :: vh
   real, dimension(SZJB_(G),SZK_(G))   :: vh2d
   real, dimension(SZJB_(G))           :: vh2d_sum
   real, dimension(SZJ_(G),SZK_(G))    :: h2d
   real, dimension(SZJ_(G))            :: h2d_sum
   real  :: vh_neglect, vh_remain, vh_max, vh_add, vh_UB, vh_LB, vh_sum
   real  :: hup, hlos, min_h
   integer :: i, j, k, m, is, ie, js, je, nz, k_rev
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   min_h = 0.1*gv%Angstrom
   do i=is,ie
     ! Copy over uh and cell volume to working arrays
     do k=1,nz ; do j=js-1,je
       vh2d(j,k) = vh(i,j,k)
     enddo ; enddo
     do k=1,nz ; do j=js-2,je+1
       h2d(j,k) = (h(i,j,k)-min_h)*g%areaT(i,j)
     enddo ; enddo
     do j=js,je
       vh_sum=sum(vh2d(j,:))
       do k=1,nz
         vh_remain = vh2d(j,k)
         vh_neglect = gv%H_subroundoff*min(g%areaT(i,j),g%areaT(i,j+1))
         if(vh_remain<0.0) then
           ! Set the amount in the layer with remaining fluxes to zero. This will be reset
           ! in the first iteration of the redistribution loop
           vh2d(j,k) = 0.0
           do k_rev=k,1,-1
             ! Calculate the lower bound of uh(I)
             hlos = max(vh2d(j+1,k_rev),0.0)
             vh_lb = min(-0.5*h2d(j+1,k_rev), -0.5*h2d(j+1,k_rev)+hlos, 0.0)
             ! Calculate the maximum amount that could be added
             vh_max = vh_lb-vh2d(j,k_rev)
             ! Calculate how much will actually be added to uh(I)
             vh_add = max(vh_max,vh_remain)
             ! Reduce the remaining flux
             vh_remain = vh_remain - vh_add
             vh2d(j,k_rev) = vh2d(j,k_rev) + vh_add
             if(vh_remain>-vh_neglect) exit
           enddo
         elseif (vh_remain>0.0) then
           ! Set the amount in the layer with remaining fluxes to zero. This will be reset
           ! in the first iteration of the redistribution loop
           vh2d(j,k) = 0
           ! Loop to distribute remaining flux in layers above
           do k_rev=k,1,-1
             hlos = max(-vh2d(j-1,k_rev),0.0)
             ! Calculate the upper bound of uh(I)
             vh_ub = max(0.5*h2d(j,k_rev), 0.5*h2d(j,k_rev)-hlos, 0.0)
             ! Calculate the maximum amount that could be added
             vh_max = vh_ub-vh2d(j,k_rev)
             ! Calculate how much will actually be added to uh(I)
             vh_add = min(vh_max,vh_remain)
             ! Reduce the remaining flux
             vh_remain = vh_remain - vh_add
             vh2d(j,k_rev) = vh2d(j,k_rev) + vh_add
             if(vh_remain<vh_neglect) exit
           enddo
         endif
         if(abs(vh_remain)>vh_neglect) then
           if(k<nz) then
             vh2d(j,k+1) = vh2d(j,k+1) + vh_remain
           else
             call mom_error(warning,"Water column cannot accommodate UH redistribution. Tracer will not be conserved")
           endif
         endif
       enddo
     enddo
     ! Update layer thicknesses at the end
     do k=1,nz ; do j=js,je
       h(i,j,k) = (h(i,j,k)*g%areaT(i,j) + (vh2d(j-1,k) - vh2d(j,k)))/g%areaT(i,j)
     enddo ; enddo
     do k=1,nz ; do j=js-1,je
       vh(i,j,k) = vh2d(j,k)
     enddo ; enddo
   enddo
References mom_error_handler::mom_error().
Referenced by mom::step_tracers().
limit_mass_flux_3d()
subroutine, public mom_offline_transport::limit_mass_flux_3d (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szib_(g),szj_(g),szk_(g)), intent(inout) uh, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(inout) vh, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) ea, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) eb, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_pre, real, intent(in) max_off_cfl)
This routine limits the mass fluxes so that the a layer cannot be completely depleted. NOTE: Only used in non-ALE mode.
Definition at line 423 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                           :: G
   type(verticalGrid_type),  pointer                           :: GV
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(inout)    :: uh
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(inout)    :: vh
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(inout)    :: ea
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(inout)    :: eb
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(in)       :: h_pre
   real,                                      intent(in)       :: max_off_cfl
   ! Local variables
   integer :: i, j, k, m, is, ie, js, je, nz
   real, dimension(SZI_(G),SZJ_(G),SZK_(G))                    :: top_flux, bottom_flux
   real                                                        :: pos_flux, hvol, h_neglect, scale_factor
   ! In this subroutine, fluxes out of the box are scaled away if they deplete
   ! the layer, note that we define the positive direction as flux out of the box.
   ! Hence, uh(I-1) is multipled by negative one, but uh(I) is not
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   ! Calculate top and bottom fluxes from ea and eb. Note the explicit negative signs
   ! to enforce the positive out convention
   k = 1
   do j=js-1,je+1 ; do i=is-1,ie+1
     top_flux(i,j,k) = -ea(i,j,k)
     bottom_flux(i,j,k) = -(eb(i,j,k)-ea(i,j,k+1))
   enddo ; enddo
   do k=2, nz-1 ; do j=js-1,je+1 ; do i=is-1,ie+1
     top_flux(i,j,k) = -(ea(i,j,k)-eb(i,j,k-1))
     bottom_flux(i,j,k) = -(eb(i,j,k)-ea(i,j,k+1))
   enddo ; enddo ; enddo
   k=nz
   do j=js-1,je+1 ; do i=is-1,ie+1
     top_flux(i,j,k) = -(ea(i,j,k)-eb(i,j,k-1))
     bottom_flux(i,j,k) = -eb(i,j,k)
   enddo ; enddo
   ! Calculate sum of positive fluxes (negatives applied to enforce convention)
   ! in a given cell and scale it back if it would deplete a layer
   do k = 1, nz ; do j=js-1,je+1 ; do i=is-1,ie+1
     hvol = h_pre(i,j,k)*g%areaT(i,j)
     pos_flux  = max(0.0,-uh(i-1,j,k)) + max(0.0, -vh(i,j-1,k)) + &
       max(0.0, uh(i,j,k)) + max(0.0, vh(i,j,k)) + &
       max(0.0, top_flux(i,j,k)*g%areaT(i,j)) + max(0.0, bottom_flux(i,j,k)*g%areaT(i,j))
     if (pos_flux>hvol .and. pos_flux>0.0) then
       scale_factor = ( hvol )/pos_flux*max_off_cfl
     else ! Don't scale
       scale_factor = 1.0
     endif
     ! Scale horizontal fluxes
     if (-uh(i-1,j,k)>0) uh(i-1,j,k) = uh(i-1,j,k)*scale_factor
     if (uh(i,j,k)>0)    uh(i,j,k)   = uh(i,j,k)*scale_factor
     if (-vh(i,j-1,k)>0) vh(i,j-1,k) = vh(i,j-1,k)*scale_factor
     if (vh(i,j,k)>0)    vh(i,j,k)   = vh(i,j,k)*scale_factor
     if (k>1 .and. k<nz) then
     ! Scale interior layers
       if(top_flux(i,j,k)>0.0) then
         ea(i,j,k) = ea(i,j,k)*scale_factor
         eb(i,j,k-1) = eb(i,j,k-1)*scale_factor
       endif
       if(bottom_flux(i,j,k)>0.0) then
         eb(i,j,k) = eb(i,j,k)*scale_factor
         ea(i,j,k+1) = ea(i,j,k+1)*scale_factor
       endif
     ! Scale top layer
     elseif (k==1) then
       if(top_flux(i,j,k)>0.0)    ea(i,j,k) = ea(i,j,k)*scale_factor
       if(bottom_flux(i,j,k)>0.0) then
         eb(i,j,k)   = eb(i,j,k)*scale_factor
         ea(i,j,k+1) = ea(i,j,k+1)*scale_factor
       endif
     ! Scale bottom layer
     elseif (k==nz) then
       if(top_flux(i,j,k)>0.0) then
         ea(i,j,k)   = ea(i,j,k)*scale_factor
         eb(i,j,k-1) = eb(i,j,k-1)*scale_factor
       endif
       if (bottom_flux(i,j,k)>0.0) eb(i,j,k)=eb(i,j,k)*scale_factor
     endif
   enddo ; enddo ; enddo
next_modulo_time()
integer function mom_offline_transport::next_modulo_time (integer inidx, integer numtime)
Calculates the next timelevel to read from the input fields. This allows the 'looping' of the fields.
Definition at line 323 of file MOM_offline_control.F90.
   ! Returns the next time interval to be read
   integer                 :: numtime              ! Number of time levels in input fields
   integer                 :: inidx                ! The current time index
   integer                 :: read_index           ! The index in the input files that corresponds
                                                   ! to the current timestep
   integer                 :: next_modulo_time
   read_index = mod(inidx+1,numtime)
   if (read_index < 0)  read_index = inidx-read_index
   if (read_index == 0) read_index = numtime
   next_modulo_time = read_index
Referenced by offline_transport_init(), and transport_by_files().
offline_transport_init()
subroutine, public mom_offline_transport::offline_transport_init (type(param_file_type), intent(in) param_file, type(offline_transport_cs), intent(inout), pointer CS, type(diabatic_aux_cs), intent(in), pointer diabatic_aux_CSp, type(ocean_grid_type), intent(in) G, type(verticalgrid_type), intent(in) GV)
Initializes the control structure for offline transport and reads in some of the.
Definition at line 248 of file MOM_offline_control.F90.
   type(param_file_type),               intent(in)     :: param_file
   type(offline_transport_CS), pointer, intent(inout)  :: CS
   type(diabatic_aux_CS),          pointer, intent(in) :: diabatic_aux_CSp
   type(ocean_grid_type),               intent(in)     :: G
   type(verticalGrid_type),             intent(in)     :: GV
   character(len=40)                               :: mod = "offline_transport"
   integer :: i, j, k, is, ie, js, je, isd, ied, jsd, jed, nz
   integer :: IsdB, IedB, JsdB, JedB
   is   = g%isc   ; ie   = g%iec  ; js   = g%jsc  ; je   = g%jec ; nz = gv%ke
   isd  = g%isd   ; ied  = g%ied  ; jsd  = g%jsd  ; jed  = g%jed
   isdb = g%IsdB  ; iedb = g%IedB ; jsdb = g%JsdB ; jedb = g%JedB
   call calltree_enter("offline_transport_init, MOM_offline_control.F90")
   if (associated(cs)) then
     call mom_error(warning, "offline_transport_init called with an associated "// &
       "control structure.")
     return
   endif
   allocate(cs)
   call log_version(param_file,mod,version, &
     "This module allows for tracers to be run offline")
   ! Parse MOM_input for offline control
   call get_param(param_file, mod, "OFFLINEDIR", cs%offlinedir, &
     "Input directory where the offline fields can be found", default=" ")
   call get_param(param_file, mod, "OFF_SUM_FILE", cs%sum_file, &
     "Filename where the accumulated fields can be found", default = " ")
   call get_param(param_file, mod, "OFF_SNAP_FILE", cs%snap_file, &
     "Filename where snapshot fields can be found",default=" ")
   call get_param(param_file, mod, "START_INDEX", cs%start_index, &
     "Which time index to start from", default=1)
   call get_param(param_file, mod, "NUMTIME", cs%numtime, &
     "Number of timelevels in offline input files", default=0)
   call get_param(param_file, mod, "FIELDS_ARE_OFFSET", cs%fields_are_offset, &
     "True if the time-averaged fields and snapshot fields\n"//&
     "are offset by one time level", default=.false.)
   call get_param(param_file, mod, "REDISTRIBUTE_METHOD", cs%redistribute_method, &
     "Redistributes any remaining horizontal fluxes throughout\n"//&
     "the rest of water column. Options are 'barotropic' which\n"//&
     "evenly distributes flux throughout the entire water column,\n"//&
     "'upwards' which adds the maximum of the remaining flux in\n"//&
     "each layer above, and 'none' which does no redistribution", &
     default='barotropic')
   call get_param(param_file, mod, "NUM_OFF_ITER", cs%num_off_iter, &
     "Number of iterations to subdivide the offline tracer advection and diffusion" )
   call get_param(param_file, mod, "DT_OFFLINE", cs%dt_offline, &
     "Length of the offline timestep")
   ! Concatenate offline directory and file names
   cs%snap_file = trim(cs%offlinedir)//trim(cs%snap_file)
   cs%sum_file = trim(cs%offlinedir)//trim(cs%sum_file)
   ! Set the starting read index for time-averaged and snapshotted fields
   cs%ridx_sum = cs%start_index
   if(cs%fields_are_offset) cs%ridx_snap = next_modulo_time(cs%start_index,cs%numtime)
   if(.not. cs%fields_are_offset) cs%ridx_snap = cs%start_index
   ! Copy over parameters from other control structures
   if(associated(diabatic_aux_csp)) then
     cs%evap_CFL_limit = diabatic_aux_csp%evap_CFL_limit
     cs%minimum_forcing_depth = diabatic_aux_csp%minimum_forcing_depth
   endif
   call calltree_leave("offline_transport_init")
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), mom_error_handler::mom_error(), and next_modulo_time().
register_diags_offline_transport()
subroutine, public mom_offline_transport::register_diags_offline_transport (type(time_type), intent(in) Time, type(diag_ctrl) diag, type(offline_transport_cs), pointer CS)
Initialize additional diagnostics required for offline tracer transport.
Parameters
cs control structure for MOM
[in] time current model time
Definition at line 213 of file MOM_offline_control.F90.
   type(offline_transport_CS), pointer :: CS         !< control structure for MOM
   type(time_type), intent(in) :: Time               !< current model time
   type(diag_ctrl)             :: diag
   ! U-cell fields
   cs%id_uhr = register_diag_field('ocean_model', 'uhr', diag%axesCuL, time, &
     'Zonal thickness fluxes remaining at end of timestep', 'kg')
   cs%id_uhr_redist = register_diag_field('ocean_model', 'uhr_redist', diag%axesCuL, time, &
     'Zonal thickness fluxes to be redistributed vertically', 'kg')
   ! V-cell fields
   cs%id_vhr = register_diag_field('ocean_model', 'vhr', diag%axesCvL, time, &
     'Meridional thickness fluxes remaining at end of timestep', 'kg')
   cs%id_vhr_redist = register_diag_field('ocean_model', 'vhr_redist', diag%axesCvL, time, &
     'Meridional thickness to be redistributed vertically', 'kg')
   ! T-cell fields
   cs%id_hr  = register_diag_field('ocean_model', 'hdiff', diag%axesTL, time, &
     'Difference between the stored and calculated layer thickness', 'm')
   cs%id_ear  = register_diag_field('ocean_model', 'ear', diag%axesTL, time, &
     'Remaining thickness entrained from above', 'm')
   cs%id_ebr  = register_diag_field('ocean_model', 'ebr', diag%axesTL, time, &
     'Remaining thickness entrained from below', 'm')
   cs%id_eta_diff = register_diag_field('ocean_model','eta_diff', diag%axesT1, time, &
     'Difference in total water column height from online and offline','m')
   cs%id_h_redist = register_diag_field('ocean_model','h_redist', diag%axesTL, time, &
     'Layer thicknesses before redistribution of mass fluxes','m')
transport_by_files()
subroutine, public mom_offline_transport::transport_by_files (type(ocean_grid_type), intent(inout) G, type(verticalgrid_type), intent(inout) GV, type(offline_transport_cs), intent(inout) CS, real, dimension(szi_(g),szj_(g),szk_(g)) h_end, real, dimension(szi_(g),szj_(g),szk_(g)) eatr, real, dimension(szi_(g),szj_(g),szk_(g)) ebtr, real, dimension(szib_(g),szj_(g),szk_(g)) uhtr, real, dimension(szi_(g),szjb_(g),szk_(g)) vhtr, real, dimension(szib_(g),szj_(g)) khdt_x, real, dimension(szi_(g),szjb_(g)) khdt_y, real, dimension(szi_(g),szj_(g),szk_(g)) temp, real, dimension(szi_(g),szj_(g),szk_(g)) salt, type(forcing) fluxes, logical, optional do_ale_in)
Controls the reading in 3d mass fluxes, diffusive fluxes, and other fields stored in a previous integration of the online model.
Definition at line 83 of file MOM_offline_control.F90.
   type(ocean_grid_type),                     intent(inout)    :: G
   type(verticalGrid_type),                   intent(inout)    :: GV
   type(offline_transport_CS),                intent(inout)    :: CS
   logical, optional                                           :: do_ale_in
   !! Mandatory variables
   ! Fields at U-points
   !  3D
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G))                   :: uhtr
   !  2D
   real, dimension(SZIB_(G),SZJ_(G))                           :: khdt_x
   ! Fields at V-points
   !  3D
   real, dimension(SZI_(G),SZJB_(G),SZK_(G))                   :: vhtr
   !  2D
   real, dimension(SZI_(G),SZJB_(G))                           :: khdt_y
   ! Fields at T-point
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) :: &
     h_end, &
     eatr, ebtr, &
     temp, salt
   type(forcing)                                               :: fluxes
   logical                                                     :: do_ale
   integer :: i, j, k, is, ie, js, je, nz
   do_ale = .false.;
   if (present(do_ale_in) ) do_ale = do_ale_in
   is   = g%isc   ; ie   = g%iec  ; js   = g%jsc  ; je   = g%jec ; nz = gv%ke
   call calltree_enter("transport_by_files, MOM_offline_control.F90")
   !! Time-summed fields
   ! U-grid
   call read_data(cs%sum_file, 'uhtr_sum',     uhtr,domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=east)
   call read_data(cs%sum_file, 'khdt_x_sum', khdt_x,domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=east)
   ! V-grid
   call read_data(cs%sum_file, 'vhtr_sum',     vhtr, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=north)
   call read_data(cs%sum_file, 'khdt_y_sum', khdt_y, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=north)
   ! T-grid
   call read_data(cs%sum_file, 'ea_sum',   eatr, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=center)
   call read_data(cs%sum_file, 'eb_sum',   ebtr, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=center)
   !! Time-averaged fields
   call read_data(cs%snap_file, 'temp',   temp, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=center)
   call read_data(cs%snap_file, 'salt',   salt, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_sum,position=center)
   !! Read snapshot fields (end of time interval timestamp)
   call read_data(cs%snap_file, 'h_end', h_end, domain=g%Domain%mpp_domain, &
     timelevel=cs%ridx_snap,position=center)
   ! Apply masks at T, U, and V points
   do k=1,nz ; do j=js,je ; do i=is,ie
     if(g%mask2dT(i,j)<1.0) then
       h_end(i,j,k) = gv%Angstrom
       eatr(i,j,k) = 0.0
       ebtr(i,j,k) = 0.0
     endif
   enddo; enddo ; enddo
   do k=1,nz ; do j=js-1,je ; do i=is,ie
     if(g%mask2dCv(i,j)<1.0) then
       khdt_y(i,j) = 0.0
       vhtr(i,j,k) = 0.0
     endif
   enddo; enddo ; enddo
   do k=1,nz ; do j=js,je ; do i=is-1,ie
     if(g%mask2dCu(i,j)<1.0) then
       khdt_x(i,j) = 0.0
       uhtr(i,j,k) = 0.0
     endif
   enddo; enddo ; enddo
   ! This block makes sure that the fluxes control structure, which may not be used in the solo_driver,
   ! contains netMassIn and netMassOut which is necessary for the applyTracerBoundaryFluxesInOut routine
   if (do_ale) then
     if (.not. ASSOCIATED(fluxes%netMassOut)) then
       ALLOCATE(fluxes%netMassOut(g%isd:g%ied,g%jsd:g%jed))
       fluxes%netMassOut(:,:) = 0.0
     endif
     if (.not. ASSOCIATED(fluxes%netMassIn)) then
       ALLOCATE(fluxes%netMassIn(g%isd:g%ied,g%jsd:g%jed))
       fluxes%netMassIn(:,:) = 0.0
     endif
     call read_data(cs%sum_file,'massout_flux_sum',fluxes%netMassOut, domain=g%Domain%mpp_domain, &
         timelevel=cs%ridx_snap,position=center)
     call read_data(cs%sum_file,'massin_flux_sum', fluxes%netMassIn,  domain=g%Domain%mpp_domain, &
         timelevel=cs%ridx_snap,position=center)
   endif
   !! Make sure all halos have been updated
   ! Vector fields
   call pass_vector(uhtr, vhtr, g%Domain)
   call pass_vector(khdt_x, khdt_y, g%Domain)
   ! Scalar fields
   call pass_var(h_end, g%Domain)
   call pass_var(eatr, g%Domain)
   call pass_var(ebtr, g%Domain)
   call pass_var(temp, g%Domain)
   call pass_var(salt, g%Domain)
   if (do_ale) then
     call pass_var(fluxes%netMassOut,g%Domain)
     call pass_var(fluxes%netMassIn,g%Domain)
   endif
   ! Update the read indices
   cs%ridx_snap = next_modulo_time(cs%ridx_snap,cs%numtime)
   cs%ridx_sum = next_modulo_time(cs%ridx_sum,cs%numtime)
   call calltree_leave("transport_by_file")
References mom_error_handler::calltree_enter(), mom_error_handler::calltree_leave(), and next_modulo_time().
update_h_horizontal_flux()
subroutine, public mom_offline_transport::update_h_horizontal_flux (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szib_(g),szj_(g),szk_(g)), intent(in) uhtr, real, dimension(szi_(g),szjb_(g),szk_(g)), intent(in) vhtr, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_pre, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h_new)
This updates thickness based on the convergence of horizontal mass fluxes NOTE: Only used in non-ALE mode.
Definition at line 343 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                           :: G
   type(verticalGrid_type),  pointer                           :: GV
   real, dimension(SZIB_(G),SZJ_(G),SZK_(G)), intent(in)       :: uhtr
   real, dimension(SZI_(G),SZJB_(G),SZK_(G)), intent(in)       :: vhtr
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(in)       :: h_pre
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(inout)    :: h_new
   ! Local variables
   integer :: i, j, k, m, is, ie, js, je, nz
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   do k = 1, nz
     do i=is-1,ie+1 ; do j=js-1,je+1
       h_new(i,j,k) = max(0.0, g%areaT(i,j)*h_pre(i,j,k) + &
         ((uhtr(i-1,j,k) - uhtr(i,j,k)) + (vhtr(i,j-1,k) - vhtr(i,j,k))))
       ! In the case that the layer is now dramatically thinner than it was previously,
       ! add a bit of mass to avoid truncation errors.  This will lead to
       ! non-conservation of tracers
       h_new(i,j,k) = h_new(i,j,k) + &
         max(gv%Angstrom, 1.0e-13*h_new(i,j,k) - g%areaT(i,j)*h_pre(i,j,k))
       ! Convert back to thickness
       h_new(i,j,k) = h_new(i,j,k)/g%areaT(i,j)
     enddo ; enddo
   enddo
update_h_vertical_flux()
subroutine, public mom_offline_transport::update_h_vertical_flux (type(ocean_grid_type), pointer G, type(verticalgrid_type), pointer GV, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) ea, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) eb, real, dimension(szi_(g),szj_(g),szk_(g)), intent(in) h_pre, real, dimension(szi_(g),szj_(g),szk_(g)), intent(inout) h_new)
Updates layer thicknesses due to vertical mass transports NOTE: Only used in non-ALE configuration.
Definition at line 377 of file MOM_offline_control.F90.
   type(ocean_grid_type),    pointer                           :: G
   type(verticalGrid_type),  pointer                           :: GV
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(in)       :: ea
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(in)       :: eb
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(in)       :: h_pre
   real, dimension(SZI_(G),SZJ_(G),SZK_(G)) , intent(inout)    :: h_new
   ! Local variables
   integer :: i, j, k, m, is, ie, js, je, nz
   ! Set index-related variables for fields on T-grid
   is  = g%isc ; ie  = g%iec ; js  = g%jsc ; je  = g%jec ; nz = gv%ke
   ! Update h_new with convergence of vertical mass transports
   do j=js-1,je+1
     do i=is-1,ie+1
       ! Top layer
       h_new(i,j,1) = max(0.0, h_pre(i,j,1) + (eb(i,j,1) - ea(i,j,2) + ea(i,j,1) ))
       h_new(i,j,1) = h_new(i,j,1) + &
           max(0.0, 1.0e-13*h_new(i,j,1) - h_pre(i,j,1))
       ! Bottom layer
 !        h_new(i,j,nz) = h_pre(i,j,nz) + (ea(i,j,nz) - eb(i,j,nz-1)+eb(i,j,nz))
       h_new(i,j,nz) = max(0.0, h_pre(i,j,nz) + (ea(i,j,nz) - eb(i,j,nz-1)+eb(i,j,nz)))
       h_new(i,j,nz) = h_new(i,j,nz) + &
           max(0.0, 1.0e-13*h_new(i,j,nz) - h_pre(i,j,nz))
     enddo
     ! Interior layers
     do k=2,nz-1 ; do i=is-1,ie+1
       h_new(i,j,k) = max(0.0, h_pre(i,j,k) + ((ea(i,j,k) - eb(i,j,k-1)) + &
           (eb(i,j,k) - ea(i,j,k+1))))
       h_new(i,j,k) = h_new(i,j,k) + &
         max(0.0, 1.0e-13*h_new(i,j,k) - h_pre(i,j,k))
     enddo ; enddo
   enddo