MOM6: user_initialization Module Reference
user_initialization Module Reference
Functions/Subroutines
subroutine, public user_set_coord (Rlay, g_prime, GV, param_file, eqn_of_state)
Set vertical coordinates.
subroutine, public user_initialize_topography (D, G, param_file, max_depth)
Initialize topography.
subroutine, public user_initialize_thickness (h, G, param_file, T)
initialize thicknesses.
subroutine, public user_initialize_velocity (u, v, G, param_file)
initialize velocities.
subroutine, public user_init_temperature_salinity (T, S, G, param_file, eqn_of_state)
This function puts the initial layer temperatures and salinities into T(:,:,:) and S(:,:,:).
subroutine, public user_init_mixed_layer_density (Rml, G, param_file, use_temperature, eqn_of_state, T, S, P_Ref)
Set initial potential density of the mixed layer.
subroutine, public user_initialize_sponges (G, use_temperature, tv, param_file, CSp, h)
Set up the sponges.
subroutine, public user_set_obc_data (OBC, tv, G, param_file, tr_Reg)
This subroutine sets the properties of flow at open boundary conditions.
subroutine, public user_set_rotation (G, param_file)
subroutine write_user_log (param_file)
Write output about the parameter values being used.
Function/Subroutine Documentation
user_init_mixed_layer_density()
subroutine, public user_initialization::user_init_mixed_layer_density (real, dimension(szi_(g), szj_(g), szk_(g)), intent(out) Rml, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, logical, intent(in) use_temperature, type(eos_type), optional, pointer eqn_of_state, real, dimension(szi_(g), szj_(g), szk_(g)), intent(in), optional T, real, dimension(szi_(g), szj_(g), szk_(g)), intent(in), optional S, real, intent(in), optional P_Ref)
Set initial potential density of the mixed layer.
Parameters
[in] g Ocean grid structure.
[out] rml Mixed layer potential density.
[in] param_file A structure indicating the open file to parse for model parameter values.
[in] use_temperature Whether to use potential temperature.
eqn_of_state integer that selects the equation of state.
[in] t Model potential temperature.
[in] s Model salinity.
[in] p_ref The coordinate-density reference pressure in Pa.
Definition at line 155 of file user_initialization.F90.
   type(ocean_grid_type),                         intent(in)  :: G        !< Ocean grid structure.
   real, dimension(SZI_(G), SZJ_(G), SZK_(G)),    intent(out) :: Rml      !< Mixed layer potential density.
   type(param_file_type),                         intent(in)  :: param_file !< A structure indicating the
                                                                          !! open file to parse for model
                                                                          !! parameter values.
   logical,                                       intent(in)  :: use_temperature !< Whether to use potential
                                                                          !! temperature.
   type(EOS_type),                      optional, pointer     :: eqn_of_state !< integer that selects the
                                                                          !! equation of state.
   real, dimension(SZI_(G), SZJ_(G), SZK_(G)), optional, intent(in) :: T  !< Model potential temperature.
   real, dimension(SZI_(G), SZJ_(G), SZK_(G)), optional, intent(in) :: S  !< Model salinity.
   real,                                optional, intent(in)  :: P_Ref    !< The coordinate-density
                                                                          !! reference pressure in Pa.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_init_mixed_layer_density: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   rml(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
user_init_temperature_salinity()
subroutine, public user_initialization::user_init_temperature_salinity (real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) T, real, dimension(szi_(g),szj_(g), szk_(g)), intent(out) S, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
This function puts the initial layer temperatures and salinities into T(:,:,:) and S(:,:,:).
Parameters
[in] g Ocean grid structure.
[out] t Potential temperature (degC).
[out] s Salinity (ppt).
[in] param_file A structure indicating the open file to parse for model parameter values.
eqn_of_state Integer that selects the equation of state.
Definition at line 132 of file user_initialization.F90.
   type(ocean_grid_type),                     intent(in)  :: G !< Ocean grid structure.
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: T !< Potential temperature (degC).
   real, dimension(SZI_(G),SZJ_(G), SZK_(G)), intent(out) :: S !< Salinity (ppt).
   type(param_file_type),                     intent(in)  :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   type(EOS_type),                            pointer     :: eqn_of_state !< Integer that selects the
                                                             !! equation of state.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_init_temperature_salinity: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   t(:,:,1) = 0.0
   s(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
user_initialize_sponges()
subroutine, public user_initialization::user_initialize_sponges (type(ocean_grid_type), intent(in) G, logical, intent(in) use_temperature, type(thermo_var_ptrs), intent(in) tv, type(param_file_type), intent(in) param_file, type(sponge_cs), pointer CSp, real, dimension(szi_(g), szj_(g), szk_(g)), intent(in) h)
Set up the sponges.
Parameters
[in] g Ocean grid structure.
[in] use_temperature Whether to use potential temperature.
[in] tv A structure containing pointers to any available thermodynamic fields, potential temperature and salinity or mixed layer density. Absent fields have NULL ptrs.
[in] param_file A structure indicating the open file to parse for model parameter values.
csp A pointer to the sponge control structure.
[in] h Layer thicknesses.
Definition at line 180 of file user_initialization.F90.
   type(ocean_grid_type), intent(in) :: G               !< Ocean grid structure.
   logical,               intent(in) :: use_temperature !< Whether to use potential
                                                        !! temperature.
   type(thermo_var_ptrs), intent(in) :: tv              !< A structure containing pointers
                                                        !! to any available thermodynamic
                                                        !! fields, potential temperature and
                                                        !! salinity or mixed layer density.
                                                        !! Absent fields have NULL ptrs.
   type(param_file_type), intent(in) :: param_file      !< A structure indicating the
                                                        !! open file to parse for model
                                                        !! parameter values.
   type(sponge_CS),       pointer    :: CSp             !< A pointer to the sponge control
                                                        !! structure.
   real, dimension(SZI_(G), SZJ_(G), SZK_(G)), intent(in) :: h !< Layer thicknesses.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_sponges: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_state_initialization::mom_initialize_state().
user_initialize_thickness()
subroutine, public user_initialization::user_initialize_thickness (real, dimension(szi_(g),szj_(g),szk_(g)), intent(out) h, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, dimension(szi_(g),szj_(g), szk_(g)), intent(in) T)
initialize thicknesses.
Parameters
[in] g The ocean's grid structure.
[out] h The thicknesses being initialized.
[in] param_file A structure indicating the open file to parse for model parameter values.
[in] t Potential temperature.
Definition at line 93 of file user_initialization.F90.
   type(ocean_grid_type), intent(in)           :: G          !< The ocean's grid structure.
   real, intent(out), dimension(SZI_(G),SZJ_(G),SZK_(G)) :: h !< The thicknesses being
                                                             !! initialized.
   type(param_file_type), intent(in)           :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   real, intent(in), dimension(SZI_(G),SZJ_(G), SZK_(G))  :: T !< Potential temperature.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_thickness: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   h(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
user_initialize_topography()
subroutine, public user_initialization::user_initialize_topography (real, dimension(g%isd:g%ied,g%jsd:g%jed), intent(out) D, type(dyn_horgrid_type), intent(in) G, type(param_file_type), intent(in) param_file, real, intent(in) max_depth)
Initialize topography.
Parameters
[in] g The dynamic horizontal grid type
[out] d Ocean bottom depth in m
[in] param_file Parameter file structure
[in] max_depth Maximum depth of model in m
Definition at line 75 of file user_initialization.F90.
   type(dyn_horgrid_type),             intent(in)  :: G !< The dynamic horizontal grid type
   real, dimension(G%isd:G%ied,G%jsd:G%jed), &
                                       intent(out) :: D !< Ocean bottom depth in m
   type(param_file_type),              intent(in)  :: param_file !< Parameter file structure
   real,                               intent(in)  :: max_depth  !< Maximum depth of model in m
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_topography: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   d(:,:) = 0.0
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_fixed_initialization::mom_initialize_topography().
user_initialize_velocity()
subroutine, public user_initialization::user_initialize_velocity (real, dimension(szib_(g), szj_(g), szk_(g)), intent(out) u, real, dimension(szi_(g), szjb_(g), szk_(g)), intent(out) v, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file)
initialize velocities.
Parameters
[in] g Ocean grid structure.
[out] u i-component of velocity [m/s]
[out] v j-component of velocity [m/s]
[in] param_file A structure indicating the open file to parse for model parameter values.
Definition at line 112 of file user_initialization.F90.
   type(ocean_grid_type),                       intent(in)  :: G !< Ocean grid structure.
   real, dimension(SZIB_(G), SZJ_(G), SZK_(G)), intent(out) :: u !< i-component of velocity [m/s]
   real, dimension(SZI_(G), SZJB_(G), SZK_(G)), intent(out) :: v !< j-component of velocity [m/s]
   type(param_file_type),                       intent(in)  :: param_file !< A structure indicating the
                                                             !! open file to parse for model
                                                             !! parameter values.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_initialize_velocity: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   u(:,:,1) = 0.0
   v(:,:,1) = 0.0
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
user_set_coord()
subroutine, public user_initialization::user_set_coord (real, dimension(:), intent(out) Rlay, real, dimension(:), intent(out) g_prime, type(verticalgrid_type), intent(in) GV, type(param_file_type), intent(in) param_file, type(eos_type), pointer eqn_of_state)
Set vertical coordinates.
Parameters
[in] gv The ocean's vertical grid structure.
[out] rlay Layer potential density.
[out] g_prime The reduced gravity at each interface, in m s-2.
[in] param_file A structure indicating the open file to parse for model parameter values.
eqn_of_state Integer that selects the equation of state.
Definition at line 52 of file user_initialization.F90.
   type(verticalGrid_type), intent(in)  :: GV         !< The ocean's vertical grid
                                                      !! structure.
   real, dimension(:),      intent(out) :: Rlay       !< Layer potential density.
   real, dimension(:),      intent(out) :: g_prime    !< The reduced gravity at
                                                      !! each interface, in m s-2.
   type(param_file_type),   intent(in)  :: param_file !< A structure indicating the
                                                      !! open file to parse for model
                                                      !! parameter values.
   type(EOS_type),          pointer     :: eqn_of_state !< Integer that selects the
                                                      !! equation of state.
   call mom_error(fatal, &
    "USER_initialization.F90, USER_set_coord: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   rlay(:) = 0.0
   g_prime(:) = 0.0
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
Referenced by mom_coord_initialization::mom_initialize_coord().
user_set_obc_data()
subroutine, public user_initialization::user_set_obc_data (type(ocean_obc_type), pointer OBC, type(thermo_var_ptrs), intent(in) tv, type(ocean_grid_type), intent(in) G, type(param_file_type), intent(in) param_file, type(tracer_registry_type), pointer tr_Reg)
This subroutine sets the properties of flow at open boundary conditions.
Parameters
obc This open boundary condition type specifies whether, where, and what open boundary conditions are used.
[in] tv A structure containing pointers to any available thermodynamic fields, including potential temperature and salinity or mixed layer density. Absent fields have NULL ptrs.
[in] g The ocean's grid structure.
[in] param_file A structure indicating the open file to parse for model parameter values.
tr_reg Tracer registry.
Definition at line 204 of file user_initialization.F90.
   type(ocean_OBC_type),       pointer    :: OBC   !< This open boundary condition type specifies
                                                   !! whether, where, and what open boundary
                                                   !! conditions are used.
   type(thermo_var_ptrs),      intent(in) :: tv    !< A structure containing pointers to any
                                        !! available thermodynamic fields, including potential
                                        !! temperature and salinity or mixed layer density. Absent
                                        !! fields have NULL ptrs.
   type(ocean_grid_type),      intent(in) :: G     !< The ocean's grid structure.
   type(param_file_type),      intent(in) :: param_file !< A structure indicating the
                                                   !! open file to parse for model
                                                   !! parameter values.
   type(tracer_registry_type), pointer    :: tr_Reg !< Tracer registry.
 !  call MOM_error(FATAL, &
 !   "USER_initialization.F90, USER_set_OBC_data: " // &
 !   "Unmodified user routine called - you must edit the routine to use it")
   if (first_call) call write_user_log(param_file)
References write_user_log().
user_set_rotation()
subroutine, public user_initialization::user_set_rotation (type(ocean_grid_type), intent(inout) G, type(param_file_type), intent(in) param_file)
Definition at line 225 of file user_initialization.F90.
   type(ocean_grid_type), intent(inout) :: G
   type(param_file_type), intent(in)    :: param_file
   call mom_error(fatal, &
    "USER_initialization.F90, USER_set_rotation: " // &
    "Unmodified user routine called - you must edit the routine to use it")
   if (first_call) call write_user_log(param_file)
References mom_error_handler::mom_error(), and write_user_log().
write_user_log()
subroutine user_initialization::write_user_log (type(param_file_type), intent(in) param_file) private
Write output about the parameter values being used.
Parameters
[in] param_file A structure indicating the open file to parse for model parameter values.
Definition at line 237 of file user_initialization.F90.
   type(param_file_type), intent(in) :: param_file !< A structure indicating the
                                                   !! open file to parse for model
                                                   !! parameter values.
 ! This include declares and sets the variable "version".
 #include "version_variable.h"
   character(len=40)  :: mod = "user_initialization" ! This module's name.
   call log_version(param_file, mod, version)
   first_call = .false.
Referenced by user_init_mixed_layer_density(), user_init_temperature_salinity(), user_initialize_sponges(), user_initialize_thickness(), user_initialize_topography(), user_initialize_velocity(), user_set_coord(), user_set_obc_data(), and user_set_rotation().