MOM6: gsw_mod_teos10_constants Module Reference
gsw_mod_teos10_constants Module Reference
Variables
real(r8), parameter db2pa = 1.0e4_r8
real(r8), parameter rec_db2pa = 1.0e-4_r8
real(r8), parameter pa2db = 1.0e-4_r8
real(r8), parameter rec_pa2db = 1.0e4_r8
real(r8), parameter pi = 3.141592653589793_r8
real(r8), parameter deg2rad = pi/180.0_r8
real(r8), parameter rad2deg = 180.0_r8/pi
real(r8), parameter gamma = 2.26e-7_r8
real(r8), parameter gsw_cp0 = 3991.86795711963_r8
real(r8), parameter gsw_t0 = 273.15_r8
real(r8), parameter gsw_p0 = 101325.0_r8
real(r8), parameter gsw_sso = 35.16504_r8
real(r8), parameter gsw_sqrtsso = 5.930011804372737_r8
real(r8), parameter gsw_ups = gsw_sso/35.0_r8
real(r8), parameter gsw_sfac = 0.0248826675584615_r8
real(r8), parameter offset = 5.971840214030754e-1_r8
real(r8), parameter gsw_c3515 = 42.9140_r8
real(r8), parameter gsw_soncl = 1.80655_r8
real(r8), parameter gsw_valence_factor = 1.2452898_r8
real(r8), parameter gsw_atomic_weight = 31.4038218_r8
Variable Documentation
db2pa
real (r8), parameter gsw_mod_teos10_constants::db2pa = 1.0e4_r8
Definition at line 9 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: db2pa = 1.0e4_r8
deg2rad
real (r8), parameter gsw_mod_teos10_constants::deg2rad = pi/180.0_r8
Definition at line 16 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: deg2rad = pi/180.0_r8
gamma
real (r8), parameter gsw_mod_teos10_constants::gamma = 2.26e-7_r8
Definition at line 19 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gamma = 2.26e-7_r8
gsw_atomic_weight
real (r8), parameter gsw_mod_teos10_constants::gsw_atomic_weight = 31.4038218_r8
Definition at line 67 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_atomic_weight = 31.4038218_r8
gsw_c3515
real (r8), parameter gsw_mod_teos10_constants::gsw_c3515 = 42.9140_r8
Definition at line 53 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_c3515 = 42.9140_r8
gsw_cp0
real (r8), parameter gsw_mod_teos10_constants::gsw_cp0 = 3991.86795711963_r8
Definition at line 24 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_cp0 = 3991.86795711963_r8
Referenced by gsw_ct_from_pt(), and gsw_pt_from_ct().
gsw_p0
real (r8), parameter gsw_mod_teos10_constants::gsw_p0 = 101325.0_r8
Definition at line 32 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_p0 = 101325.0_r8
gsw_sfac
real (r8), parameter gsw_mod_teos10_constants::gsw_sfac = 0.0248826675584615_r8
Definition at line 45 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_sfac = 0.0248826675584615_r8
Referenced by gsw_ct_from_pt(), gsw_gibbs_pt0_pt0(), gsw_rho_first_derivatives(), gsw_specvol(), and gsw_specvol_first_derivatives().
gsw_soncl
real (r8), parameter gsw_mod_teos10_constants::gsw_soncl = 1.80655_r8
Definition at line 57 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_soncl = 1.80655_r8
gsw_sqrtsso
real (r8), parameter gsw_mod_teos10_constants::gsw_sqrtsso = 5.930011804372737_r8
Definition at line 37 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_sqrtsso = 5.930011804372737_r8
gsw_sso
real (r8), parameter gsw_mod_teos10_constants::gsw_sso = 35.16504_r8
Definition at line 36 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_sso = 35.16504_r8
gsw_t0
real (r8), parameter gsw_mod_teos10_constants::gsw_t0 = 273.15_r8
Definition at line 28 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_t0 = 273.15_r8
Referenced by gsw_pt_from_ct().
gsw_ups
real (r8), parameter gsw_mod_teos10_constants::gsw_ups = gsw_sso/35.0_r8
Definition at line 41 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_ups = gsw_sso/35.0_r8
Referenced by gsw_pt_from_ct(), gsw_sp_from_sr(), and gsw_sr_from_sp().
gsw_valence_factor
real (r8), parameter gsw_mod_teos10_constants::gsw_valence_factor = 1.2452898_r8
Definition at line 62 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: gsw_valence_factor = 1.2452898_r8
offset
real (r8), parameter gsw_mod_teos10_constants::offset = 5.971840214030754e-1_r8
Definition at line 49 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: offset = 5.971840214030754e-1_r8
Referenced by gsw_rho_first_derivatives(), gsw_specvol(), and gsw_specvol_first_derivatives().
pa2db
real (r8), parameter gsw_mod_teos10_constants::pa2db = 1.0e-4_r8
Definition at line 12 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: pa2db = 1.0e-4_r8
Referenced by gsw_rho_first_derivatives().
pi
real (r8), parameter gsw_mod_teos10_constants::pi = 3.141592653589793_r8
Definition at line 15 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: pi = 3.141592653589793_r8
rad2deg
real (r8), parameter gsw_mod_teos10_constants::rad2deg = 180.0_r8/pi
Definition at line 17 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: rad2deg = 180.0_r8/pi
rec_db2pa
real (r8), parameter gsw_mod_teos10_constants::rec_db2pa = 1.0e-4_r8
Definition at line 10 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: rec_db2pa = 1.0e-4_r8
rec_pa2db
real (r8), parameter gsw_mod_teos10_constants::rec_pa2db = 1.0e4_r8
Definition at line 13 of file gsw_mod_teos10_constants.f90.
 real(r8), parameter :: rec_pa2db = 1.0e4_r8